
config.new_step = {
	[1001] = {
		[1] = {
			id = 1001,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1001,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/task_com/touch_com"},
			delay = 0,
			click_rect = {x=350,y=935,width=0,height=0},
			do_times = 1,
			open_view = {},
		},
	},
	[1002] = {
		[1] = {
			id = 1002,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1001,on_view={"ui_task/task_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/task_dialog_view/btn_finish"},
			delay = 0,
			click_rect = {x=361,y=1194},
			do_times = 1,
			open_view = {},
		},
	},
	[1003] = {
		[1] = {
			id = 1003,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1002,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/task_com/touch_com"},
			delay = 0,
			click_rect = {x=350,y=935,width=0,height=0},
			do_times = 1,
			open_view = {},
		},
	},
	[1004] = {
		[1] = {
			id = 1004,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1005, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_pet"},
			delay = 2,
			click_rect = {x=253,y=997},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
		},
		[2] = {
			id = 1004,
			step = 2,
			key_step = 0,
			open_event = "nil",
			active_cond = {on_view={"ui_pet/pet_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_view/btn_battle"},
			delay = 0,
			click_rect = {x=287,y=904},
			do_times = 1,
			open_view = {},
		},
	},
	[1005] = {
		[1] = {
			id = 1005,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1006, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_skill"},
			delay = 2,
			click_rect = {x=145,y=1004},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
		},
		[2] = {
			id = 1005,
			step = 2,
			key_step = 0,
			open_event = "nil",
			active_cond = {on_view={"ui_skill/skill_view"}},
			next_cond = {click_btn_name = "ui_skill/skill_view/skill_template/skill_upgrade_item/btn_upgrade"},
			delay = 0,
			click_rect = {x=464,y=1174},
			do_times = 1,
			open_view = {},
		},
		[3] = {
			id = 1005,
			step = 3,
			key_step = 0,
			open_event = "nil",
			active_cond = {on_view={"ui_skill/skill_view"}},
			next_cond = {click_btn_name = "ui_skill/skill_view/close_btn"},
			delay = 0,
			click_rect = {x=617,y=49},
			do_times = 1,
			open_view = {},
		},
	},
	[1006] = {
		[1] = {
			id = 1006,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1021, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_foundry"},
			delay = 2,
			click_rect = {x=255,y=995},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
		},
		[2] = {
			id = 1006,
			step = 2,
			key_step = 0,
			open_event = "nil",
			active_cond = {on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_stren"},
			delay = 0,
			click_rect = {x=456,y=1177},
			do_times = 1,
			open_view = {},
		},
		[3] = {
			id = 1006,
			step = 3,
			key_step = 0,
			open_event = "nil",
			active_cond = {on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_close"},
			delay = 0,
			click_rect = {x=631,y=47},
			do_times = 1,
			open_view = {},
		},
	},
	-- [1007] = {
	-- 	[1] = {
	-- 		id = 1007,
	-- 		step = 1,
	-- 		key_step = 1,
	-- 		open_event = "focus_on_view",
	-- 		active_cond = {task_id=1029, on_view={"ui_main/new_main_view"}},
	-- 		next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_hero"},
	-- 		delay = 2,
	-- 		click_rect = {x=258,y=1095},
	-- 		do_times = 1,
	-- 		open_view = {"MainUICtrl", 1},
	-- 	},
	-- },
}