
return {
    [game.OperateType.Stop] = "game/operate/operate_stop",
    [game.OperateType.Move] = "game/operate/operate_move",
    [game.OperateType.Sequence] = "game/operate/operate_sequence",
    [game.OperateType.FindWay] = "game/operate/operate_find_way",
    [game.OperateType.Attack] = "game/operate/operate_attack",
    [game.OperateType.MoveAttack] = "game/operate/operate_move_attack",
    [game.OperateType.AttackTarget] = "game/operate/operate_attack_target",
    [game.OperateType.Callback] = "game/operate/operate_callback",
    [game.OperateType.Gather] = "game/operate/operate_gather",
    [game.OperateType.Practice] = "game/operate/operate_practice",

    [game.OperateType.Jump] = "game/operate/operate_jump",
    [game.OperateType.Empty] = "game/operate/operate_empty",
    [game.OperateType.GetItem] = "game/operate/operate_get_item",
    [game.OperateType.GetTaskReward] = "game/operate/operate_get_task_reward",
    [game.OperateType.OpenView] = "game/operate/operate_open_view",
    
    
    [game.OperateType.Hang] = "game/operate/operate_hang",
    [game.OperateType.HangAttack] = "game/operate/operate_hang_attack",
    [game.OperateType.HangFindWay] = "game/operate/operate_hang_findway",

    [game.OperateType.Talk] = "game/operate/operate_talk",
    [game.OperateType.TalkToNpc] = "game/operate/operate_talk_to_npc",
    [game.OperateType.GoToNpc] = "game/operate/operate_go_to_npc",
    [game.OperateType.ChangeScene] = "game/operate/operate_change_scene",
    [game.OperateType.HangMonster] = "game/operate/operate_hang_monster",
    [game.OperateType.KillMonster] = "game/operate/operate_kill_monster",
    [game.OperateType.HangSequence] = "game/operate/operate_hang_sequence",
    [game.OperateType.ClickNpc] = "game/operate/operate_click_npc",
    [game.OperateType.Joystick] = "game/operate/operate_joystick",
    [game.OperateType.JoystickAttack] = "game/operate/operate_joystick_attack",
    [game.OperateType.HangJoystick] = "game/operate/operate_hang_joystick",
    [game.OperateType.HangStay] = "game/operate/operate_hang_stay",
    [game.OperateType.HangPet] = "game/operate/operate_hang_pet",
    [game.OperateType.HangRobot] = "game/operate/operate_hang_robot",
    [game.OperateType.MakeTeamFollow] = "game/operate/operate_make_team_follow",
    [game.OperateType.GoToGather] = "game/operate/operate_go_to_gather",
    [game.OperateType.GoToScenePos] = "game/operate/operate_go_to_scene_pos",
    [game.OperateType.Carry] = "game/operate/operate_carry",
    [game.OperateType.HangGather] = "game/operate/operate_hang_gather",
    [game.OperateType.HangCatchPet] = "game/operate/operate_hang_catch_pet",
    [game.OperateType.HangTask] = "game/operate/operate_hang_task",
    [game.OperateType.HangGuildCarry] = "game/operate/operate_hang_guild_carry",
    [game.OperateType.HangTaskDungeon] = "game/operate/operate_hang_task_dungeon",
    [game.OperateType.HangTaskMonster] = "game/operate/operate_hang_task_monster",
    [game.OperateType.HangTaskGather] = "game/operate/operate_hang_task_gather",
    [game.OperateType.HangGuildTask] = "game/operate/operate_hang_guild_task",
    [game.OperateType.HangGuildTaskPet] = "game/operate/operate_hang_guild_task_pet",
    [game.OperateType.HangGuildTaskVisit] = "game/operate/operate_hang_guild_task_visit",
    [game.OperateType.HangGuildTaskTreasure] = "game/operate/operate_hang_guild_task_treasure",
    [game.OperateType.HangTaskTreasureMap] = "game/operate/operate_hang_task_treasure_map",
    [game.OperateType.UseTreasureMap] = "game/operate/operate_use_treasure_map",
    [game.OperateType.HangTaskCxdt] = "game/operate/operate_hang_task_cxdt",
    [game.OperateType.GoToTalkNpc] = "game/operate/operate_go_to_talk_npc",
	[game.OperateType.HangTaskCatchPet] = "game/operate/operate_hang_task_catch_pet",
    [game.OperateType.GoToMonsterPos] = "game/operate/operate_go_to_monster_pos",
    [game.OperateType.HangGatherQueue] = "game/operate/operate_hang_gather_queue",
    [game.OperateType.HangTaskGatherQueue] = "game/operate/operate_hang_task_gather_queue",
    [game.OperateType.HangTaskThief] = "game/operate/operate_hang_task_thief",
    [game.OperateType.HangTaskExamineNew] = "game/operate/operate_hang_task_examine_new",
    [game.OperateType.HangDailyTask] = "game/operate/operate_hang_daily_task",
    [game.OperateType.HangMainSubTask] = "game/operate/operate_hang_main_sub_task",
    [game.OperateType.HangWeaponSoul] = "game/operate/operate_hang_weapon_soul",
    [game.OperateType.HangRunloopTask] = "game/operate/operate_hang_runloop_task",
    [game.OperateType.HangDungeon] = "game/operate/operate_hang_dungeon",

    [game.OperateType.Follow] = "game/operate/operate_follow",
}
