config.vow_task = {
    [1001] = {
        id = 1001,
        day = 1,
        type = 1,
        deed = 10,
        times = 1,
        arg = 0,
        desc = "把對方加為好友",
    },
    [1002] = {
        id = 1002,
        day = 1,
        type = 2,
        deed = 15,
        times = 1,
        arg = 0,
        desc = "給對方私聊發送壹句話",
    },
    [1003] = {
        id = 1003,
        day = 1,
        type = 7,
        deed = 15,
        times = 1,
        arg = 201,
        desc = "完成壹次雙人動作（君子酒）",
    },
    [1004] = {
        id = 1004,
        day = 1,
        type = 7,
        deed = 10,
        times = 1,
        arg = 202,
        desc = "完成壹次雙人動作（相思結）",
    },
    [1005] = {
        id = 1005,
        day = 1,
        type = 3,
        deed = 10,
        times = 1,
        arg = 0,
        desc = "給對方私聊發送壹句語音",
    },
    [2001] = {
        id = 2001,
        day = 2,
        type = 3,
        deed = 20,
        times = 1,
        arg = 0,
        desc = "給對方私聊發送壹句語音",
    },
    [2002] = {
        id = 2002,
        day = 2,
        type = 6,
        deed = 20,
        times = 20,
        arg = 0,
        desc = "與對方組隊擊殺20只野怪",
    },
    [2003] = {
        id = 2003,
        day = 2,
        type = 7,
        deed = 10,
        times = 1,
        arg = 201,
        desc = "完成壹次雙人動作（君子酒）",
    },
    [2004] = {
        id = 2004,
        day = 2,
        type = 4,
        deed = 10,
        times = 1,
        arg = 900,
        desc = "組隊完成壹次四絕莊副本（可助戰）",
    },
    [2005] = {
        id = 2005,
        day = 2,
        type = 4,
        deed = 10,
        times = 1,
        arg = 800,
        desc = "組隊完成壹次燕子塢副本（可助戰）",
    },
    [3001] = {
        id = 3001,
        day = 3,
        type = 3,
        deed = 20,
        times = 1,
        arg = 0,
        desc = "給對方私聊發送壹句語音",
    },
    [3002] = {
        id = 3002,
        day = 3,
        type = 6,
        deed = 20,
        times = 20,
        arg = 0,
        desc = "與對方組隊擊殺20只野怪",
    },
    [3003] = {
        id = 3003,
        day = 3,
        type = 7,
        deed = 10,
        times = 1,
        arg = 202,
        desc = "完成壹次雙人動作（相思結）",
    },
    [3004] = {
        id = 3004,
        day = 3,
        type = 5,
        deed = 10,
        times = 5,
        arg = 0,
        desc = "組隊完成馬賊活動（5次即可）",
    },
    [3005] = {
        id = 3005,
        day = 3,
        type = 4,
        deed = 10,
        times = 1,
        arg = 1200,
        desc = "組隊完成壹次珍瓏棋局（可助戰）",
    },
    [4001] = {
        id = 4001,
        day = 4,
        type = 3,
        deed = 20,
        times = 1,
        arg = 0,
        desc = "給對方私聊發送壹句語音",
    },
    [4002] = {
        id = 4002,
        day = 4,
        type = 9,
        deed = 30,
        times = 1,
        arg = 0,
        desc = "為對方放壹枚煙花（需向對方使用）",
    },
    [4003] = {
        id = 4003,
        day = 4,
        type = 7,
        deed = 10,
        times = 1,
        arg = 202,
        desc = "完成壹次雙人動作（相思結）",
    },
    [4004] = {
        id = 4004,
        day = 4,
        type = 4,
        deed = 10,
        times = 1,
        arg = 800,
        desc = "組隊完成壹次燕子塢副本（可助戰）",
    },
    [4005] = {
        id = 4005,
        day = 4,
        type = 4,
        deed = 10,
        times = 1,
        arg = 1000,
        desc = "組隊完成壹次縹緲峰副本（可助戰）",
    },
    [5001] = {
        id = 5001,
        day = 5,
        type = 4,
        deed = 20,
        times = 1,
        arg = 1100,
        desc = "組隊完成壹次稀世藏寶圖副本",
    },
    [5002] = {
        id = 5002,
        day = 5,
        type = 6,
        deed = 20,
        times = 20,
        arg = 0,
        desc = "與對方組隊擊殺20只野怪",
    },
    [5003] = {
        id = 5003,
        day = 5,
        type = 7,
        deed = 10,
        times = 1,
        arg = 201,
        desc = "完成壹次雙人動作（君子酒）",
    },
    [5004] = {
        id = 5004,
        day = 5,
        type = 4,
        deed = 10,
        times = 1,
        arg = 900,
        desc = "組隊完成壹次四絕莊副本（可助戰）",
    },
    [5005] = {
        id = 5005,
        day = 5,
        type = 4,
        deed = 10,
        times = 1,
        arg = 700,
        desc = "組隊完成壹次老三環副本（可助戰）",
    },
    [6001] = {
        id = 6001,
        day = 6,
        type = 9,
        deed = 35,
        times = 1,
        arg = 0,
        desc = "為對方放壹枚煙花（需向對方使用）",
    },
    [6002] = {
        id = 6002,
        day = 6,
        type = 3,
        deed = 20,
        times = 1,
        arg = 0,
        desc = "給對方私聊發送壹句語音",
    },
    [6003] = {
        id = 6003,
        day = 6,
        type = 7,
        deed = 10,
        times = 1,
        arg = 202,
        desc = "完成壹次雙人動作（相思結）",
    },
    [6004] = {
        id = 6004,
        day = 6,
        type = 4,
        deed = 10,
        times = 1,
        arg = 900,
        desc = "組隊完成壹次四絕莊副本（可助戰）",
    },
    [6005] = {
        id = 6005,
        day = 6,
        type = 5,
        deed = 10,
        times = 10,
        arg = 0,
        desc = "組隊完成馬賊活動（10次即可）",
    },
    [7001] = {
        id = 7001,
        day = 7,
        type = 8,
        deed = 35,
        times = 1,
        arg = 0,
        desc = "使用喇叭向對方示意（刷喇叭即可）",
    },
    [7002] = {
        id = 7002,
        day = 7,
        type = 4,
        deed = 20,
        times = 1,
        arg = 1100,
        desc = "組隊完成壹次稀世藏寶圖副本",
    },
    [7003] = {
        id = 7003,
        day = 7,
        type = 7,
        deed = 10,
        times = 1,
        arg = 202,
        desc = "完成壹次雙人動作（相思結）",
    },
    [7004] = {
        id = 7004,
        day = 7,
        type = 4,
        deed = 10,
        times = 1,
        arg = 800,
        desc = "組隊完成壹次燕子塢副本（可助戰）",
    },
    [7005] = {
        id = 7005,
        day = 7,
        type = 4,
        deed = 10,
        times = 1,
        arg = 1000,
        desc = "組隊完成壹次縹緲峰副本（可助戰）",
    },
}