config.combat_power = {
	[1] = {
		value = 0.5,
		sign = "hp_lim",
		seq = 1,
		name = "生命",
		attr_name = "生      命",
	},
	[2] = {
		value = 0,
		sign = "hp_rec",
		seq = 2,
		name = "回血",
		attr_name = "回      血",
	},
	[3] = {
		value = 0,
		sign = "mp_lim",
		seq = 3,
		name = "氣量上限",
		attr_name = "氣      量",
	},
	[4] = {
		value = 0,
		sign = "mp_rec",
		seq = 4,
		name = "氣量回復",
		attr_name = "回      氣",
	},
	[5] = {
		value = 5,
		sign = "att",
		seq = 5,
		name = "攻擊",
		attr_name = "攻      擊",
	},
	[6] = {
		value = 5,
		sign = "def",
		seq = 6,
		name = "防禦",
		attr_name = "防      禦",
	},
	[7] = {
		value = 0,
		sign = "att_speed",
		seq = 7,
		name = "攻擊速度",
		attr_name = "攻擊速度",
	},
	[8] = {
		value = 0,
		sign = "move_speed",
		seq = 8,
		name = "移動速度",
		attr_name = "移動速度",
	},
	[9] = {
		value = 15,
		sign = "hit",
		seq = 9,
		name = "命中",
		attr_name = "命      中",
	},
	[10] = {
		value = 15,
		sign = "dodge",
		seq = 10,
		name = "閃避",
		attr_name = "閃      避",
	},
	[11] = {
		value = 15,
		sign = "crit_hurt",
		seq = 11,
		name = "暴擊傷害",
		attr_name = "暴擊傷害",
	},
	[12] = {
		value = 15,
		sign = "crit_def",
		seq = 12,
		name = "暴擊防禦",
		attr_name = "暴擊防禦",
	},
	[13] = {
		value = 5,
		sign = "igndef_hurt",
		seq = 13,
		name = "無視傷害",
		attr_name = "無視傷害",
	},
	[14] = {
		value = 5,
		sign = "igndef_def",
		seq = 14,
		name = "無視防禦",
		attr_name = "無視防禦",
	},
	[15] = {
		value = 0,
		sign = "resist",
		seq = 15,
		name = "格擋",
		attr_name = "格      擋",
	},
	[16] = {
		value = 0,
		sign = "wreck",
		seq = 16,
		name = "破擊",
		attr_name = "破      擊",
	},
	[17] = {
		value = 0,
		sign = "hurt_add",
		seq = 17,
		name = "傷害加成 萬分比",
		attr_name = "傷害加成",
	},
	[18] = {
		value = 0,
		sign = "hurt_red",
		seq = 18,
		name = "傷害減免 萬分比",
		attr_name = "傷害減免",
	},
	[19] = {
		value = 0,
		sign = "crit_add",
		seq = 19,
		name = "會傷加成 萬分比",
		attr_name = "會傷加成",
	},
	[20] = {
		value = 0,
		sign = "crit_red",
		seq = 20,
		name = "會傷減免 萬分比",
		attr_name = "會傷減免",
	},
	[21] = {
		value = 0,
		sign = "pvp_add",
		seq = 21,
		name = "PVP傷害加成 萬分比",
		attr_name = "PVP傷加",
	},
	[22] = {
		value = 0,
		sign = "pvp_red",
		seq = 22,
		name = "PVP傷害減免 萬分比",
		attr_name = "PVP傷減",
	},
	[23] = {
		value = 0,
		sign = "pve_add",
		seq = 23,
		name = "PVE傷害加成 萬分比",
		attr_name = "PVE傷加",
	},
	[24] = {
		value = 0,
		sign = "pve_red",
		seq = 24,
		name = "PVE傷害減免 萬分比",
		attr_name = "PVE傷減",
	},
}
