config.lucky_rotary = {
	[1] = {
        [1] = {
            id = 1,
            conf_index = 1,
            drop_id = 2101,
            is_rumor = 0,
            is_rare = 0,
        },
        [2] = {
            id = 2,
            conf_index = 1,
            drop_id = 2102,
            is_rumor = 0,
            is_rare = 0,
        },
        [3] = {
            id = 3,
            conf_index = 1,
            drop_id = 2103,
            is_rumor = 0,
            is_rare = 0,
        },
        [4] = {
            id = 4,
            conf_index = 1,
            drop_id = 2104,
            is_rumor = 0,
            is_rare = 0,
        },
        [5] = {
            id = 5,
            conf_index = 1,
            drop_id = 2201,
            is_rumor = 0,
            is_rare = 0,
        },
        [6] = {
            id = 6,
            conf_index = 1,
            drop_id = 2202,
            is_rumor = 0,
            is_rare = 0,
        },
        [7] = {
            id = 7,
            conf_index = 1,
            drop_id = 2203,
            is_rumor = 0,
            is_rare = 0,
        },
        [8] = {
            id = 8,
            conf_index = 1,
            drop_id = 2204,
            is_rumor = 0,
            is_rare = 0,
        },
        [9] = {
            id = 9,
            conf_index = 1,
            drop_id = 2301,
            is_rumor = 1,
            is_rare = 1,
        },
        [10] = {
            id = 10,
            conf_index = 1,
            drop_id = 2302,
            is_rumor = 1,
            is_rare = 1,
        },
        [11] = {
            id = 11,
            conf_index = 1,
            drop_id = 2303,
            is_rumor = 1,
            is_rare = 1,
        },
        [12] = {
            id = 12,
            conf_index = 1,
            drop_id = 2304,
            is_rumor = 1,
            is_rare = 1,
        },
    },
	[2] = {
        [1] = {
            id = 1,
            conf_index = 2,
            drop_id = 2101,
            is_rumor = 0,
            is_rare = 0,
        },
        [2] = {
            id = 2,
            conf_index = 2,
            drop_id = 2102,
            is_rumor = 0,
            is_rare = 0,
        },
        [3] = {
            id = 3,
            conf_index = 2,
            drop_id = 2103,
            is_rumor = 0,
            is_rare = 0,
        },
        [4] = {
            id = 4,
            conf_index = 2,
            drop_id = 2104,
            is_rumor = 0,
            is_rare = 0,
        },
        [5] = {
            id = 5,
            conf_index = 2,
            drop_id = 2201,
            is_rumor = 0,
            is_rare = 0,
        },
        [6] = {
            id = 6,
            conf_index = 2,
            drop_id = 2202,
            is_rumor = 0,
            is_rare = 0,
        },
        [7] = {
            id = 7,
            conf_index = 2,
            drop_id = 2203,
            is_rumor = 0,
            is_rare = 0,
        },
        [8] = {
            id = 8,
            conf_index = 2,
            drop_id = 2204,
            is_rumor = 0,
            is_rare = 0,
        },
        [9] = {
            id = 9,
            conf_index = 2,
            drop_id = 2301,
            is_rumor = 1,
            is_rare = 1,
        },
        [10] = {
            id = 10,
            conf_index = 2,
            drop_id = 2302,
            is_rumor = 1,
            is_rare = 1,
        },
        [11] = {
            id = 11,
            conf_index = 2,
            drop_id = 2303,
            is_rumor = 1,
            is_rare = 1,
        },
        [12] = {
            id = 12,
            conf_index = 2,
            drop_id = 2304,
            is_rumor = 1,
            is_rare = 1,
        },
    },
}