config.guild_research_info = {
	[1001] = {
		id = 1001,
		type = 0,
		need_lv = 2,
		prev = 0,
		need_num = 0,
		desc = "幫會修煉消耗的幫貢減少%d點",
		name = "冥想",
		icon = "sc_01",
	},
	[1002] = {
		id = 1002,
		type = 0,
		need_lv = 2,
		prev = 0,
		need_num = 0,
		desc = "幫會維護是消耗的資金減少%d%%",
		name = "建設",
		icon = "sc_02",
	},
	[1003] = {
		id = 1003,
		type = 0,
		need_lv = 2,
		prev = 0,
		need_num = 0,
		desc = "從農政全書、山海經、徐霞客遊記、齊民要術中獲得熟練度提高%d點",
		name = "自給自足",
		icon = "sc_03",
	},
	[1004] = {
		id = 1004,
		type = 0,
		need_lv = 3,
		prev = 1002,
		need_num = 0,
		desc = "幫會工資中所有活動的綁定元寶提高%d點",
		name = "日進鬥金",
		icon = "sc_04",
	},
	[1005] = {
		id = 1005,
		type = 0,
		need_lv = 3,
		prev = 0,
		need_num = 0,
		desc = "從酬謝函中獲得的幫貢提高%d點",
		name = "宴請達人",
		icon = "sc_05",
	},
	[1006] = {
		id = 1006,
		type = 0,
		need_lv = 4,
		prev = 0,
		need_num = 4,
		desc = "每次幫會任務獲得的幫貢和幫會通寶提高%d點",
		name = "骨幹人員",
		icon = "sc_06",
	},
	[1007] = {
		id = 1007,
		type = 0,
		need_lv = 4,
		prev = 0,
		need_num = 4,
		desc = "從幫會殺星和幫會禦膳比拼中獲得的幫會資金提高%d%%",
		name = "財源滾滾",
		icon = "sc_07",
	},
	[1008] = {
		id = 1008,
		type = 0,
		need_lv = 4,
		prev = 1003,
		need_num = 4,
		desc = "活力上限提高%d點",
		name = "活力充沛",
		icon = "sc_08",
	},
	[1009] = {
		id = 1009,
		type = 0,
		need_lv = 4,
		prev = 0,
		need_num = 5,
		desc = "每次幫會煉金獲得的銀兩提高%d",
		name = "點石成金",
		icon = "sc_09",
	},
	[1010] = {
		id = 1010,
		type = 0,
		need_lv = 5,
		prev = 1007,
		need_num = 7,
		desc = "從幫會殺星和幫會禦膳比拼中獲得的幫貢和通寶提高%d%%",
		name = "豐衣足食",
		icon = "sc_10",
	},
	[2001] = {
		id = 2001,
		type = 1,
		need_lv = 2,
		prev = 0,
		need_num = 0,
		desc = "幫會守衛戰天元、日曜、月曜鼎的血量提高%d%%",
		name = "團結",
		icon = "js_01",
	},
	[2002] = {
		id = 2002,
		type = 1,
		need_lv = 2,
		prev = 0,
		need_num = 0,
		desc = "幫會宣戰消耗的點數降低%d%%",
		name = "爭強好勝",
		icon = "js_02",
	},
	[2003] = {
		id = 2003,
		type = 1,
		need_lv = 2,
		prev = 0,
		need_num = 0,
		desc = "在領地爭奪戰中出竅時間減少%d秒",
		name = "復活加速",
		icon = "js_03",
	},
	[2004] = {
		id = 2004,
		type = 1,
		need_lv = 3,
		prev = 0,
		need_num = 2,
		desc = "押送幫會鏢車的收益提高%d%%",
		name = "只賺不賠",
		icon = "js_04",
	},
	[2005] = {
		id = 2005,
		type = 1,
		need_lv = 4,
		prev = 2001,
		need_num = 4,
		desc = "幫會守衛戰獲得的幫會資金提高%d%%",
		name = "守衛之星",
		icon = "js_05",
	},
	[2006] = {
		id = 2006,
		type = 1,
		need_lv = 4,
		prev = 0,
		need_num = 4,
		desc = "在領地爭奪戰中奪旗時間減少%d%%",
		name = "奪旗強化",
		icon = "js_06",
	},
	[2007] = {
		id = 2007,
		type = 1,
		need_lv = 4,
		prev = 2003,
		need_num = 4,
		desc = "領地和鳳凰古城爭奪戰中蠻力戰鼓的效果延長%d秒",
		name = "蠻力戰鼓",
		icon = "js_07",
	},
	[2008] = {
		id = 2008,
		type = 1,
		need_lv = 4,
		prev = 2004,
		need_num = 5,
		desc = "幫會運鏢獲得中攔截獲得幫會資金和幫會貢獻提高%d%%",
		name = "劫富濟貧",
		icon = "js_08",
	},
	[2009] = {
		id = 2009,
		type = 1,
		need_lv = 5,
		prev = 2006,
		need_num = 7,
		desc = "在領地戰中，對己方戰旗附近敵方造成生活提高%d%%",
		name = "戰旗守衛",
		icon = "js_09",
	},
	[2010] = {
		id = 2010,
		type = 1,
		need_lv = 5,
		prev = 2007,
		need_num = 7,
		desc = "領地和鳳凰古城爭奪戰中鼓舞戰鼓的效果延長%d秒",
		name = "鼓舞戰鼓",
		icon = "js_10",
	},
}
