config.examine_bank = {
    [1] = {
        id = 1,
        question = '羊肉泡饃是我國哪壹城市的風味食品？',
        options1 = "南沙",
        options2 = "西安",
        options3 = "北京",
        options4 = "上海",
        answer = 2,
    },
    [2] = {
        id = 2,
        question = '從月球上看地球的唯壹建築物是：',
        options1 = "什麽也看不到",
        options2 = "長城",
        options3 = "金字塔",
        options4 = "故宮",
        answer = 1,
    },
    [3] = {
        id = 3,
        question = '是誰發現了好望角：',
        options1 = "哥倫布",
        options2 = "迪亞士",
        options3 = "孟加拉",
        options4 = "索爾",
        answer = 2,
    },
    [4] = {
        id = 4,
        question = '世界上刮風最多的地方是：',
        options1 = "南極洲",
        options2 = "澳洲",
        options3 = "北美洲",
        options4 = "非洲",
        answer = 1,
    },
    [5] = {
        id = 5,
        question = '"草堂留後世，詩聖著千秋"指的是：',
        options1 = "李白",
        options2 = "杜甫",
        options3 = "杜牧",
        options4 = "白居易",
        answer = 2,
    },
    [6] = {
        id = 6,
        question = '男士穿燕尾服系的是：',
        options1 = "領結",
        options2 = "領帶",
        options3 = "皮帶",
        options4 = "鞋帶",
        answer = 1,
    },
    [7] = {
        id = 7,
        question = '古人放爆竹最早是為了：',
        options1 = "慶祝節日",
        options2 = "驅逐瘟神疫鬼",
        options3 = "沒什麽意義",
        options4 = "聽個響",
        answer = 2,
    },
    [8] = {
        id = 8,
        question = '我國的南北分界線是：',
        options1 = "秦嶺-淮河",
        options2 = "長江",
        options3 = "黃河",
        options4 = "三峽",
        answer = 1,
    },
    [9] = {
        id = 9,
        question = '俗稱"四不象"的動物是：',
        options1 = "駝羊",
        options2 = "麋鹿",
        options3 = "犀牛",
        options4 = "麒麟",
        answer = 2,
    },
    [10] = {
        id = 10,
        question = '龍在十二生肖中排行第幾？',
        options1 = "5",
        options2 = "6",
        options3 = "7",
        options4 = "8",
        answer = 1,
    },
    [11] = {
        id = 11,
        question = '歷史上"樂不思蜀"的是哪位皇帝？',
        options1 = "劉禪",
        options2 = "劉備",
        options3 = "劉邦",
        options4 = "劉秀",
        answer = 1,
    },
    [12] = {
        id = 12,
        question = '"不為五鬥米折腰"最早是指誰不願為五鬥米折腰？',
        options1 = "白居易",
        options2 = "陶淵明",
        options3 = "李白",
        options4 = "杜甫",
        answer = 2,
    },
    [13] = {
        id = 13,
        question = '"明月幾時有？把酒問青天。"是誰的詩詞？',
        options1 = "蘇浙",
        options2 = "蘇東坡",
        options3 = "李白",
        options4 = "杜甫",
        answer = 2,
    },
    [14] = {
        id = 14,
        question = '鼎有幾個"耳朵"？',
        options1 = "2個",
        options2 = "3個",
        options3 = "4個",
        options4 = "5個",
        answer = 1,
    },
    [15] = {
        id = 15,
        question = '"尚方寶劍"中的"尚方"最初指的是：',
        options1 = "至高無上",
        options2 = "官署名",
        options3 = "剛剛",
        options4 = "方形",
        answer = 2,
    },
    [16] = {
        id = 16,
        question = '美國的國花是什麽花？',
        options1 = "喇叭花",
        options2 = "玫瑰",
        options3 = "康乃磬",
        options4 = "郁金香",
        answer = 2,
    },
    [17] = {
        id = 17,
        question = '哪種動物被稱為"沙漠之舟"？',
        options1 = "駱駝",
        options2 = "鴕鳥",
        options3 = "斑馬",
        options4 = "犀牛",
        answer = 1,
    },
    [18] = {
        id = 18,
        question = '現在美國國旗星條旗上有多少顆星:',
        options1 = "51顆",
        options2 = "50顆",
        options3 = "49顆",
        options4 = "48顆",
        answer = 2,
    },
    [19] = {
        id = 19,
        question = '著名的【大衛像】是誰的作品？',
        options1 = "米開朗琪羅",
        options2 = "拉斐爾",
        options3 = "達芬奇",
        options4 = "阿基米德",
        answer = 1,
    },
    [20] = {
        id = 20,
        question = '在中國的習俗裏，壹年的最後壹天叫：',
        options1 = "平安夜",
        options2 = "除夕",
        options3 = "元旦",
        options4 = "春節",
        answer = 2,
    },
    [21] = {
        id = 21,
        question = '我國最大的淡水湖是：',
        options1 = "鄱陽湖",
        options2 = "洞庭湖",
        options3 = "青海湖",
        options4 = "太湖",
        answer = 1,
    },
    [22] = {
        id = 22,
        question = '人生自古誰無死，留取丹心照汗青"的作者是：',
        options1 = "嶽飛",
        options2 = "文天祥",
        options3 = "辛棄疾",
        options4 = "蘇軾",
        answer = 2,
    },
    [23] = {
        id = 23,
        question = '數學符號中的"0"起源於：',
        options1 = "古印度",
        options2 = "中國",
        options3 = "古希臘",
        options4 = "古埃及",
        answer = 1,
    },
    [24] = {
        id = 24,
        question = '下面哪壹種是能降血壓的蔬菜？',
        options1 = "菠菜",
        options2 = "生菜",
        options3 = "白菜",
        options4 = "芹菜",
        answer = 4,
    },
    [25] = {
        id = 25,
        question = '我國古代"八卦"中的符號"--"代表',
        options1 = "乾",
        options2 = "坤",
        options3 = "陰",
        options4 = "陽",
        answer = 3,
    },
    [26] = {
        id = 26,
        question = '中國的四大發明不包括：',
        options1 = "火藥",
        options2 = "印刷術",
        options3 = "指南針",
        options4 = "地動儀",
        answer = 4,
    },
    [27] = {
        id = 27,
        question = '按照風俗習慣戒指帶在中指上表示：',
        options1 = "未婚",
        options2 = "已婚",
        options3 = "正在戀愛之中",
        options4 = "失戀",
        answer = 3,
    },
    [28] = {
        id = 28,
        question = '"破釜沈舟"這個成語出於哪次戰爭？',
        options1 = "官渡之戰",
        options2 = "長平之戰",
        options3 = "赤壁之戰",
        options4 = "巨鹿之戰",
        answer = 4,
    },
    [29] = {
        id = 29,
        question = '我國陸上極高與極低相差：',
        options1 = "3000多米",
        options2 = "7000多米",
        options3 = "9000多米",
        options4 = "18000多米",
        answer = 3,
    },
    [30] = {
        id = 30,
        question = '長槍與短槍哪個射出去的子彈打得遠？',
        options1 = "壹樣遠",
        options2 = "不確定",
        options3 = "短槍",
        options4 = "長槍",
        answer = 4,
    },
    [31] = {
        id = 31,
        question = '"伯樂壹顧"中的伯樂看的是什麽：',
        options1 = "豬",
        options2 = "牛",
        options3 = "馬",
        options4 = "人才",
        answer = 3,
    },
    [32] = {
        id = 32,
        question = '【清明上河圖】是壹幅：',
        options1 = "山水畫",
        options2 = "水墨畫",
        options3 = "風景畫",
        options4 = "社會風俗畫",
        answer = 4,
    },
    [33] = {
        id = 33,
        question = '"三過家門而不入"是哪壹歷史人物的故事？',
        options1 = "舜",
        options2 = "堯",
        options3 = "禹",
        options4 = "羿",
        answer = 3,
    },
    [34] = {
        id = 34,
        question = '坦克是哪個國家發明的？',
        options1 = "德國",
        options2 = "蘇聯",
        options3 = "法國",
        options4 = "英國",
        answer = 4,
    },
    [35] = {
        id = 35,
        question = '維納斯是希臘神話中的：',
        options1 = "女神",
        options2 = "力量之神",
        options3 = "愛神與美神",
        options4 = "智慧之神",
        answer = 3,
    },
    [36] = {
        id = 36,
        question = '被譽為"鋼琴之王"的作曲家是：',
        options1 = "肖邦",
        options2 = "莫紮特",
        options3 = "李斯特",
        options4 = "貝多芬",
        answer = 3,
    },
    [37] = {
        id = 37,
        question = '藍鯨和海豚，哪個遊的快？',
        options1 = "壹樣快",
        options2 = "不確定",
        options3 = "海豚",
        options4 = "藍鯨",
        answer = 4,
    },
    [38] = {
        id = 38,
        question = '中國神話中相傳誰人發明"鉆木取火"？',
        options1 = "炎帝",
        options2 = "皇帝",
        options3 = "燧人氏",
        options4 = "神農氏",
        answer = 3,
    },
    [39] = {
        id = 39,
        question = '【指環王】中的指環可以讓人？',
        options1 = "不死",
        options2 = "點石成金",
        options3 = "力大無窮",
        options4 = "隱身",
        answer = 4,
    },
    [40] = {
        id = 40,
        question = '【哈利波特】電影中，哈利如何逃避三頭狗進入地穴？',
        options1 = "使用隱形衣",
        options2 = "除妳武器",
        options3 = "什麽也沒做",
        options4 = "使用催眠咒",
        answer = 3,
    },
    [41] = {
        id = 41,
        question = '【白雪公主】的作者是誰',
        options1 = "金庸",
        options2 = "高爾基",
        options3 = "安徒生",
        options4 = "格林",
        answer = 4,
    },
    [42] = {
        id = 42,
        question = '地殼裏存在最多的金屬元素是：',
        options1 = "銅",
        options2 = "鋼",
        options3 = "鐵",
        options4 = "鋁",
        answer = 4,
    },
    [43] = {
        id = 43,
        question = '哪個器官制造了血液？',
        options1 = "骨頭",
        options2 = "肺",
        options3 = "紅骨髓",
        options4 = "心臟",
        answer = 3,
    },
    [44] = {
        id = 44,
        question = '白鰭豚用什麽呼吸？',
        options1 = "皮膚",
        options2 = "口",
        options3 = "腮",
        options4 = "肺",
        answer = 4,
    },
    [45] = {
        id = 45,
        question = '"卅"比"廿"多多少？',
        options1 = "30",
        options2 = "20",
        options3 = "10",
        options4 = "1",
        answer = 3,
    },
    [46] = {
        id = 46,
        question = '鳩摩智是哪國國師？',
        options1 = "吐蕃",
        options2 = "大理",
        options3 = "西夏",
        options4 = "遼國",
        answer = 1,
    },
    [47] = {
        id = 47,
        question = '天龍八部是誰的作品？',
        options1 = "梁羽生",
        options2 = "金庸",
        options3 = "古龍",
        options4 = "溫瑞安",
        answer = 2,
    },
    [48] = {
        id = 48,
        question = '誰殺死了阿朱？',
        options1 = "段正淳",
        options2 = "阿紫",
        options3 = "喬峰",
        options4 = "慕容復",
        answer = 3,
    },
    [49] = {
        id = 49,
        question = '慕容復的手下，哪個最愛和人鬥嘴？',
        options1 = "風波惡",
        options2 = "鄧百川",
        options3 = "公冶乾",
        options4 = "包不同",
        answer = 4,
    },
    [50] = {
        id = 50,
        question = '慕容復的手下，哪個最愛和人打架？',
        options1 = "風波惡",
        options2 = "包不同",
        options3 = "鄧百川",
        options4 = "公冶乾",
        answer = 1,
    },
    [51] = {
        id = 51,
        question = '喬峰是哪國人？',
        options1 = "大宋",
        options2 = "契丹",
        options3 = "西夏",
        options4 = "女真",
        answer = 2,
    },
    [52] = {
        id = 52,
        question = '位列四大惡人之首的是誰？',
        options1 = "葉二娘",
        options2 = "嶽老三",
        options3 = "段延慶",
        options4 = "雲中鶴",
        answer = 3,
    },
    [53] = {
        id = 53,
        question = '位列四大惡人之二的是誰？',
        options1 = "段延慶",
        options2 = "嶽老三",
        options3 = "雲中鶴",
        options4 = "葉二娘",
        answer = 4,
    },
    [54] = {
        id = 54,
        question = '位列四大惡人之三的是誰？',
        options1 = "嶽老三",
        options2 = "段延慶",
        options3 = "葉二娘",
        options4 = "雲中鶴",
        answer = 1,
    },
    [55] = {
        id = 55,
        question = '位列四大惡人之四的是誰？',
        options1 = "段延慶",
        options2 = "雲中鶴",
        options3 = "葉二娘",
        options4 = "嶽老三",
        answer = 2,
    },
    [56] = {
        id = 56,
        question = '虛竹的母親是誰？',
        options1 = "王夫人",
        options2 = "李秋水",
        options3 = "葉二娘",
        options4 = "余婆",
        answer = 3,
    },
    [57] = {
        id = 57,
        question = '大宋武林群豪在何處伏擊了蕭遠山夫婦？',
        options1 = "山海關",
        options2 = "函谷關",
        options3 = "居庸關",
        options4 = "雁門關",
        answer = 4,
    },
    [58] = {
        id = 58,
        question = '率領大宋武林群豪伏擊蕭遠山夫婦的是誰？',
        options1 = "玄慈",
        options2 = "汪劍通",
        options3 = "段正淳",
        options4 = "慕容博",
        answer = 1,
    },
    [59] = {
        id = 59,
        question = '娶得西夏公主的是誰？',
        options1 = "段譽",
        options2 = "虛竹",
        options3 = "喬峰",
        options4 = "慕容復",
        answer = 2,
    },
    [60] = {
        id = 60,
        question = '虛竹的父親是什麽身份？',
        options1 = "丐幫幫主",
        options2 = "大理皇帝",
        options3 = "少林方丈",
        options4 = "遼國貴族",
        answer = 3,
    },
    [61] = {
        id = 61,
        question = '段譽為何百毒不侵？',
        options1 = "天賦異稟",
        options2 = "神功護體",
        options3 = "精通醫理",
        options4 = "誤食朱蛤",
        answer = 4,
    },
    [62] = {
        id = 62,
        question = '綽號修羅刀的女子是誰？',
        options1 = "秦紅梅",
        options2 = "刀白鳳",
        options3 = "葉二娘",
        options4 = "甘寶寶",
        answer = 1,
    },
    [63] = {
        id = 63,
        question = '那個武功不是大理段氏的獨門武功？',
        options1 = "壹陽指",
        options2 = "淩波微步",
        options3 = "六脈神劍",
        options4 = "段家劍",
        answer = 2,
    },
    [64] = {
        id = 64,
        question = '曼陀山莊種滿了什麽花？',
        options1 = "月季花",
        options2 = "牡丹花",
        options3 = "山茶花",
        options4 = "玫瑰花",
        answer = 3,
    },
    [65] = {
        id = 65,
        question = '綽號俏藥叉的女子是誰？',
        options1 = "秦紅梅",
        options2 = "刀白鳳",
        options3 = "葉二娘",
        options4 = "甘寶寶",
        answer = 4,
    },
    [66] = {
        id = 66,
        question = '閃電貂是誰的寵物？',
        options1 = "鐘靈",
        options2 = "木婉清",
        options3 = "阿紫",
        options4 = "阿朱",
        answer = 1,
    },
    [67] = {
        id = 67,
        question = '黑玫瑰是誰的坐騎？',
        options1 = "鐘靈",
        options2 = "木婉清",
        options3 = "阿碧",
        options4 = "王語嫣",
        answer = 2,
    },
    [68] = {
        id = 68,
        question = '阿碧的居所叫什麽名字？',
        options1 = "聽香水榭",
        options2 = "瑯嬛福地",
        options3 = "琴韻小築",
        options4 = "曼陀山莊",
        answer = 3,
    },
    [69] = {
        id = 69,
        question = '在大理境內被自己成名絕技韋陀杵打死的是誰？',
        options1 = "玄難",
        options2 = "玄苦",
        options3 = "玄痛",
        options4 = "玄悲",
        answer = 4,
    },
    [70] = {
        id = 70,
        question = '阿朱從少林寺盜走了什麽武功秘籍？',
        options1 = "易筋經",
        options2 = "大力金剛掌",
        options3 = "般若掌法",
        options4 = "拈花指法",
        answer = 1,
    },
    [71] = {
        id = 71,
        question = '薛神醫是哪個門派的？',
        options1 = "丐幫",
        options2 = "逍遙",
        options3 = "星宿",
        options4 = "武當",
        answer = 2,
    },
    [72] = {
        id = 72,
        question = '喬峰的授業師父是誰？',
        options1 = "玄難",
        options2 = "玄悲",
        options3 = "玄苦",
        options4 = "玄慈",
        answer = 3,
    },
    [73] = {
        id = 73,
        question = '西夏壹品堂在杏子林中用什麽迷倒眾人？',
        options1 = "十香軟筋散",
        options2 = "黑玉斷續膏",
        options3 = "陰陽和合散",
        options4 = "悲酥清風",
        answer = 4,
    },
    [74] = {
        id = 74,
        question = '鎖喉功是丐幫哪位長老的絕技？',
        options1 = "馬大元",
        options2 = "白世鏡",
        options3 = "陳孤雁",
        options4 = "全冠清",
        answer = 1,
    },
    [75] = {
        id = 75,
        question = '在天寧寺中假扮喬峰和慕容復，救出丐幫幫眾的是誰？',
        options1 = "段譽和王語嫣",
        options2 = "阿朱和段譽",
        options3 = "慕容復的阿碧",
        options4 = "虛竹和夢姑",
        answer = 2,
    },
    [76] = {
        id = 76,
        question = '慕容博在藏經閣抄了幾門少林七十二絕技？',
        options1 = "十八",
        options2 = "三十六",
        options3 = "二十八",
        options4 = "二十七",
        answer = 3,
    },
    [77] = {
        id = 77,
        question = '段譽向木婉清借的馬叫什麽？',
        options1 = "白玫瑰",
        options2 = "紫電",
        options3 = "追風",
        options4 = "黑玫瑰",
        answer = 4,
    },
    [78] = {
        id = 78,
        question = '誰破解了珍瓏棋局？',
        options1 = "虛竹",
        options2 = "段譽",
        options3 = "無崖子",
        options4 = "丁春秋",
        answer = 1,
    },
    [79] = {
        id = 79,
        question = '星宿老仙是誰的稱號？',
        options1 = "無崖子",
        options2 = "丁春秋",
        options3 = "蘇星河",
        options4 = "天山童姥",
        answer = 2,
    },
    [80] = {
        id = 80,
        question = '"不會武功也能殺人，會了武功也未必殺人"是誰說的？',
        options1 = "玄慈",
        options2 = "枯榮",
        options3 = "黃眉僧",
        options4 = "鳩摩智",
        answer = 3,
    },
    [81] = {
        id = 81,
        question = '大理段氏的始祖是誰？',
        options1 = "段思平",
        options2 = "段廉義",
        options3 = "段延慶",
        options4 = "段儉魏",
        answer = 4,
    },
    [82] = {
        id = 82,
        question = '段正明皈依佛門，法號是？',
        options1 = "本塵",
        options2 = "本參",
        options3 = "本因",
        options4 = "本觀",
        answer = 1,
    },
    [83] = {
        id = 83,
        question = '段譽在無量山洞獲得的卷帛內共有多少幅圖像？',
        options1 = "24",
        options2 = "36",
        options3 = "48",
        options4 = "64",
        answer = 2,
    },
    [84] = {
        id = 84,
        question = '大理國內最尊崇的寺院是？',
        options1 = "身戒寺",
        options2 = "法華寺",
        options3 = "崇聖寺",
        options4 = "拈花寺",
        answer = 3,
    },
    [85] = {
        id = 85,
        question = '第壹個告知喬峰姓蕭的是誰？',
        options1 = "徐長老",
        options2 = "玄苦",
        options3 = "趙錢孫",
        options4 = "智光大師",
        answer = 4,
    },
    [86] = {
        id = 86,
        question = '夜探少林寺時，誰使出壹拍兩散掌法奔襲喬峰',
        options1 = "玄寂",
        options2 = "玄難",
        options3 = "玄渡",
        options4 = "玄痛",
        answer = 1,
    },
    [87] = {
        id = 87,
        question = '夜探少林寺時，誰在少林長老與喬峰的對掌中受傷？',
        options1 = "喬峰",
        options2 = "阿朱",
        options3 = "玄寂",
        options4 = "玄慈",
        answer = 2,
    },
    [88] = {
        id = 88,
        question = '冰窖中，虛竹身上給童姥種了幾張有效的生死符？',
        options1 = "6",
        options2 = "3",
        options3 = "9",
        options4 = "12",
        answer = 3,
    },
    [89] = {
        id = 89,
        question = '慕容復在誰的眼中像是壹只鳳凰？',
        options1 = "王語嫣",
        options2 = "阿碧",
        options3 = "王夫人",
        options4 = "阿朱",
        answer = 4,
    },
    [90] = {
        id = 90,
        question = '阿紫讓冰蠶吸遊坦之的血是在什麽季節？',
        options1 = "春",
        options2 = "夏",
        options3 = "秋",
        options4 = "冬",
        answer = 1,
    },
    [91] = {
        id = 91,
        question = '段譽在無量山洞，磕了多少頭使蒲團破裂漏出內層物品？',
        options1 = "壹千",
        options2 = "八百余個",
        options3 = "兩千",
        options4 = "五百余個",
        answer = 2,
    },
    [92] = {
        id = 92,
        question = '制作珍瓏棋局用了無崖子多少時間？',
        options1 = "五年",
        options2 = "八年",
        options3 = "三年",
        options4 = "十年",
        answer = 3,
    },
    [93] = {
        id = 93,
        question = '函谷八友每多少年聚會壹次？',
        options1 = "三年",
        options2 = "五年",
        options3 = "八年",
        options4 = "兩年",
        answer = 4,
    },
    [94] = {
        id = 94,
        question = '掃地僧指出蕭遠山第壹次偷研什麽典籍？',
        options1 = "無相劫指譜",
        options2 = "拈花指法",
        options3 = "六脈神劍",
        options4 = "伏魔杖法",
        answer = 1,
    },
    [95] = {
        id = 95,
        question = '智光大師住在何處？',
        options1 = "五臺山",
        options2 = "天臺山",
        options3 = "武夷山",
        options4 = "天柱山",
        answer = 2,
    },
    [96] = {
        id = 96,
        question = '誰的口音可以輕易變化，使人難以辨別？',
        options1 = "段譽",
        options2 = "虛竹",
        options3 = "慕容復",
        options4 = "喬峰",
        answer = 3,
    },
    [97] = {
        id = 97,
        question = '少林派最精奧的掌法是什麽？',
        options1 = "雪山掌",
        options2 = "達摩掌",
        options3 = "如來千手掌",
        options4 = "般若掌",
        answer = 4,
    },
    [98] = {
        id = 98,
        question = '蕭遠山當年在遼國擔任什麽職務？',
        options1 = "珊軍總教頭",
        options2 = "禁軍總教頭",
        options3 = "海軍總教頭",
        options4 = "遼軍總教頭",
        answer = 1,
    },
    [99] = {
        id = 99,
        question = '遊坦之的鐵頭花了多少兩銀子做的？',
        options1 = "五十",
        options2 = "三十",
        options3 = "二十",
        options4 = "壹百",
        answer = 2,
    },
    [100] = {
        id = 100,
        question = '珍瓏棋局上，在鳩摩智之後出場的人物是誰？',
        options1 = "玄難",
        options2 = "段延慶",
        options3 = "慕容復",
        options4 = "虛竹",
        answer = 3,
    },
    [101] = {
        id = 101,
        question = '喬峰在橋邊看到壹個黑衣漢子和農夫在吵架，漢子是誰?',
        options1 = "鄧百川",
        options2 = "包不同",
        options3 = "公冶乾",
        options4 = "風波惡",
        answer = 4,
    },
    [102] = {
        id = 102,
        question = '虛竹最先以為是誰在暗中指點他下棋?',
        options1 = "玄難",
        options2 = "段延慶",
        options3 = "蘇星河",
        options4 = "無崖子",
        answer = 1,
    },
    [103] = {
        id = 103,
        question = '段譽第壹次殺人是什麽情形？',
        options1 = "誤殺瑞婆婆手下",
        options2 = "在山崖擲石",
        options3 = "擊斃努爾海",
        options4 = "擊斃西夏武士",
        answer = 2,
    },
    [104] = {
        id = 104,
        question = '木婉清給司空玄的解藥是什麽？',
        options1 = "金瘡藥",
        options2 = "七厘散",
        options3 = "香粉",
        options4 = "五毒散",
        answer = 3,
    },
    [105] = {
        id = 105,
        question = '左臉頰上有幾粒白色麻子的是誰？',
        options1 = "譚婆",
        options2 = "嚴媽媽",
        options3 = "辛雙清",
        options4 = "葛光佩",
        answer = 4,
    },
    [106] = {
        id = 106,
        question = '誰與天山童姥苦苦相鬥，最終同歸於盡？',
        options1 = "李秋水",
        options2 = "丁春秋",
        options3 = "無崖子",
        options4 = "小師妹",
        answer = 1,
    },
    [107] = {
        id = 107,
        question = '無崖子心裏喜歡的是誰？',
        options1 = "小師妹",
        options2 = "李秋水",
        options3 = "天山童姥",
        options4 = "李青蘿",
        answer = 2,
    },
    [108] = {
        id = 108,
        question = '少室山時，誰沒有參與圍攻契丹人蕭峰？',
        options1 = "慕容復",
        options2 = "丁春秋",
        options3 = "鳩摩智",
        options4 = "遊坦之",
        answer = 3,
    },
    [109] = {
        id = 109,
        question = '《長恨歌》中"忽聞海上有仙山"的下句是',
        options1 = "只有相思無盡處",
        options2 = "悔教夫婿覓封侯",
        options3 = "壹片冰心在玉壺",
        options4 = "山在虛無縹緲間",
        answer = 4,
    },
    [110] = {
        id = 110,
        question = '古詩名句:"清瑟怨遙夜"的下句是？',
        options1 = "繞弦風雨哀",
        options2 = "卷起千堆雪",
        options3 = "蕭蕭班馬鳴",
        options4 = "壹將功成萬骨枯",
        answer = 1,
    },
    [111] = {
        id = 111,
        question = '古詩名句:"去年花裏逢君別"的下句',
        options1 = "只是當時已惘然",
        options2 = "今日花開又壹年。",
        options3 = "對影成三人",
        options4 = "何事秋風悲畫扇",
        answer = 2,
    },
    [112] = {
        id = 112,
        question = '古詩名句"白日放歌須縱酒"的下句是',
        options1 = "天涯共此時",
        options2 = "但聞人語響",
        options3 = "青春做伴好還鄉",
        options4 = "心有靈犀壹點通",
        answer = 3,
    },
    [113] = {
        id = 113,
        question = '宋詞名句"天涯地角有窮時"的下壹句是',
        options1 = "悔教夫婿覓封侯",
        options2 = "壹片冰心在玉壺",
        options3 = "言師采藥去",
        options4 = "只有相思無盡處",
        answer = 4,
    },
    [114] = {
        id = 114,
        question = '蘇軾《赤壁懷古》中"亂石穿空，驚濤拍岸"的下壹句是',
        options1 = "卷起千堆雪",
        options2 = "蕭蕭班馬鳴",
        options3 = "壹將功成萬骨枯",
        options4 = "片片吹落軒轅臺",
        answer = 1,
    },
    [115] = {
        id = 115,
        question = '古詩名句"此情可待成追憶"的下句是',
        options1 = "對影成三人",
        options2 = "只是當時已惘然",
        options3 = "何事秋風悲畫扇",
        options4 = "半江瑟瑟半江紅",
        answer = 2,
    },
    [116] = {
        id = 116,
        question = '古詩名句"海上生明月"的下句是',
        options1 = "但聞人語響",
        options2 = "心有靈犀壹點通",
        options3 = "天涯共此時",
        options4 = "落花時節又逢君",
        answer = 3,
    },
    [117] = {
        id = 117,
        question = '古詩名句"忽見陌頭楊柳色"的下句是',
        options1 = "壹片冰心在玉壺",
        options2 = "言師采藥去",
        options3 = "三千寵愛在壹身",
        options4 = "悔教夫婿覓封侯",
        answer = 4,
    },
    [118] = {
        id = 118,
        question = '古詩名句"揮手自茲去"的下句是',
        options1 = "蕭蕭班馬鳴",
        options2 = "壹將功成萬骨枯",
        options3 = "片片吹落軒轅臺",
        options4 = "天若有情天亦老",
        answer = 1,
    },
    [119] = {
        id = 119,
        question = '古詩名句"舉杯邀明月"的下句是',
        options1 = "何事秋風悲畫扇",
        options2 = "對影成三人",
        options3 = "半江瑟瑟半江紅",
        options4 = "悠然見南山",
        answer = 2,
    },
    [120] = {
        id = 120,
        question = '古詩名句"空山不見人"的下句是',
        options1 = "心有靈犀壹點通",
        options2 = "落花時節又逢君",
        options3 = "但聞人語響",
        options4 = "不知轉入此中來",
        answer = 3,
    },
    [121] = {
        id = 121,
        question = '古詩名句"洛陽親友如相問"的下句是',
        options1 = "言師采藥去",
        options2 = "三千寵愛在壹身",
        options3 = "壹日看盡長安花",
        options4 = "壹片冰心在玉壺",
        answer = 4,
    },
    [122] = {
        id = 122,
        question = '古詩名句"憑君莫話封侯事"的下句是',
        options1 = "壹將功成萬骨枯",
        options2 = "片片吹落軒轅臺",
        options3 = "天若有情天亦老",
        options4 = "孤蓬萬裏征",
        answer = 1,
    },
    [123] = {
        id = 123,
        question = '古詩名句"人生若只如初見"的下句是',
        options1 = "半江瑟瑟半江紅",
        options2 = "何事秋風悲畫扇",
        options3 = "悠然見南山",
        options4 = "長河落日圓",
        answer = 2,
    },
    [124] = {
        id = 124,
        question = '古詩名句"身無彩鳳雙飛翼"的下壹句是',
        options1 = "落花時節又逢君",
        options2 = "不知轉入此中來",
        options3 = "心有靈犀壹點通",
        options4 = "道是無睛還有晴",
        answer = 3,
    },
    [125] = {
        id = 125,
        question = '古詩名句"松下問童子"的下句是',
        options1 = "三千寵愛在壹身",
        options2 = "壹日看盡長安花",
        options3 = "壹片孤城萬仞山",
        options4 = "言師采藥去",
        answer = 4,
    },
    [126] = {
        id = 126,
        question = '古詩名句"燕山雪花大如席"的下句是',
        options1 = "片片吹落軒轅臺",
        options2 = "天若有情天亦老",
        options3 = "孤蓬萬裏征",
        options4 = "白雲千載空悠悠",
        answer = 1,
    },
    [127] = {
        id = 127,
        question = '古詩名句"壹道殘陽鋪水中"的下句是',
        options1 = "悠然見南山",
        options2 = "半江瑟瑟半江紅",
        options3 = "長河落日圓",
        options4 = "誰家新燕啄春泥",
        answer = 2,
    },
    [128] = {
        id = 128,
        question = '古詩名句"正是江南好風景"的下句是',
        options1 = "不知轉入此中來",
        options2 = "道是無睛還有晴",
        options3 = "落花時節又逢君",
        options4 = "暫憑杯酒長精神",
        answer = 3,
    },
    [129] = {
        id = 129,
        question = '《長恨歌》中"後宮佳麗三千人"的下句是',
        options1 = "壹日看盡長安花",
        options2 = "壹片孤城萬仞山",
        options3 = "低頭思故鄉",
        options4 = "三千寵愛在壹身",
        answer = 4,
    },
    [130] = {
        id = 130,
        question = '《金銅仙人辭漢歌》中"衰蘭送客鹹陽道"的下句',
        options1 = "天若有情天亦老",
        options2 = "孤蓬萬裏征",
        options3 = "白雲千載空悠悠",
        options4 = "露似真珠月似弓",
        answer = 1,
    },
    [131] = {
        id = 131,
        question = '古詩名句"采菊東籬下"的下句是',
        options1 = "長河落日圓",
        options2 = "悠然見南山",
        options3 = "誰家新燕啄春泥",
        options4 = "繞床弄青梅",
        answer = 2,
    },
    [132] = {
        id = 132,
        question = '古詩名句"長恨春尋無覓處"的下句是',
        options1 = "道是無睛還有晴",
        options2 = "暫憑杯酒長精神",
        options3 = "不知轉入此中來",
        options4 = "壹行白鷺上青天",
        answer = 3,
    },
    [133] = {
        id = 133,
        question = '古詩名句"春風得意馬蹄疾"的下句是',
        options1 = "壹片孤城萬仞山",
        options2 = "低頭思故鄉",
        options3 = "淺草才能沒馬蹄",
        options4 = "壹日看盡長安花",
        answer = 4,
    },
    [134] = {
        id = 134,
        question = '古詩名句"此地壹為別"的下句是',
        options1 = "孤蓬萬裏征",
        options2 = "白雲千載空悠悠",
        options3 = "露似真珠月似弓",
        options4 = "憑君傳語報平安",
        answer = 1,
    },
    [135] = {
        id = 135,
        question = '古詩名句"大漠孤煙直"的下句是',
        options1 = "誰家新燕啄春泥",
        options2 = "長河落日圓",
        options3 = "繞床弄青梅",
        options4 = "收取關山五十州",
        answer = 2,
    },
    [136] = {
        id = 136,
        question = '古詩名句"東邊日出西邊雨"的下句是',
        options1 = "暫憑杯酒長精神",
        options2 = "壹行白鷺上青天",
        options3 = "道是無睛還有晴",
        options4 = "疑義相與析",
        answer = 3,
    },
    [137] = {
        id = 137,
        question = '古詩名句"黃河遠上白雲間"的下句是',
        options1 = "低頭思故鄉",
        options2 = "淺草才能沒馬蹄",
        options3 = "水村山郭酒旗風",
        options4 = "壹片孤城萬仞山",
        answer = 4,
    },
    [138] = {
        id = 138,
        question = '古詩名句"黃鶴壹去不復返"的下句是',
        options1 = "白雲千載空悠悠",
        options2 = "露似真珠月似弓",
        options3 = "憑君傳語報平安",
        options4 = "萬徑人蹤滅",
        answer = 1,
    },
    [139] = {
        id = 139,
        question = '古詩名句"幾處早鶯爭暖樹"的下句是',
        options1 = "繞床弄青梅",
        options2 = "誰家新燕啄春泥",
        options3 = "收取關山五十州",
        options4 = "莫使金樽空對月",
        answer = 2,
    },
    [140] = {
        id = 140,
        question = '古詩名句"今日聽君歌壹曲"的下句是',
        options1 = "壹行白鷺上青天",
        options2 = "疑義相與析",
        options3 = "暫憑杯酒長精神",
        options4 = "畫樓西畔桂堂東",
        answer = 3,
    },
    [141] = {
        id = 141,
        question = '古詩名句"舉頭望明月"的下句是',
        options1 = "淺草才能沒馬蹄",
        options2 = "水村山郭酒旗風",
        options3 = "我輩豈是蓬蒿人",
        options4 = "低頭思故鄉",
        answer = 4,
    },
    [142] = {
        id = 142,
        question = '古詩名句"可憐九月初三夜"的下句是',
        options1 = "露似真珠月似弓",
        options2 = "憑君傳語報平安",
        options3 = "萬徑人蹤滅",
        options4 = "無人知是荔枝來",
        answer = 1,
    },
    [143] = {
        id = 143,
        question = '古詩名句"郎騎竹馬來"的下句是',
        options1 = "收取關山五十州",
        options2 = "繞床弄青梅",
        options3 = "莫使金樽空對月",
        options4 = "小扣柴扉久不開",
        answer = 2,
    },
    [144] = {
        id = 144,
        question = '古詩名句"兩個黃鸝鳴翠柳"的下句是',
        options1 = "疑義相與析",
        options2 = "畫樓西畔桂堂東",
        options3 = "壹行白鷺上青天",
        options4 = "雪擁藍關馬不前",
        answer = 3,
    },
    [145] = {
        id = 145,
        question = '古詩名句"亂花漸欲迷人眼"的下句是',
        options1 = "水村山郭酒旗風",
        options2 = "我輩豈是蓬蒿人",
        options3 = "別有天地非人間",
        options4 = "淺草才能沒馬蹄",
        answer = 4,
    },
    [146] = {
        id = 146,
        question = '古詩名句"馬上相逢無紙筆"的下句是',
        options1 = "憑君傳語報平安",
        options2 = "萬徑人蹤滅",
        options3 = "無人知是荔枝來",
        options4 = "濃睡不消殘酒",
        answer = 1,
    },
    [147] = {
        id = 147,
        question = '古詩名句"男兒何不帶吳鉤"的下句是',
        options1 = "莫使金樽空對月",
        options2 = "收取關山五十州",
        options3 = "小扣柴扉久不開",
        options4 = "似曾相識燕歸來",
        answer = 2,
    },
    [148] = {
        id = 148,
        question = '古詩名句"奇文共欣賞"的下句是',
        options1 = "畫樓西畔桂堂東",
        options2 = "雪擁藍關馬不前",
        options3 = "疑義相與析",
        options4 = "機關用盡不如君",
        answer = 3,
    },
    [149] = {
        id = 149,
        question = '古詩名句"千裏鶯啼綠映紅"的下句是',
        options1 = "我輩豈是蓬蒿人",
        options2 = "別有天地非人間",
        options3 = "去便不來來便去",
        options4 = "水村山郭酒旗風",
        answer = 4,
    },
    [150] = {
        id = 150,
        question = '古詩名句"千山鳥飛絕"的下句是',
        options1 = "萬徑人蹤滅",
        options2 = "無人知是荔枝來",
        options3 = "濃睡不消殘酒",
        options4 = "落日平原縱馬豪",
        answer = 1,
    },
    [151] = {
        id = 151,
        question = '古詩名句"人生得意須盡歡"的下句是',
        options1 = "小扣柴扉久不開",
        options2 = "莫使金樽空對月",
        options3 = "似曾相識燕歸來",
        options4 = "每逢佳節倍思親",
        answer = 2,
    },
    [152] = {
        id = 152,
        question = '古詩名句"身無彩鳳雙飛翼"的上壹句是',
        options1 = "雪擁藍關馬不前",
        options2 = "機關用盡不如君",
        options3 = "畫樓西畔桂堂東",
        options4 = "山在虛無縹緲間",
        answer = 3,
    },
    [153] = {
        id = 153,
        question = '古詩名句"仰天大笑出門去"的下句是',
        options1 = "別有天地非人間",
        options2 = "去便不來來便去",
        options3 = "繞弦風雨哀",
        options4 = "我輩豈是蓬蒿人",
        answer = 4,
    },
    [154] = {
        id = 154,
        question = '古詩名句"壹騎紅塵妃子笑"的下句是',
        options1 = "無人知是荔枝來",
        options2 = "濃睡不消殘酒",
        options3 = "落日平原縱馬豪",
        options4 = "今日花開又壹年。",
        answer = 1,
    },
    [155] = {
        id = 155,
        question = '古詩名句"應憐屐齒印蒼苔"的下句是',
        options1 = "似曾相識燕歸來",
        options2 = "小扣柴扉久不開",
        options3 = "每逢佳節倍思親",
        options4 = "青春做伴好還鄉",
        answer = 2,
    },
    [156] = {
        id = 156,
        question = '古詩名句"雲橫秦嶺家何在"的下句是',
        options1 = "機關用盡不如君",
        options2 = "山在虛無縹緲間",
        options3 = "雪擁藍關馬不前",
        options4 = "只有相思無盡處",
        answer = 3,
    },
    [157] = {
        id = 157,
        question = '李白《山中答問》詩中"桃花流水苜然去"的下句是',
        options1 = "去便不來來便去",
        options2 = "繞弦風雨哀",
        options3 = "卷起千堆雪",
        options4 = "別有天地非人間",
        answer = 4,
    },
    [158] = {
        id = 158,
        question = '李清照《如夢令》中"昨夜雨疏風驟"的下壹句是',
        options1 = "濃睡不消殘酒",
        options2 = "落日平原縱馬豪",
        options3 = "今日花開又壹年。",
        options4 = "只是當時已惘然",
        answer = 1,
    },
    [159] = {
        id = 159,
        question = '宋詞名句"無可奈何花落去"的下壹句是',
        options1 = "每逢佳節倍思親",
        options2 = "似曾相識燕歸來",
        options3 = "青春做伴好還鄉",
        options4 = "天涯共此時",
        answer = 2,
    },
    [160] = {
        id = 160,
        question = '騎牛遠遠過前村，短笛橫吹隔隴聞。多少長安名利客，（ ）。',
        options1 = "山在虛無縹緲間",
        options2 = "只有相思無盡處",
        options3 = "機關用盡不如君",
        options4 = "悔教夫婿覓封侯",
        answer = 3,
    },
    [161] = {
        id = 161,
        question = '輕無管系狂無數。水畔花飛風裏絮。算伊渾似薄情郎，（ ）。',
        options1 = "繞弦風雨哀",
        options2 = "卷起千堆雪",
        options3 = "蕭蕭班馬鳴",
        options4 = "去便不來來便去",
        answer = 4,
    },
    [162] = {
        id = 162,
        question = '秋風古道題詩瘦的下聯是什麽？',
        options1 = "落日平原縱馬豪",
        options2 = "今日花開又壹年。",
        options3 = "只是當時已惘然",
        options4 = "對影成三人",
        answer = 1,
    },
    [163] = {
        id = 163,
        question = '獨在異鄉為異客，（ ）。遙知兄弟登高處，遍插茱萸少壹人。',
        options1 = "青春做伴好還鄉",
        options2 = "每逢佳節倍思親",
        options3 = "天涯共此時",
        options4 = "但聞人語響",
        answer = 2,
    },
    [164] = {
        id = 164,
        question = '"飛鳥盡，良弓藏，狡兔死，走狗烹"是誰最先說的',
        options1 = "範增",
        options2 = "範偉",
        options3 = "範蠡",
        options4 = "範仲淹",
        answer = 3,
    },
    [165] = {
        id = 165,
        question = '"火把節"在每年農歷的什麽時間舉行？',
        options1 = "五月二十四日",
        options2 = "四月二十四日",
        options3 = "三月二十四日",
        options4 = "六月二十四日",
        answer = 4,
    },
    [166] = {
        id = 166,
        question = '"孟夏"在古代時令中是指農歷幾月',
        options1 = "四月",
        options2 = "五月",
        options3 = "六月",
        options4 = "七月",
        answer = 1,
    },
    [167] = {
        id = 167,
        question = '"算盤"是古代計算用具，中間用檔木分為兩欄，上欄每列兩珠，下欄每列的珠數是',
        options1 = "四珠",
        options2 = "五珠",
        options3 = "六珠",
        options4 = "七珠",
        answer = 2,
    },
    [168] = {
        id = 168,
        question = '"通往帝王陵區的神道上，石頭動物後面的石人又叫做',
        options1 = "石牛",
        options2 = "石山",
        options3 = "石翁仲",
        options4 = "石佛",
        answer = 3,
    },
    [169] = {
        id = 169,
        question = '"銅權"是古代常見的金屬器物，後來被俗稱為',
        options1 = "量尺",
        options2 = "拐杖",
        options3 = "梳子",
        options4 = "秤砣",
        answer = 4,
    },
    [170] = {
        id = 170,
        question = '"玄英"是哪個季節的別稱',
        options1 = "冬季",
        options2 = "春季",
        options3 = "夏季",
        options4 = "秋季",
        answer = 1,
    },
    [171] = {
        id = 171,
        question = '"驛站"在元代稱做什麽？',
        options1 = "崗哨",
        options2 = "站赤",
        options3 = "中轉站",
        options4 = "物流中心",
        answer = 2,
    },
    [172] = {
        id = 172,
        question = '"胄"是古代士兵使用的防護用具，用來保護哪個部位',
        options1 = "肩部",
        options2 = "手部",
        options3 = "頭部",
        options4 = "腰部",
        answer = 3,
    },
    [173] = {
        id = 173,
        question = '《西廂記》脫胎於哪個唐傳奇故事',
        options1 = "昆侖奴",
        options2 = "紅拂傳",
        options3 = "虬髯客",
        options4 = "會真記",
        answer = 4,
    },
    [174] = {
        id = 174,
        question = '被稱為"七絕聖手"的唐代詩人是',
        options1 = "王昌齡",
        options2 = "李白",
        options3 = "杜甫",
        options4 = "李商隱",
        answer = 1,
    },
    [175] = {
        id = 175,
        question = '不屬於中國四大名園的是',
        options1 = "頤和園",
        options2 = "圓明園",
        options3 = "留園",
        options4 = "拙政園",
        answer = 2,
    },
    [176] = {
        id = 176,
        question = '傳說中的"八大山人"有幾個人',
        options1 = "8個人",
        options2 = "4個人",
        options3 = "1個人",
        options4 = "32個人",
        answer = 3,
    },
    [177] = {
        id = 177,
        question = '詞語"芊芊"代表著什麽顏色',
        options1 = "黃色",
        options2 = "黑色",
        options3 = "藍色",
        options4 = "翠綠色",
        answer = 4,
    },
    [178] = {
        id = 178,
        question = '詞語"司空見慣"中的"司空"指的是',
        options1 = "官職",
        options2 = "名字",
        options3 = "車輛",
        options4 = "園林",
        answer = 1,
    },
    [179] = {
        id = 179,
        question = '詞語"同氣"是指什麽關系',
        options1 = "親戚",
        options2 = "兄弟",
        options3 = "父子",
        options4 = "仇人",
        answer = 2,
    },
    [180] = {
        id = 180,
        question = '從我國古代的神話傳說來看，以下與月亮無關的是',
        options1 = "嫦娥",
        options2 = "吳剛",
        options3 = "誇父",
        options4 = "玉兔",
        answer = 3,
    },
    [181] = {
        id = 181,
        question = '宮城的正門被稱為',
        options1 = "玄武門",
        options2 = "玉華門",
        options3 = "朱雀門",
        options4 = "午門",
        answer = 4,
    },
    [182] = {
        id = 182,
        question = '古代成語"愛鶴失眾"的寓意是',
        options1 = "因小失大",
        options2 = "見利忘義",
        options3 = "大公無私",
        options4 = "兩頭為難",
        answer = 1,
    },
    [183] = {
        id = 183,
        question = '古代成語"白龍魚服"的意思是',
        options1 = "形容貧窮",
        options2 = "形容微服出行的危險",
        options3 = "形容吝嗇",
        options4 = "形容貪婪",
        answer = 2,
    },
    [184] = {
        id = 184,
        question = '古代成語"白首窮經"的寓意是',
        options1 = "形容貧窮",
        options2 = "形容無知",
        options3 = "活到老學到老",
        options4 = "形容貪婪",
        answer = 3,
    },
    [185] = {
        id = 185,
        question = '古代成語"碧落黃泉"中的"黃泉"是指',
        options1 = "沙漠",
        options2 = "海洋",
        options3 = "深淵",
        options4 = "地府",
        answer = 4,
    },
}
