config.activity = {
    [1001] = {
        id = 1001,
        name = "武林盟主",
        type = 1,
        icon = "act_6",
        tips = {2},
    },
    [1004] = {
        id = 1004,
        name = "武林禁地",
        type = 1,
        icon = "act_1",
        tips = {2},
    },
    [1005] = {
        id = 1005,
        name = "幫會守衛戰",
        type = 1,
        icon = "act_4",
        tips = {2},
    },
    [1006] = {
        id = 1006,
        name = "門派競技",
        type = 1,
        icon = "act_7",
        tips = {2},
    },
    [1007] = {
        id = 1007,
        name = "鏡湖剿匪",
        type = 1,
        icon = "act_5",
        tips = {2},
    },
    [1008] = {
        id = 1008,
        name = "幫會行酒令",
        type = 1,
        icon = "act_8",
        tips = {2},
    },
    [1009] = {
        id = 1009,
        name = "演武堂",
        type = 1,
        icon = "act_10",
        tips = {2},
    },
    [1010] = {
        id = 1010,
        name = "領地戰",
        type = 1,
        icon = "act_0",
        tips = {2},
    },
    [1011] = {
        id = 1011,
        name = "領地戰",
        type = 1,
        icon = "act_0",
        tips = {2},
    },
    [1012] = {
        id = 1012,
        name = "領地戰",
        type = 1,
        icon = "act_0",
        tips = {2},
    },
    [1013] = {
        id = 1013,
        name = "幫會練功",
        type = 1,
        icon = "act_9",
        tips = {2},
    },
    [1014] = {
        id = 1014,
        name = "珍瓏棋局",
        type = 1,
        icon = "act_18",
        tips = {2},
    },
    [1015] = {
        id = 1015,
        name = "幫會運鏢",
        type = 1,
        icon = "act_9",
        tips = {2},
    },
    [1016] = {
        id = 1016,
        name = "江湖歷練",
        type = 1,
        icon = "act_0",
        tips = {0},
    },
    [2016] = {
        id = 2016,
        name = "開服紅利",
        type = 2,
        icon = "",
        tips = {0},
    },
    [6001] = {
        id = 6001,
        name = "宋遼戰爭",
        type = 6,
        icon = "act_3",
        tips = {1,2},
    },
    [6002] = {
        id = 6002,
        name = "秦皇陵",
        type = 6,
        icon = "",
        tips = {},
    },
    [6003] = {
        id = 6003,
        name = "巔峰秦皇陵",
        type = 6,
        icon = "",
        tips = {},
    },
}