
config.new_step = {
	[10011] = {
		[1] = {
			id = 10011,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=1001,on_view={"ui_main/new_main_view"},finish_jump_event = true},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/task_com/touch_com"},
			delay = 0,
			click_rect = {x=350,y=961,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=14,y=681,flip=0,npc_img = 1,txt="點擊此處<font color ='#ffff00'>追蹤</font>任務目標"},{x=373,y=881,rotation=90}},
			sound = "snd2001",
			frame_cfg = {lt_pos = {161, 907}, height = 85, width = 387},
			circle_effect = {},
		},
	},
	[10021] = {
		[1] = {
			id = 10021,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=1001,on_view={"ui_task/task_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/task_dialog_view/btn_finish"},
			delay = 0,
			click_rect = {x=361,y=1253,rotation=-90,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {3, 961}, height = 312, width = 713},
			circle_effect = {},
		},
	},
	[100021] = {
		[1] = {
			id = 100021,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_id=1002,on_view={"ui_task/task_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/task_dialog_view/btn_finish"},
			delay = 0,
			click_rect = {x=361,y=1253,rotation=-90,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {3, 961}, height = 312, width = 713},
			circle_effect = {},
		},
	},
	[100031] = {
		[1] = {
			id = 100031,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=1002,on_view={"ui_task/task_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/task_dialog_view/btn_finish"},
			delay = 0,
			click_rect = {x=361,y=1253,rotation=-90,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {3, 961}, height = 312, width = 713},
			circle_effect = {},
		},
	},
	[100044] = {
		[1] = {
			id = 100044,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {open_func_id = 1129,on_view={"ui_main/new_main_view"}},
			next_cond = {on_view={"ui_equip_tips/godweapon_collect_view"}},
			delay = 0,
			click_rect = {},
			do_times = 1,
			open_view = {"OpenGodWeaponView", 1},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[100041] = {
		[1] = {
			id = 100041,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=100044,on_view={"ui_equip_tips/godweapon_collect_view"}},
			next_cond = {click_btn_name = "ui_equip_tips/godweapon_collect_view/award_item1"},
			delay = 0,
			click_rect = {x=87,y=1198,rotation=0,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=186,y=906,flip=1,npc_img = 1,txt="點擊獎勵圖標<font color ='#ffff00'>領取</font>碎片，獲得獎勵"},{x=194,y=1107,rotation=135}},
			sound = "snd2002",
			frame_cfg = {lt_pos = {32, 1142}, height = 108, width = 108},
			circle_effect = {},
		},
	},
	[100042] = {
		[1] = {
			id = 100042,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=100041,on_view={"ui_equip_tips/godweapon_collect_view"}},
			next_cond = {click_btn_name = "ui_equip_tips/godweapon_collect_view/n10"},
			delay = 0,
			click_rect = {x=658,y=1050,rotation=0,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=206,y=760,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>預覽</font>神器"},{x=675,y=964,rotation=90}},
			sound = "snd2003",
			frame_cfg = {lt_pos = {619, 1020}, height = 83, width = 83},
			circle_effect = {},
		},
	},
	[100043] = {
		[1] = {
			id = 100043,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=100042,on_view={"ui_foundry/foundry_godweapon_preview"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_godweapon_preview/btn_close"},
			delay = 3.5,
			click_rect = {x=678,y=43,rotation=90,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=219,y=45,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>關閉</font>界面"},{x=649,y=169,rotation=-90}},
			sound = "snd2004",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10031] = {
		[1] = {
			id = 10031,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=1005, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/pet_head_component/btn_pet"},
			delay = 0,
			click_rect = {x=35,y=143,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=0,y=135,flip=1,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>珍獸界面"}},
			sound = "snd2005",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10032] = {
		[1] = {
			id = 10032,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=10031,on_view={"ui_pet/pet_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_view/btn_battle"},
			delay = 0,
			click_rect = {x=358,y=930,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=20,y=878,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>出戰</font>珍獸"},{x=347,y=1002,rotation=-90}},
			sound = "snd2006",
			frame_cfg = {lt_pos = {287, 893}, height = 56, width = 146},
			circle_effect = {},
		},
	},
	[10033] = {
		[1] = {
			id = 10033,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=10032,on_view={"ui_pet/pet_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_view/close_btn"},
			delay = 0,
			click_rect = {x=670,y=71,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=81,y=37,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>關閉</font>界面"},{x=556,y=128,rotation=-45}},
			sound = "snd2004",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10041] = {
		[1] = {
			id = 10041,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=1003, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_skill"},
			delay = 0,
			click_rect = {x=303,y=1044,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=230,y=755,flip=1,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>技能界面"},{x=320,y=951,rotation=90}},
			sound = "snd2007",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10042] = {
		[1] = {
			id = 10042,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=10041,on_view={"ui_skill/skill_view"}},
			next_cond = {click_btn_name = "ui_skill/skill_view/skill_template/skill_upgrade_item/btn_upgrade"},
			delay = 0,
			click_rect = {x=504,y=1221,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=48,y=929,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>升級</font>技能"},{x=529,y=1129,rotation=90}},
			sound = "snd2008",
			frame_cfg = {lt_pos = {406, 1187}, height = 72, width = 202},
			circle_effect = {},
		},
	},
	[10043] = {
		[1] = {
			id = 10043,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=10042,on_view={"ui_skill/skill_view"}},
			next_cond = {click_btn_name = "ui_skill/skill_view/close_btn"},
			delay = 0,
			click_rect = {x=670,y=71,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=81,y=37,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>關閉</font>界面"},{x=556,y=128,rotation=-45}},
			sound = "snd2004",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10051] = {
		[1] = {
			id = 10051,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=1021, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_foundry"},
			delay = 0,
			click_rect = {x=411,y=1044,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=0,y=747,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>強化界面"},{x=428,y=948,rotation=90}},
			sound = "snd2009",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10052] = {
		[1] = {
			id = 10052,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=10051,on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_stren"},
			delay = 0,
			click_rect = {x=511,y=1222,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=80,y=929,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>強化</font>裝備位"},{x=527,y=1129,rotation=90}},
			sound = "snd2010",
			frame_cfg = {lt_pos = {408, 1187}, height = 72, width = 202},
			circle_effect = {},
		},
	},
	[10053] = {
		[1] = {
			id = 10053,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {pre_id=10052,on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_close"},
			delay = 0,
			click_rect = {x=670,y=71,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=81,y=37,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>關閉</font>界面"},{x=556,y=128,rotation=-45}},
			sound = "snd2004",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[100011] = {
		[1] = {
			id = 100011,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=10005,on_view={"ui_task/task_view",1}},
			next_cond = {click_btn_name = "ui_task/task_view/group_bg/task/btn"},
			delay = 0,
			click_rect = {x=631,y=454,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=33,y=193,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>追蹤</font>任務"},{x=530,y=373,rotation=45}},
			sound = "snd2001",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[100061] = {
		[1] = {
			id = 100061,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {lv_task=1038,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/task_com/btn_task"},
			delay = 0,
			click_rect = {x=205,y=939,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=10,y=662,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>任務</font>查看"},{x=223,y=857,rotation=90}},
			sound = "snd2011",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[100062] = {
		[1] = {
			id = 100062,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {lv_task=1038,less_lv=19,on_view={"ui_task/task_view"}},
			next_cond = {click_btn_name = "ui_task/task_view/task_template/task_item/btn_go"},
			delay = 0,
			click_rect = {x=632,y=450,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10061] = {
		[1] = {
			id = 10061,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20104,cur_click_task_id=20104, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_hero"},
			delay = 0,
			click_rect = {x=189,y=1125,guangbao=1},
			do_times = 999,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=0,y=837,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>英雄譜界面"},{x=213,y=1038,rotation=90}},
			sound = "snd2012",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10061,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_hero/hero_view"}},
			next_cond = {click_btn_name = "ui_hero/hero_view/book_template/btn_checkbox"},
			delay = 0,
			click_rect = {x=517,y=1224,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=72,y=935,flip=0,npc_img = 1,txt="點擊查看<font color ='#ffff00'>已結交</font>英雄"},{x=534,y=1137,rotation=90}},
			sound = "snd2013",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10061,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_hero/hero_view"}},
			next_cond = {click_btn_name = "ui_hero/hero_view/book_template/hero_item/group"},
			delay = 0,
			click_rect = {x=202,y=440,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=211,y=414,flip=1,npc_img = 1,txt="點擊<font color ='#ffff00'>已結交</font>英雄培養"}},
			sound = "snd2014",
			frame_cfg = {},
			circle_effect = {},
		},
		[4] = {
			id = 10061,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_hero/hero_info_view"}},
			next_cond = {click_btn_name = "ui_hero/hero_info_view/btn_upgrade"},
			delay = 0,
			click_rect = {x=238,y=1243,rotation=150,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=203,y=962,flip=1,npc_img = 1,txt="點擊<font color ='#ffff00'>使用</font>培養道具"},{x=266,y=1157,rotation=90}},
			sound = "",
			frame_cfg = {lt_pos = {146, 1218}, height = 52, width = 181},
			circle_effect = {},
		},
	},
	[10071] = {
		[1] = {
			id = 10071,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20106,on_view={"ui_task/npc_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/npc_dialog_view/func_btn"},
			delay = 0,
			click_rect = {x=157,y=1107,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10071,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_carbon/hero_trial_view"}},
			next_cond = {click_btn_name = "ui_carbon/hero_trial_view/btn_start"},
			delay = 0,
			click_rect = {x=504,y=1222,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=67,y=922,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>挑戰</font>進入英雄試煉"},{x=524,y=1130,rotation=90}},
			sound = "snd2016",
			frame_cfg = {lt_pos = {405, 1186}, height = 76, width = 206},
			circle_effect = {},
		},
	},
	[10091] = {
		[1] = {
			id = 10091,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20107,on_view={"ui_task/npc_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/npc_dialog_view/func_btn"},
			delay = 0,
			click_rect = {x=157,y=1107,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10091,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_carbon/hero_trial_view"}},
			next_cond = {click_btn_name = "ui_carbon/hero_trial_view/hero_component/reward"},
			delay = 0,
			click_rect = {x=228,y=283,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=214,y=255,flip=1,npc_img = 1,txt="點擊<font color ='#ffff00'>領取</font>已通關章節獎勵"}},
			sound = "snd2017",
			frame_cfg = {lt_pos = {197, 246}, height = 64, width = 64},
			circle_effect = {},
		},
		[3] = {
			id = 10091,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_carbon/chapter_reward_view"}},
			next_cond = {click_btn_name = "ui_carbon/chapter_reward_view/btn_get"},
			delay = 0,
			click_rect = {x=358,y=634,rotation=-90,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=8,y=613,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>領取</font>獎勵"},{x=342,y=729,rotation=-90}},
			sound = "snd2018",
			frame_cfg = {lt_pos = {254, 597}, height = 76, width = 206},
			circle_effect = {},
		},
	},
	[10101] = {
		[1] = {
			id = 10101,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20203,cur_click_task_id=20203,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_foundry"},
			delay = 0,
			click_rect = {x=411,y=1044,guangbao=1},
			do_times = 999,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=0,y=747,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>寶石功能入口"},{x=428,y=948,rotation=90}},
			sound = "snd2019",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10101,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_stone"},
			delay = 0,
			click_rect = {x=271,y=146,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=206,y=132,flip=1,npc_img = 1,txt="點擊切換<font color ='#ffff00'>寶石</font>標簽"}},
			sound = "snd2020",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10101,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/stone_template/bot_btn2"},
			delay = 0,
			click_rect = {x=256,y=1133,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=220,y=830,flip=1,npc_img = 1,txt="點擊選擇<font color ='#ffff00'>上衣</font>"},{x=273,y=1027,rotation=90}},
			sound = "snd2021",
			frame_cfg = {lt_pos = {182, 1070}, height = 170, width = 143},
			circle_effect = {},
		},
		[4] = {
			id = 10101,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/stone_template/mid_btn1"},
			delay = 0,
			click_rect = {x=357,y=396,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {310, 336}, height = 107, width = 107},
			circle_effect = {},
		},
		[5] = {
			id = 10101,
			step = 5,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/stone_template/inlay_btn"},
			delay = 0,
			click_rect = {x=363,y=330,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {299, 306}, height = 50, width = 134},
			circle_effect = {},
		},
		[6] = {
			id = 10101,
			step = 6,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_stone_inlay_view"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_stone_inlay_view/stone_right_template1"},
			delay = 0,
			click_rect = {x=358,y=380,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[7] = {
			id = 10101,
			step = 7,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_stone_inlay_view"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_stone_inlay_view/stone_right_template2"},
			delay = 0,
			click_rect = {x=179,y=472,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[8] = {
			id = 10101,
			step = 8,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_stone_inlay_view"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_stone_inlay_view/close_btn"},
			delay = 0,
			click_rect = {x=668,y=67,rotation=90,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[9] = {
			id = 10101,
			step = 9,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_close"},
			delay = 0,
			click_rect = {x=670,y=71,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=81,y=37,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>關閉</font>界面"},{x=556,y=128,rotation=-45}},
			sound = "snd2004",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10111] = {
		[1] = {
			id = 10111,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20204,cur_click_task_id=20204,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_foundry"},
			delay = 0,
			click_rect = {x=411,y=1044,guangbao=1},
			do_times = 999,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=0,y=747,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>強化界面"},{x=428,y=948,rotation=90}},
			sound = "snd2009",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10111,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_stone"},
			delay = 0,
			click_rect = {x=271,y=146,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=206,y=132,flip=1,npc_img = 1,txt="點擊選擇<font color ='#ffff00'>寶石</font>標簽"}},
			sound = "snd2020",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10111,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/stone_template/bot_btn2"},
			delay = 0,
			click_rect = {x=256,y=1133,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=220,y=830,flip=1,npc_img = 1,txt="點擊選擇<font color ='#ffff00'>上衣</font>"},{x=273,y=1027,rotation=90}},
			sound = "snd2021",
			frame_cfg = {lt_pos = {182, 1070}, height = 170, width = 143},
			circle_effect = {},
		},
		[4] = {
			id = 10111,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/stone_template/mid_btn1"},
			delay = 0,
			click_rect = {x=357,y=396,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {310, 336}, height = 107, width = 107},
			circle_effect = {},
		},
		[5] = {
			id = 10111,
			step = 5,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/stone_template/upgrade_btn"},
			delay = 0,
			click_rect = {x=358,y=389,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {299, 369}, height = 50, width = 134},
			circle_effect = {},
		},
		[6] = {
			id = 10111,
			step = 6,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/stone_advance_view"}},
			next_cond = {click_btn_name = "ui_foundry/stone_advance_view/n34"},
			delay = 0,
			click_rect = {x=367,y=1104,rotation=0,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {259, 1057}, height = 76, width = 206},
			circle_effect = {},
		},
		[7] = {
			id = 10111,
			step = 7,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",2}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_close"},
			delay = 0,
			click_rect = {x=670,y=71,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=81,y=37,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>關閉</font>界面"},{x=556,y=128,rotation=-45}},
			sound = "snd2004",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10121] = {
		[1] = {
			id = 10121,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20904,cur_click_task_id=20904, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/pet_head_component/btn_pet"},
			delay = 0,
			click_rect = {x=35,y=143,guangbao=1},
			do_times = 999,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=0,y=135,flip=1,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>珍獸界面"}},
			sound = "snd2005",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10121,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_view/btn_train"},
			delay = 0,
			click_rect = {x=214,y=1211,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10121,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_train_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_train_view/list/pet_icon_item2"},
			delay = 0,
			click_rect = {x=236,y=1057,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {192, 1016}, height = 80, width = 80},
			circle_effect = {},
		},
		[4] = {
			id = 10121,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_train_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_train_view/train_attr_template/btn_wash"},
			delay = 0,
			click_rect = {x=507,y=1221,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {404, 1183}, height = 73, width = 207},
			circle_effect = {},
		},
		[5] = {
			id = 10121,
			step = 5,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_train_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_train_view/btn_close"},
			delay = 0,
			click_rect = {x=670,y=69,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10131] = {
		[1] = {
			id = 10131,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20906,on_view={"ui_task/npc_dialog_view"}},
			next_cond = {click_btn_name = "ui_task/npc_dialog_view/func_btn"},
			delay = 0,
			click_rect = {x=131,y=1091,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10131,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_breed_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_breed_view/list/pet_item1"},
			delay = 1,
			click_rect = {x=123,y=810,guangbao=1},
			do_times = 999,
			open_view = {"PetBreedView"},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10131,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_breed_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_breed_view/list/pet_item2"},
			delay = 0,
			click_rect = {x=317,y=810,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[4] = {
			id = 10131,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_pet/pet_breed_view"}},
			next_cond = {click_btn_name = "ui_pet/pet_breed_view/btn_breed"},
			delay = 0,
			click_rect = {x=363,y=1067,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10141] = {
		[1] = {
			id = 10141,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20804,cur_click_task_id=20804, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_role"},
			delay = 0,
			click_rect = {x=197,y=1043,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10141,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_role/role_new_view"}},
			next_cond = {click_btn_name = "ui_role/role_new_view/role_base_com/btn_up"},
			delay = 0,
			click_rect = {x=530,y=1187,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10141,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_role/honor_view"}},
			next_cond = {click_btn_name = "ui_role/honor_view/btn_upgrade"},
			delay = 0,
			click_rect = {x=531,y=849,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10161] = {
		[1] = {
			id = 10161,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20403,cur_click_task_id=20403, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_foundry"},
			delay = 0,
			click_rect = {x=411,y=1044,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=0,y=747,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>打開</font>鍛造界面"},{x=428,y=948,rotation=90}},
			sound = "snd2024",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10161,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_smelt"},
			delay = 0,
			click_rect = {x=449,y=146,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=206,y=132,flip=1,npc_img = 1,txt="點擊選擇<font color ='#ffff00'>熔煉</font>標簽"}},
			sound = "snd2025",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10161,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",3}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/smelt_template/btn_smelt"},
			delay = 0,
			click_rect = {x=363,y=1217,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[4] = {
			id = 10161,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_smelt_select_view"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_smelt_select_view/n14"},
			delay = 0,
			click_rect = {x=496,y=878,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[5] = {
			id = 10161,
			step = 5,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_smelt_select_view"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_smelt_select_view/n13"},
			delay = 0,
			click_rect = {x=212,y=878,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[6] = {
			id = 10161,
			step = 6,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_smelt_select_view"}},
			next_cond = {click_btn_name = "ui_foundry/foundry_smelt_select_view/btn_close"},
			delay = 0,
			click_rect = {x=676,y=189,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[7] = {
			id = 10161,
			step = 7,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_foundry/foundry_view2",3}},
			next_cond = {click_btn_name = "ui_foundry/foundry_view2/btn_close"},
			delay = 0,
			click_rect = {x=665,y=68,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10171] = {
		[1] = {
			id = 10171,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20501, on_view={"ui_guild/guild_lobby_view"}},
			next_cond = {click_btn_name = "ui_guild/guild_lobby_view/btn_apply"},
			delay = 0,
			click_rect = {x=209,y=1221,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10181] = {
		[1] = {
			id = 10181,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20503,cur_click_task_id=20503, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_guild"},
			delay = 0,
			click_rect = {x=197,y=1127,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=3,y=832,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>幫會</font>界面"},{x=210,y=1037,rotation=90}},
			sound = "snd2026",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10181,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_new_view"}},
			next_cond = {click_btn_name = "ui_guild/guild_new_view/btn_welfare"},
			delay = 0,
			click_rect = {x=496,y=140,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=169,y=183,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>福利</font>標簽"}},
			sound = "snd2027",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10181,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_new_view",4}},
			next_cond = {click_btn_name = "ui_guild/guild_new_view/guild_welfare_template/btn_open2"},
			delay = 0,
			click_rect = {x=629,y=399,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[4] = {
			id = 10181,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_shop/shop_view"}},
			next_cond = {click_btn_name = "ui_shop/shop_view/shop_item/btn_buy"},
			delay = 0,
			click_rect = {x=301,y=324,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=14,y=371,flip=0,npc_img = 1,txt="點擊<font color ='#ffff00'>購買</font>地煞強化精華"}},
			sound = "snd2028",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10191] = {
		[1] = {
			id = 10191,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20506,cur_click_task_id=20506, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_guild"},
			delay = 0.5,
			click_rect = {x=197,y=1127,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=3,y=832,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>幫會</font>界面"},{x=210,y=1037,rotation=90}},
			sound = "snd2026",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10191,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_new_view"}},
			next_cond = {click_btn_name = "ui_guild/guild_new_view/btn_welfare"},
			delay = 0,
			click_rect = {x=496,y=140,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=169,y=183,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>福利</font>標簽"}},
			sound = "snd2027",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10191,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_new_view",4}},
			next_cond = {click_btn_name = "ui_guild/guild_new_view/guild_welfare_template/btn_open6"},
			delay = 0,
			click_rect = {x=629,y=922,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[4] = {
			id = 10191,
			step = 4,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_wage_view"}},
			next_cond = {click_btn_name = "ui_guild/guild_wage_view/btn_close"},
			delay = 0,
			click_rect = {x=650,y=256,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[5] = {
			id = 10191,
			step = 5,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_new_view",4}},
			next_cond = {click_btn_name = "ui_guild/guild_new_view/btn_close"},
			delay = 0,
			click_rect = {x=666,y=68,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10201] = {
		[1] = {
			id = 10201,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20504,cur_click_task_id=20504, on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/btn_guild"},
			delay = 0.5,
			click_rect = {x=197,y=1127,guangbao=1},
			do_times = 1,
			open_view = {"MainUICtrl", 1},
			npc_jt = {{x=3,y=832,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>幫會</font>界面"},{x=210,y=1037,rotation=90}},
			sound = "snd2026",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10201,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_guild/guild_new_view"}},
			next_cond = {click_btn_name = "ui_guild/guild_new_view/guild_info_template/btn_back"},
			delay = 0,
			click_rect = {x=204,y=1222,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10211] = {
		[1] = {
			id = 10211,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20301,cur_click_task_id=20301,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10211,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1012},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10221] = {
		[1] = {
			id = 10221,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20701,cur_click_task_id=20701,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10221,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1006},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10231] = {
		[1] = {
			id = 10231,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20702,cur_click_task_id=20702,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10231,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1011},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10241] = {
		[1] = {
			id = 10241,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20908,cur_click_task_id=20908,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10241,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1007},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10251] = {
		[1] = {
			id = 10251,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20910,cur_click_task_id=20910,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10251,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1008},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10261] = {
		[1] = {
			id = 10261,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20915,cur_click_task_id=20915,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10261,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1009},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10261,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_lake_exp/lake_exp_view"}},
			next_cond = {click_btn_name = "ui_lake_exp/lake_exp_view/list_page/item2"},
			delay = 1,
			click_rect = {x=355,y=652,guangbao=1},
			do_times = 999,
			open_view = {"LakeExpView", 1},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {3, 502}, height = 280, width = 714},
			circle_effect = {},
		},
	},
	[10271] = {
		[1] = {
			id = 10271,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20918,cur_click_task_id=20918,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10271,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1001},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10281] = {
		[1] = {
			id = 10281,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=10004,on_view={"ui_main/new_main_view"},cur_scene_id=10000},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/task_com/touch_com"},
			delay = 0,
			click_rect = {x=350,y=961,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=14,y=681,flip=0,npc_img = 1,txt="點擊此處<font color ='#ffff00'>追蹤</font>任務目標"},{x=373,y=881,rotation=90}},
			sound = "snd2001",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10291] = {
		[1] = {
			id = 10291,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_end=1029,on_view={"ui_main/new_main_view"},cur_scene_id=10000},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_bottom/task_com/touch_com"},
			delay = 0,
			click_rect = {x=350,y=961,guangbao=1},
			do_times = 1,
			open_view = {},
			npc_jt = {{x=14,y=681,flip=0,npc_img = 1,txt="點擊此處<font color ='#ffff00'>追蹤</font>任務目標"},{x=373,y=881,rotation=90}},
			sound = "snd2001",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10301] = {
		[1] = {
			id = 10301,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=20509,cur_click_task_id=20509,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10301,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1014},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10311] = {
		[1] = {
			id = 10311,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=21003,cur_click_task_id=21003,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10311,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1002},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
	},
	[10321] = {
		[1] = {
			id = 10321,
			step = 1,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {task_ing=22202,cur_click_task_id=22202,on_view={"ui_main/new_main_view"}},
			next_cond = {click_btn_name = "ui_main/new_main_view/mid_top/func_group_3/btn_func_1"},
			delay = 0,
			click_rect = {x=591,y=144,guangbao=1},
			do_times = 999,
			open_view = {},
			npc_jt = {{x=38,y=90,flip=0,npc_img = 1,txt="點擊打開<font color ='#ffff00'>活動大廳</font>界面"},{x=514,y=195,rotation=-45}},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[2] = {
			id = 10321,
			step = 2,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_activity/activity_hall_view",1}},
			next_cond = {click_btn_name = "ui_activity/activity_hall_view/activity_daily_template/btn"},
			delay = 0,
			click_rect = {},
			do_times = 999,
			open_view = {"OpenActivityHallView",1,1009},
			npc_jt = {},
			sound = "",
			frame_cfg = {},
			circle_effect = {},
		},
		[3] = {
			id = 10321,
			step = 3,
			key_step = 1,
			open_event = "focus_on_view",
			active_cond = {on_view={"ui_lake_exp/lake_exp_view"}},
			next_cond = {click_btn_name = "ui_lake_exp/lake_exp_view/list_page/item3"},
			delay = 1,
			click_rect = {x=355,y=954,guangbao=1},
			do_times = 999,
			open_view = {"LakeExpView", 2},
			npc_jt = {},
			sound = "",
			frame_cfg = {lt_pos = {3, 808}, height = 280, width = 714},
			circle_effect = {},
		},
	},
}