config.pet_skill_upgrade = {
    [1] = {
    	level = 1,
	    cost_num = 2,
	    upgrade_rate = 10000,
	    stone_rate = 0,
	    stone_rate_auto = 0,
	    carry_lv = 0,
	},
    [2] = {
    	level = 2,
	    cost_num = 5,
	    upgrade_rate = 10000,
	    stone_rate = 0,
	    stone_rate_auto = 0,
	    carry_lv = 0,
	},
    [3] = {
    	level = 3,
	    cost_num = 10,
	    upgrade_rate = 10000,
	    stone_rate = 0,
	    stone_rate_auto = 0,
	    carry_lv = 0,
	},
    [4] = {
    	level = 4,
	    cost_num = 15,
	    upgrade_rate = 10000,
	    stone_rate = 0,
	    stone_rate_auto = 0,
	    carry_lv = 0,
	},
    [5] = {
    	level = 5,
	    cost_num = 0,
	    upgrade_rate = 0,
	    stone_rate = 500,
	    stone_rate_auto = 800,
	    carry_lv = 85,
	},
    [6] = {
    	level = 6,
	    cost_num = 0,
	    upgrade_rate = 0,
	    stone_rate = 400,
	    stone_rate_auto = 600,
	    carry_lv = 95,
	},
    [7] = {
    	level = 7,
	    cost_num = 0,
	    upgrade_rate = 0,
	    stone_rate = 0,
	    stone_rate_auto = 0,
	    carry_lv = 0,
	},
}