config.daily_event_task = {
    [1] = {
        id = 1,
        desc = "裝備熔煉",
        max_n = 20,
        exp = 1,
        cost = 1,
        open_limit = {{1,1}},
    },
    [2] = {
        id = 2,
        desc = "珍瓏棋局",
        max_n = 10,
        exp = 2,
        cost = 2,
        open_limit = {{1,10}},
    },
    [3] = {
        id = 3,
        desc = "神獸來襲",
        max_n = 10,
        exp = 2,
        cost = 2,
        open_limit = {{1,20}},
    },
    [4] = {
        id = 4,
        desc = "奪寶奇兵",
        max_n = 10,
        exp = 2,
        cost = 2,
        open_limit = {{1,30}},
    },
    [5] = {
        id = 5,
        desc = "競技場",
        max_n = 5,
        exp = 5,
        cost = 5,
        open_limit = {{1,10}},
    },
    [6] = {
        id = 6,
        desc = "材料副本",
        max_n = 18,
        exp = 1,
        cost = 1,
        open_limit = {{1,10}},
    },
}