config.mentor_task = {
    [41] = {
        [1001] = {
            id = 1001,
            type = 41,
            desc = "等級到達30級",
            cond = {1,30,{}},
            mark = 5,
            require = 0,
        },
        [1002] = {
            id = 1002,
            type = 41,
            desc = "等級到達40級",
            cond = {1,40,{}},
            mark = 5,
            require = 0,
        },
        [1003] = {
            id = 1003,
            type = 41,
            desc = "等級到達50級",
            cond = {1,50,{}},
            mark = 10,
            require = 0,
        },
        [1004] = {
            id = 1004,
            type = 41,
            desc = "繁殖珍獸1次",
            cond = {35,1,{}},
            mark = 10,
            require = 0,
        },
        [1005] = {
            id = 1005,
            type = 41,
            desc = "通關英雄試煉“青衫磊落”章節",
            cond = {11,1,{550,30}},
            mark = 10,
            require = 0,
        },
        [1006] = {
            id = 1006,
            type = 41,
            desc = "打造壹件裝備",
            cond = {65,1,{1}},
            mark = 5,
            require = 0,
        },
        [1007] = {
            id = 1007,
            type = 41,
            desc = "加入壹個結拜",
            cond = {90,1,{}},
            mark = 5,
            require = 0,
        },
        [1008] = {
            id = 1008,
            type = 41,
            desc = "師徒組隊殺死1500只怪",
            cond = {91,1500,{}},
            mark = 10,
            require = 0,
        },
        [1009] = {
            id = 1009,
            type = 41,
            desc = "師徒組隊參加30次奪寶馬賊",
            cond = {92,30,{}},
            mark = 10,
            require = 0,
        },
        [1010] = {
            id = 1010,
            type = 41,
            desc = "師徒組隊完成2次珍瓏棋局",
            cond = {93,2,{1200}},
            mark = 10,
            require = 0,
        },
        [1011] = {
            id = 1011,
            type = 41,
            desc = "師徒組隊完成2次老三環",
            cond = {93,2,{700}},
            mark = 10,
            require = 0,
        },
        [1012] = {
            id = 1012,
            type = 41,
            desc = "師徒組隊完成2次燕子塢",
            cond = {93,2,{800}},
            mark = 10,
            require = 0,
        },
    },
    [42] = {
        [2001] = {
            id = 2001,
            type = 42,
            desc = "完成每日任務10次",
            cond = {16,10,{}},
            mark = 0,
            require = 32,
        },
        [2002] = {
            id = 2002,
            type = 42,
            desc = "參與科舉答題1次",
            cond = {26,1,{}},
            mark = 0,
            require = 32,
        },
        [2003] = {
            id = 2003,
            type = 42,
            desc = "參與10次懲兇打圖",
            cond = {27,10,{}},
            mark = 0,
            require = 32,
        },
        [2004] = {
            id = 2004,
            type = 42,
            desc = "完成老三環副本1次",
            cond = {17,1,{700}},
            mark = 0,
            require = 32,
        },
        [2005] = {
            id = 2005,
            type = 42,
            desc = "完成燕子塢副本1次",
            cond = {17,1,{800}},
            mark = 0,
            require = 32,
        },
        [2006] = {
            id = 2006,
            type = 42,
            desc = "完成珍瓏棋局1次",
            cond = {17,1,{1200}},
            mark = 0,
            require = 32,
        },
    },
    [43] = {
        [3001] = {
            id = 3001,
            type = 43,
            desc = "完成老三環副本3次",
            cond = {17,3,{700}},
            mark = 0,
            require = 0,
        },
        [3002] = {
            id = 3002,
            type = 43,
            desc = "完成燕子塢副本3次",
            cond = {17,3,{800}},
            mark = 0,
            require = 0,
        },
        [3003] = {
            id = 3003,
            type = 43,
            desc = "完成珍瓏棋局3次",
            cond = {17,3,{1200}},
            mark = 0,
            require = 0,
        },
        [3004] = {
            id = 3004,
            type = 43,
            desc = "完成每日任務30次",
            cond = {16,30,{}},
            mark = 0,
            require = 0,
        },
        [3005] = {
            id = 3005,
            type = 43,
            desc = "參與科舉答題3次",
            cond = {26,3,{}},
            mark = 0,
            require = 0,
        },
        [3006] = {
            id = 3006,
            type = 43,
            desc = "完成四絕莊副本3次",
            cond = {17,3,{900}},
            mark = 0,
            require = 0,
        },
        [3007] = {
            id = 3007,
            type = 43,
            desc = "累計完成20環幫會任務",
            cond = {29,20,{}},
            mark = 0,
            require = 0,
        },
        [3008] = {
            id = 3008,
            type = 43,
            desc = "累計參與2次幫會練功活動",
            cond = {32,2,{}},
            mark = 0,
            require = 0,
        },
        [3009] = {
            id = 3009,
            type = 43,
            desc = "累計參與2次宋遼大戰活動",
            cond = {33,2,{}},
            mark = 0,
            require = 0,
        },
        [3010] = {
            id = 3010,
            type = 43,
            desc = "對神器神鑄了3次",
            cond = {43,3,{}},
            mark = 0,
            require = 0,
        },
        [3011] = {
            id = 3011,
            type = 43,
            desc = "熔煉了5件裝備",
            cond = {44,5,{}},
            mark = 0,
            require = 0,
        },
        [3012] = {
            id = 3012,
            type = 43,
            desc = "累計參與30次奪寶馬賊活動",
            cond = {25,30,{}},
            mark = 0,
            require = 0,
        },
        [3013] = {
            id = 3013,
            type = 43,
            desc = "繁殖珍獸1次",
            cond = {35,1,{}},
            mark = 0,
            require = 0,
        },
        [3014] = {
            id = 3014,
            type = 43,
            desc = "師徒傳功3次",
            cond = {94,3,{}},
            mark = 0,
            require = 0,
        },
    },
}