config.examine_new_bank = {
    [1] = {
        id = 1,
        question = '少俠，歡迎來到這裏，初涉江湖，妳知道這座城市的名字嗎？',
        options1 = "蓬萊",
        options2 = "大理",
        options3 = "洛陽",
        options4 = "樓蘭",
        answer = 3,
    },
    [2] = {
        id = 2,
        question = '在哪裏可以看到這個城市的地圖呢？',
        options1 = "買壹張地圖",
        options2 = "點右上角小地圖",
        options3 = "找人問路",
        options4 = "打開導航",
        answer = 2,
    },
    [3] = {
        id = 3,
        question = '任務界面可以查看任務詳情信息，如何打開任務界面呢？',
        options1 = "點主界面任務按鈕",
        options2 = "對屏幕喊任務出來",
        options3 = "問問任務發布人",
        options4 = "打電話給客服",
        answer = 1,
    },
    [4] = {
        id = 4,
        question = '少俠知道打開背包之後怎樣使用物品嗎？',
        options1 = "對屏幕喊使用",
        options2 = "告訴策劃幫我使用",
        options3 = "把物品賣給商店",
        options4 = "點擊物品選擇使用",
        answer = 4,
    },
    [5] = {
        id = 5,
        question = '珍獸是妳的好夥伴，那麽怎樣才能提升珍獸等級呢？',
        options1 = "和它壹起唱歌",
        options2 = "帶它壹起打怪",
        options3 = "陪它壹起聊天",
        options4 = "在屏幕上點擊它",
        answer = 2,
    },
}
