--[[
    @File   : conf_vip
    @Brief  : Vip配置
    @Author : CC
]]

config.recharge = {
    [1] = {
        product_id = 1,
        os = 1,
        gold = 200,
        extra_gold = 20,
        total_gold = 220,
        first_rebate = 0,
        rmb = 100,
        product_name = "200元寶",
        icon = "cz_04",
    },
    [2] = {
        product_id = 2,
        os = 1,
        gold = 500,
        extra_gold = 50,
        total_gold = 550,
        first_rebate = 0,
        rmb = 250,
        product_name = "500元寶",
        icon = "cz_05",
    },
    [3] = {
        product_id = 3,
        os = 1,
        gold = 680,
        extra_gold = 78,
        total_gold = 758,
        first_rebate = 0,
        rmb = 340,
        product_name = "680元寶",
        icon = "cz_06",
    },
    [4] = {
        product_id = 4,
        os = 1,
        gold = 1280,
        extra_gold = 156,
        total_gold = 1436,
        first_rebate = 0,
        rmb = 640,
        product_name = "1280元寶",
        icon = "cz_07",
    },
    [5] = {
        product_id = 5,
        os = 1,
        gold = 1980,
        extra_gold = 288,
        total_gold = 2268,
        first_rebate = 0,
        rmb = 990,
        product_name = "1980元寶",
        icon = "cz_08",
    },
    [6] = {
        product_id = 6,
        os = 1,
        gold = 3280,
        extra_gold = 518,
        total_gold = 3798,
        first_rebate = 0,
        rmb = 1640,
        product_name = "3280元寶",
        icon = "cz_09",
    },
    [7] = {
        product_id = 7,
        os = 1,
        gold = 4880,
        extra_gold = 888,
        total_gold = 5768,
        first_rebate = 0,
        rmb = 2440,
        product_name = "4880元寶",
        icon = "cz_10",
    },
    [8] = {
        product_id = 8,
        os = 1,
        gold = 6480,
        extra_gold = 1288,
        total_gold = 7768,
        first_rebate = 0,
        rmb = 3240,
        product_name = "6480元寶",
        icon = "cz_11",
    },
    [11] = {
        product_id = 11,
        os = 2,
        gold = 60,
        extra_gold = 6,
        total_gold = 66,
        first_rebate = 0,
        rmb = 6,
        product_name = "60元寶",
        icon = "cz_04",
    },
    [12] = {
        product_id = 12,
        os = 2,
        gold = 300,
        extra_gold = 33,
        total_gold = 333,
        first_rebate = 0,
        rmb = 30,
        product_name = "300元寶",
        icon = "cz_05",
    },
    [13] = {
        product_id = 13,
        os = 2,
        gold = 680,
        extra_gold = 78,
        total_gold = 758,
        first_rebate = 0,
        rmb = 68,
        product_name = "680元寶",
        icon = "cz_06",
    },
    [14] = {
        product_id = 14,
        os = 2,
        gold = 1280,
        extra_gold = 156,
        total_gold = 1436,
        first_rebate = 0,
        rmb = 128,
        product_name = "1280元寶",
        icon = "cz_07",
    },
    [15] = {
        product_id = 15,
        os = 2,
        gold = 1980,
        extra_gold = 288,
        total_gold = 2268,
        first_rebate = 0,
        rmb = 198,
        product_name = "1980元寶",
        icon = "cz_08",
    },
    [16] = {
        product_id = 16,
        os = 2,
        gold = 3280,
        extra_gold = 518,
        total_gold = 3798,
        first_rebate = 0,
        rmb = 328,
        product_name = "3280元寶",
        icon = "cz_09",
    },
    [17] = {
        product_id = 17,
        os = 2,
        gold = 4880,
        extra_gold = 888,
        total_gold = 5768,
        first_rebate = 0,
        rmb = 488,
        product_name = "4880元寶",
        icon = "cz_10",
    },
    [18] = {
        product_id = 18,
        os = 2,
        gold = 6480,
        extra_gold = 1288,
        total_gold = 7768,
        first_rebate = 0,
        rmb = 648,
        product_name = "6480元寶",
        icon = "cz_11",
    },
}
