config.pulse_potential = {
    [21] = {
        id = 21,
        type = 1,
        limit = 349,
        name = "冰攻擊",
    },
    [22] = {
        id = 22,
        type = 1,
        limit = 349,
        name = "火攻擊",
    },
    [23] = {
        id = 23,
        type = 1,
        limit = 349,
        name = "玄攻擊",
    },
    [24] = {
        id = 24,
        type = 1,
        limit = 349,
        name = "毒攻擊",
    },
    [109] = {
        id = 109,
        type = 1,
        limit = 100,
        name = "全屬性攻擊",
    },
    [103] = {
        id = 103,
        type = 2,
        limit = 202,
        name = "體力",
    },
    [7] = {
        id = 7,
        type = 2,
        limit = 1254,
        name = "外功防禦",
    },
    [8] = {
        id = 8,
        type = 2,
        limit = 1254,
        name = "內功防禦",
    },
    [3] = {
        id = 3,
        type = 2,
        limit = 5332,
        name = "氣量",
    },
    [101] = {
        id = 101,
        type = 3,
        limit = 231,
        name = "力量",
    },
    [102] = {
        id = 102,
        type = 3,
        limit = 231,
        name = "靈氣",
    },
    [9] = {
        id = 9,
        type = 3,
        limit = 1651,
        name = "命中",
    },
    [104] = {
        id = 104,
        type = 4,
        limit = 224,
        name = "定力",
    },
    [105] = {
        id = 105,
        type = 4,
        limit = 124,
        name = "身法",
    },
    [10] = {
        id = 10,
        type = 4,
        limit = 413,
        name = "閃避",
    },
}
