config.func_foreshow = {
    [1] = {
        level = 2,
        name = "神器預開啟",
        icon = {"t_01"},
        inner_icon = {"z_01"},
        desc = "角色等級到達32級\n即可開啟神器",
    },
    [2] = {
        level = 6,
        name = "獲得珍獸",
        icon = {"t_02"},
        inner_icon = {"z_02"},
        desc = "獲得珍獸，大幅提升戰鬥力",
    },
    [3] = {
        level = 8,
        name = "獲得坐騎",
        icon = {"t_08"},
        inner_icon = {"z_08"},
        desc = "獲得坐騎",
    },
    [4] = {
        level = 9,
        name = "好友",
        icon = {"gn_22"},
        inner_icon = {0},
        desc = "開啟好友功能",
    },
    [5] = {
        level = 11,
        name = "強化",
        icon = {"t_05"},
        inner_icon = {"z_05"},
        desc = "強化提升戰鬥力",
    },
    [6] = {
        level = 13,
        name = "獲得時裝",
        icon = {"t_07"},
        inner_icon = {"z_07"},
        desc = "獲得時裝",
    },
    [7] = {
        level = 14,
        name = "社交動作",
        icon = {"gn_51"},
        inner_icon = {"z_52"},
        desc = "社交動作",
    },
    [8] = {
        level = 15,
        name = "英雄譜",
        icon = {"t_40"},
        inner_icon = {"z_40"},
        desc = "結交培養英雄\n增加戰鬥力",
    },
    [9] = {
        level = 17,
        name = "寶石",
        icon = {"t_42"},
        inner_icon = {"z_42"},
        desc = "寶石大幅提升戰鬥力",
    },
    [10] = {
        level = 18,
        name = "幫會",
        icon = {"t_09"},
        inner_icon = {"z_09"},
        desc = "加入幫會",
    },
    [11] = {
        level = 20,
        name = "熔煉",
        icon = {"t_05"},
        inner_icon = {"z_06"},
        desc = "熔煉提升戰鬥力",
    },
    [12] = {
        level = 21,
        name = "商會",
        icon = {"gn_41"},
        inner_icon = {0},
        desc = "玩家商會交易開啟",
    },
    [13] = {
        level = 22,
        name = "拍賣行",
        icon = {"gn_35"},
        inner_icon = {0},
        desc = "拍賣行開啟",
    },
    [14] = {
        level = 25,
        name = "珍獸養成",
        icon = {"t_02"},
        inner_icon = {"z_03"},
        desc = "養成珍獸\n提升戰鬥力",
    },
    [15] = {
        level = 32,
        name = "神器開啟",
        icon = {"t_01"},
        inner_icon = {"z_55"},
        desc = "開啟神器\n大幅提升戰鬥力",
    },
    [16] = {
        level = 34,
        name = "結拜",
        icon = {"t_44"},
        inner_icon = {"z_44"},
        desc = "開啟結拜\n江湖之路，攜手同行",
    },
    [17] = {
        level = 38,
        name = "結婚",
        icon = {"gn_26"},
        inner_icon = {0},
        desc = "開啟結婚\n與知心伴侶，快意江湖",
    },
    [18] = {
        level = 42,
        name = "神器",
        icon = {"16410102","16410202","16410302","16410402"},
        inner_icon = {"z_11","z_17","z_23","z_29"},
        desc = "可開啟第2把神器",
    },
    [19] = {
        level = 47,
        name = "跑環",
        icon = {"t_00"},
        inner_icon = {"z_50"},
        desc = "跑環快速獲得經驗",
    },
    [20] = {
        level = 49,
        name = "修煉",
        icon = {"t_10"},
        inner_icon = {"z_10"},
        desc = "幫會修煉開啟",
    },
    [21] = {
        level = 50,
        name = "打造",
        icon = {"t_05"},
        inner_icon = {"z_51"},
        desc = "打造極品裝備，大幅提升戰力",
    },
    [22] = {
        level = 52,
        name = "神器",
        icon = {"16410103","16410203","16410303","16410403"},
        inner_icon = {"z_12","z_18","z_24","z_30"},
        desc = "可開啟第3把神器",
    },
    [23] = {
        level = 55,
        name = "珍獸附體",
        icon = {"t_02"},
        inner_icon = {"z_04"},
        desc = "珍獸附體\n大幅提升戰鬥力",
    },
    [24] = {
        level = 62,
        name = "神器",
        icon = {"16410104","16410204","16410304","16410404"},
        inner_icon = {"z_13","z_19","z_25","z_31"},
        desc = "可開啟第4把神器",
    },
    [25] = {
        level = 64,
        name = "暗器",
        icon = {"t_43"},
        inner_icon = {"z_43"},
        desc = "開啟暗器功能\n提升戰鬥力",
    },
    [26] = {
        level = 68,
        name = "經脈",
        icon = {"t_41"},
        inner_icon = {"z_41"},
        desc = "英雄打通經脈\n提升戰鬥力",
    },
    [27] = {
        level = 72,
        name = "神器",
        icon = {"16410105","16410205","16410305","16410405"},
        inner_icon = {"z_14","z_20","z_26","z_32"},
        desc = "可開啟第5把神器",
    },
    [28] = {
        level = 74,
        name = "2階暗器",
        icon = {"16420202"},
        inner_icon = {"z_35"},
        desc = "戰鬥力大幅提升",
    },
    [29] = {
        level = 79,
        name = "武魂",
        icon = {0},
        inner_icon = {"z_53"},
        desc = "開啟武魂，戰鬥力大幅提升",
    },
    [30] = {
        level = 82,
        name = "神器",
        icon = {"16410106","16410206","16410306","16410406"},
        inner_icon = {"z_15","z_21","z_27","z_33"},
        desc = "可開啟第6把神器",
    },
    [31] = {
        level = 84,
        name = "3階暗器",
        icon = {"16420203"},
        inner_icon = {"z_36"},
        desc = "戰鬥力大幅提升",
    },
    [32] = {
        level = 87,
        name = "龍紋",
        icon = {0},
        inner_icon = {"z_54"},
        desc = "開啟龍紋，戰鬥力大幅提升",
    },
    [33] = {
        level = 92,
        name = "神器",
        icon = {"16410107","16410207","16410307","16410407"},
        inner_icon = {"z_16","z_22","z_28","z_34"},
        desc = "可開啟第7把神器",
    },
    [34] = {
        level = 94,
        name = "4階暗器",
        icon = {"16420204"},
        inner_icon = {"z_37"},
        desc = "戰鬥力大幅提升",
    },
}