config.sworn_senior_name = {
    [1] = {
        senior_id = 1,
        name = "老大",
        name2 = "【 老 大 】",
        male_old = "大哥",
        male_young = "無",
        female_old = "大姐",
        female_young = "無",
    },
    [2] = {
        senior_id = 2,
        name = "老二",
        name2 = "【 老 二 】",
        male_old = "二哥",
        male_young = "二弟",
        female_old = "二姐",
        female_young = "二妹",
    },
    [3] = {
        senior_id = 3,
        name = "老三",
        name2 = "【 老 三 】",
        male_old = "三哥",
        male_young = "三弟",
        female_old = "三姐",
        female_young = "三妹",
    },
    [4] = {
        senior_id = 4,
        name = "老四",
        name2 = "【 老 四 】",
        male_old = "四哥",
        male_young = "四弟",
        female_old = "四姐",
        female_young = "四妹",
    },
    [5] = {
        senior_id = 5,
        name = "老五",
        name2 = "【 老 五 】",
        male_old = "無",
        male_young = "五弟",
        female_old = "無",
        female_young = "五妹",
    },
}
