config.transform = {
    [1] = {
        id = 1,
        model_id = 5037,
        body_type = 1,
        params = {},
        can_ride = 0,
        can_change_scene = 0,
        can_attack = 0,
        can_play_action = 0,
        desc = "煉金小人",
    },
    [2] = {
        id = 2,
        model_id = 5037,
        body_type = 1,
        params = {5036},
        can_ride = 0,
        can_change_scene = 0,
        can_attack = 0,
        can_play_action = 0,
        desc = "煉金小人+馬車",
    },
    [3] = {
        id = 3,
        model_id = 1003,
        body_type = 1,
        params = {},
        can_ride = 0,
        can_change_scene = 0,
        can_attack = 0,
        can_play_action = 0,
        desc = "閃電貂",
    },
    [4] = {
        id = 4,
        model_id = 1009,
        body_type = 1,
        params = {},
        can_ride = 0,
        can_change_scene = 0,
        can_attack = 0,
        can_play_action = 0,
        desc = "狐貍",
    },
    [5] = {
        id = 5,
        model_id = 1018,
        body_type = 1,
        params = {},
        can_ride = 0,
        can_change_scene = 0,
        can_attack = 0,
        can_play_action = 0,
        desc = "呆呆牛",
    },
    [6] = {
        id = 6,
        model_id = 1020,
        body_type = 1,
        params = {},
        can_ride = 0,
        can_change_scene = 0,
        can_attack = 0,
        can_play_action = 0,
        desc = "丘比特",
    },
}
