config.achieve_type = {
    [11] = {
        cate = 1,
        name = "江湖",
        star = 25,
        title = 6001,
        icon_up = "cjqy_1jh",
        icon_down = "cjqy_1jh2",
        achieve_icon = "cjzi_01",
    },
    [12] = {
        cate = 1,
        name = "結拜",
        star = 5,
        title = 6002,
        icon_up = "cjqy_2jb",
        icon_down = "cjqy_2jb2",
        achieve_icon = "cjzi_02",
    },
    [13] = {
        cate = 1,
        name = "英雄譜",
        star = 5,
        title = 6003,
        icon_up = "cjqy_12yxp",
        icon_down = "cjqy_12yxp2",
        achieve_icon = "cjzi_03",
    },
    [21] = {
        cate = 2,
        name = "幫會",
        star = 30,
        title = 6004,
        icon_up = "cjqy_3bh",
        icon_down = "cjqy_3bh2",
        achieve_icon = "cjzi_04",
    },
    [31] = {
        cate = 3,
        name = "裝備",
        star = 40,
        title = 6005,
        icon_up = "cjqy_10zb",
        icon_down = "cjqy_10zb2",
        achieve_icon = "cjzi_05",
    },
    [32] = {
        cate = 3,
        name = "珍獸",
        star = 20,
        title = 6006,
        icon_up = "cjqy_11zs",
        icon_down = "cjqy_11zs2",
        achieve_icon = "cjzi_06",
    },
    [41] = {
        cate = 4,
        name = "副本",
        star = 20,
        title = 6008,
        icon_up = "cjqy_5fb",
        icon_down = "cjqy_5fb2",
        achieve_icon = "cjzi_08",
    },
    [43] = {
        cate = 4,
        name = "門派競技",
        star = 20,
        title = 6009,
        icon_up = "cjqy_7mp",
        icon_down = "cjqy_7mp2",
        achieve_icon = "cjzi_10",
    },
    [51] = {
        cate = 5,
        name = "日常活動",
        star = 40,
        title = 6010,
        icon_up = "cjqy_8rc",
        icon_down = "cjqy_8rc2",
        achieve_icon = "cjzi_11",
    },
}