config.shop = {
    [1] = {
        id = 1,
        name = "元寶商店",
        price_type = 25,
        function_id = 1000,
        sort = 1,
        task = 0,
    },
    [2] = {
        id = 2,
        name = "綁元商店",
        price_type = 13,
        function_id = 1000,
        sort = 2,
        task = 0,
    },
    [3] = {
        id = 3,
        name = "銀兩商店",
        price_type = 17,
        function_id = 1000,
        sort = 3,
        task = 0,
    },
    [4] = {
        id = 4,
        name = "神秘商店",
        price_type = 13,
        function_id = 1000,
        sort = 4,
        task = 0,
    },
    [5] = {
        id = 5,
        name = "材料商店",
        price_type = 2,
        function_id = 1109,
        sort = 1,
        task = 0,
    },
    [6] = {
        id = 6,
        name = "神獸商店",
        price_type = 2,
        function_id = 1110,
        sort = 1,
        task = 0,
    },
    [7] = {
        id = 7,
        name = "幫會商店",
        price_type = 10,
        function_id = 1001,
        sort = 2,
        task = 0,
    },
    [8] = {
        id = 8,
        name = "幫會福利",
        price_type = 10,
        function_id = 1001,
        sort = 3,
        task = 0,
    },
    [9] = {
        id = 9,
        name = "競技商店",
        price_type = 2,
        function_id = 1003,
        sort = 1,
        task = 0,
    },
    [10] = {
        id = 10,
        name = "競技福利",
        price_type = 2,
        function_id = 1003,
        sort = 2,
        task = 0,
    },
    [11] = {
        id = 11,
        name = "奪寶商店",
        price_type = 2,
        function_id = 1111,
        sort = 1,
        task = 0,
    },
    [12] = {
        id = 12,
        name = "隨身商店",
        price_type = 4,
        function_id = 1114,
        sort = 1,
        task = 0,
    },
    [13] = {
        id = 13,
        name = "1級",
        price_type = 12,
        function_id = 1115,
        sort = 1,
        task = 0,
    },
    [14] = {
        id = 14,
        name = "2級",
        price_type = 12,
        function_id = 1115,
        sort = 2,
        task = 0,
    },
    [15] = {
        id = 15,
        name = "3級",
        price_type = 12,
        function_id = 1115,
        sort = 3,
        task = 0,
    },
    [16] = {
        id = 16,
        name = "4級",
        price_type = 12,
        function_id = 1115,
        sort = 4,
        task = 0,
    },
    [17] = {
        id = 17,
        name = "5級",
        price_type = 12,
        function_id = 1115,
        sort = 5,
        task = 0,
    },
    [18] = {
        id = 18,
        name = "宋遼商店",
        price_type = 26,
        function_id = 1120,
        sort = 1,
        task = 0,
    },
    [19] = {
        id = 19,
        name = "許願果商店",
        price_type = 19,
        function_id = 1121,
        sort = 1,
        task = 0,
    },
    [20] = {
        id = 20,
        name = "藏寶閣",
        price_type = 20,
        function_id = 1122,
        sort = 1,
        task = 0,
    },
    [21] = {
        id = 21,
        name = "積分商城",
        price_type = 21,
        function_id = 1123,
        sort = 1,
        task = 0,
    },
    [22] = {
        id = 22,
        name = "桃李商店",
        price_type = 22,
        function_id = 1124,
        sort = 1,
        task = 0,
    },
    [23] = {
        id = 23,
        name = "恩愛商店",
        price_type = 17,
        function_id = 1125,
        sort = 1,
        task = 0,
    },
    [24] = {
        id = 24,
        name = "百煉商店",
        price_type = 15,
        function_id = 1126,
        sort = 1,
        task = 0,
    },
    [25] = {
        id = 25,
        name = "俠義商店",
        price_type = 16,
        function_id = 1127,
        sort = 1,
        task = 0,
    },
    [26] = {
        id = 26,
        name = "天命商店",
        price_type = 24,
        function_id = 1128,
        sort = 1,
        task = 0,
    },
    [27] = {
        id = 27,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1129,
        sort = 1,
        task = 1,
    },
    [28] = {
        id = 28,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1130,
        sort = 1,
        task = 1,
    },
    [29] = {
        id = 29,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1131,
        sort = 1,
        task = 1,
    },
    [30] = {
        id = 30,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1132,
        sort = 1,
        task = 1,
    },
    [31] = {
        id = 31,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1133,
        sort = 1,
        task = 1,
    },
    [32] = {
        id = 32,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1134,
        sort = 1,
        task = 1,
    },
    [33] = {
        id = 33,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1135,
        sort = 1,
        task = 1,
    },
    [34] = {
        id = 34,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1136,
        sort = 1,
        task = 1,
    },
    [35] = {
        id = 35,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1137,
        sort = 1,
        task = 1,
    },
    [36] = {
        id = 36,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1138,
        sort = 1,
        task = 1,
    },
    [37] = {
        id = 37,
        name = "雜貨商店",
        price_type = 4,
        function_id = 1139,
        sort = 1,
        task = 1,
    },
    [38] = {
        id = 38,
        name = "太湖石兌換商店",
        price_type = 16160124,
        function_id = 1140,
        sort = 1,
        task = 0,
    },
    [39] = {
        id = 39,
        name = "徒弟禮包",
        price_type = 2,
        function_id = 3303,
        sort = 1,
        task = 0,
    },
    [40] = {
        id = 40,
        name = "煙花商店",
        price_type = 4,
        function_id = 1141,
        sort = 1,
        task = 0,
    },
}