config.guild_bonus = {
    [1] = {
        [1] =  {
            type = 1,
            stage = 1,
            num = 500,
            bonus = 20,
            name = "幫會任務",
        },
        [2] =  {
            type = 1,
            stage = 2,
            num = 750,
            bonus = 20,
            name = "幫會任務",
        },
        [3] =  {
            type = 1,
            stage = 3,
            num = 1000,
            bonus = 40,
            name = "幫會任務",
        },
        [4] =  {
            type = 1,
            stage = 4,
            num = 1250,
            bonus = 60,
            name = "幫會任務",
        },
        [5] =  {
            type = 1,
            stage = 5,
            num = 1500,
            bonus = 60,
            name = "幫會任務",
        },
    },
    [2] = {
        [1] =  {
            type = 2,
            stage = 1,
            num = 700,
            bonus = 40,
            name = "幫會煉金",
        },
        [2] =  {
            type = 2,
            stage = 2,
            num = 1000,
            bonus = 40,
            name = "幫會煉金",
        },
        [3] =  {
            type = 2,
            stage = 3,
            num = 2100,
            bonus = 60,
            name = "幫會煉金",
        },
        [4] =  {
            type = 2,
            stage = 4,
            num = 3500,
            bonus = 80,
            name = "幫會煉金",
        },
        [5] =  {
            type = 2,
            stage = 5,
            num = 4200,
            bonus = 80,
            name = "幫會煉金",
        },
    },
    [3] = {
        [1] =  {
            type = 3,
            stage = 1,
            num = 400,
            bonus = 40,
            name = "運鏢",
        },
        [2] =  {
            type = 3,
            stage = 2,
            num = 600,
            bonus = 40,
            name = "運鏢",
        },
        [3] =  {
            type = 3,
            stage = 3,
            num = 1200,
            bonus = 60,
            name = "運鏢",
        },
        [4] =  {
            type = 3,
            stage = 4,
            num = 2100,
            bonus = 80,
            name = "運鏢",
        },
        [5] =  {
            type = 3,
            stage = 5,
            num = 2500,
            bonus = 80,
            name = "運鏢",
        },
    },
    [4] = {
        [1] =  {
            type = 4,
            stage = 1,
            num = 50,
            bonus = 40,
            name = "行酒令",
        },
        [2] =  {
            type = 4,
            stage = 2,
            num = 75,
            bonus = 40,
            name = "行酒令",
        },
        [3] =  {
            type = 4,
            stage = 3,
            num = 100,
            bonus = 60,
            name = "行酒令",
        },
        [4] =  {
            type = 4,
            stage = 4,
            num = 125,
            bonus = 80,
            name = "行酒令",
        },
        [5] =  {
            type = 4,
            stage = 5,
            num = 150,
            bonus = 80,
            name = "行酒令",
        },
    },
    [5] = {
        [1] =  {
            type = 5,
            stage = 1,
            num = 7,
            bonus = 40,
            name = "守衛戰",
        },
        [2] =  {
            type = 5,
            stage = 2,
            num = 12,
            bonus = 80,
            name = "守衛戰",
        },
        [3] =  {
            type = 5,
            stage = 3,
            num = 17,
            bonus = 120,
            name = "守衛戰",
        },
        [4] =  {
            type = 5,
            stage = 4,
            num = 26,
            bonus = 160,
            name = "守衛戰",
        },
        [5] =  {
            type = 5,
            stage = 5,
            num = 36,
            bonus = 200,
            name = "守衛戰",
        },
    },
}