config.combat_power_battle = {
	[1] = {
		type = 1,
		seq = 1,
		value = 0.16669999999999999,
		sign = "hp_lim",
		name = "生命",
		attr_name = "生    命",
		pet = 0.067,
		pet_attach = 0.46676,
	},
	[2] = {
		type = 2,
		seq = 2,
		value = 0,
		sign = "hp_rec",
		name = "生命回復",
		attr_name = "生命回復",
		pet = 0,
		pet_attach = 0,
	},
	[3] = {
		type = 3,
		seq = 3,
		value = 0,
		sign = "mp_lim",
		name = "氣量",
		attr_name = "氣    量",
		pet = 0,
		pet_attach = 0,
	},
	[4] = {
		type = 4,
		seq = 4,
		value = 0,
		sign = "mp_rec",
		name = "氣量回復",
		attr_name = "氣量回復",
		pet = 0,
		pet_attach = 0,
	},
	[5] = {
		type = 5,
		seq = 5,
		value = 2.7,
		sign = "outer_att",
		name = "外功攻擊",
		attr_name = "外功攻擊",
		pet = 1.08,
		pet_attach = 7.56,
	},
	[6] = {
		type = 6,
		seq = 6,
		value = 2.7,
		sign = "inner_att",
		name = "內功攻擊",
		attr_name = "內功攻擊",
		pet = 1.08,
		pet_attach = 7.56,
	},
	[7] = {
		type = 7,
		seq = 7,
		value = 2.7,
		sign = "outer_def",
		name = "外功防禦",
		attr_name = "外功防禦",
		pet = 1.08,
		pet_attach = 7.56,
	},
	[8] = {
		type = 8,
		seq = 8,
		value = 2.7,
		sign = "inner_def",
		name = "內功防禦",
		attr_name = "內功防禦",
		pet = 1.08,
		pet_attach = 7.56,
	},
	[9] = {
		type = 9,
		seq = 9,
		value = 2,
		sign = "hit",
		name = "命中",
		attr_name = "命    中",
		pet = 0.8,
		pet_attach = 5.6,
	},
	[10] = {
		type = 10,
		seq = 10,
		value = 8.1999999999999993,
		sign = "dodge",
		name = "閃避",
		attr_name = "閃    避",
		pet = 3.28,
		pet_attach = 22.96,
	},
	[11] = {
		type = 11,
		seq = 11,
		value = 10.6,
		sign = "crit_hurt",
		name = "會心攻擊",
		attr_name = "會心攻擊",
		pet = 4.24,
		pet_attach = 29.68,
	},
	[12] = {
		type = 12,
		seq = 12,
		value = 20,
		sign = "crit_def",
		name = "會心防禦",
		attr_name = "會心防禦",
		pet = 8,
		pet_attach = 56,
	},
	[13] = {
		type = 13,
		seq = 13,
		value = 0,
		sign = "att_speed",
		name = "攻擊速度",
		attr_name = "攻擊速度",
		pet = 0,
		pet_attach = 0,
	},
	[14] = {
		type = 14,
		seq = 14,
		value = 0,
		sign = "move_speed",
		name = "移動速度",
		attr_name = "移動速度",
		pet = 0,
		pet_attach = 0,
	},
	[15] = {
		type = 15,
		seq = 15,
		value = 0,
		sign = "igndef_hurt",
		name = "無視防禦傷害",
		attr_name = "無視防禦傷害",
		pet = 0,
		pet_attach = 0,
	},
	[16] = {
		type = 16,
		seq = 16,
		value = 0,
		sign = "igndef_def",
		name = "無視傷害減免",
		attr_name = "無視傷害減免",
		pet = 0,
		pet_attach = 0,
	},
	[17] = {
		type = 17,
		seq = 17,
		value = 0,
		sign = "hurt_add",
		name = "傷害加成",
		attr_name = "傷害加成",
		pet = 0,
		pet_attach = 0,
	},
	[18] = {
		type = 18,
		seq = 18,
		value = 0,
		sign = "hurt_red",
		name = "傷害減免",
		attr_name = "傷害減免",
		pet = 0,
		pet_attach = 0,
	},
	[19] = {
		type = 19,
		seq = 19,
		value = 0,
		sign = "crit_add",
		name = "會傷加成",
		attr_name = "會傷加成",
		pet = 0,
		pet_attach = 0,
	},
	[20] = {
		type = 20,
		seq = 20,
		value = 0,
		sign = "crit_red",
		name = "會傷減免",
		attr_name = "會傷減免",
		pet = 0,
		pet_attach = 0,
	},
	[21] = {
		type = 21,
		seq = 21,
		value = 10,
		sign = "aatt_ice",
		name = "冰攻擊",
		attr_name = "冰 攻 擊",
		pet = 4,
		pet_attach = 28,
	},
	[22] = {
		type = 22,
		seq = 22,
		value = 10,
		sign = "aatt_fire",
		name = "火攻擊",
		attr_name = "火 攻 擊",
		pet = 4,
		pet_attach = 28,
	},
	[23] = {
		type = 23,
		seq = 23,
		value = 10,
		sign = "aatt_dark",
		name = "玄攻擊",
		attr_name = "玄 攻 擊",
		pet = 4,
		pet_attach = 28,
	},
	[24] = {
		type = 24,
		seq = 24,
		value = 10,
		sign = "aatt_poison",
		name = "毒攻擊",
		attr_name = "毒 攻 擊",
		pet = 4,
		pet_attach = 28,
	},
	[25] = {
		type = 25,
		seq = 25,
		value = 25,
		sign = "adef_ice",
		name = "冰抗性",
		attr_name = "冰 抗 性",
		pet = 10,
		pet_attach = 70,
	},
	[26] = {
		type = 26,
		seq = 26,
		value = 25,
		sign = "adef_fire",
		name = "火抗性",
		attr_name = "火 抗 性",
		pet = 10,
		pet_attach = 70,
	},
	[27] = {
		type = 27,
		seq = 27,
		value = 25,
		sign = "adef_dark",
		name = "玄抗性",
		attr_name = "玄 抗 性",
		pet = 10,
		pet_attach = 70,
	},
	[28] = {
		type = 28,
		seq = 28,
		value = 25,
		sign = "adef_poison",
		name = "毒抗性",
		attr_name = "毒 抗 性",
		pet = 10,
		pet_attach = 70,
	},
	[29] = {
		type = 29,
		seq = 29,
		value = 25,
		sign = "adef_red_ice",
		name = "冰減抗",
		attr_name = "冰 減 抗",
		pet = 10,
		pet_attach = 70,
	},
	[30] = {
		type = 30,
		seq = 30,
		value = 25,
		sign = "adef_red_fire",
		name = "火減抗",
		attr_name = "火 減 抗",
		pet = 10,
		pet_attach = 70,
	},
	[31] = {
		type = 31,
		seq = 31,
		value = 25,
		sign = "adef_red_dark",
		name = "玄減抗",
		attr_name = "玄 減 抗",
		pet = 10,
		pet_attach = 70,
	},
	[32] = {
		type = 32,
		seq = 32,
		value = 25,
		sign = "adef_red_poison",
		name = "毒減抗",
		attr_name = "毒 減 抗",
		pet = 10,
		pet_attach = 70,
	},
	[33] = {
		type = 33,
		seq = 33,
		value = 100,
		sign = "adef_min_ice",
		name = "冰抗性下限",
		attr_name = "冰抗性下限",
		pet = 40,
		pet_attach = 280,
	},
	[34] = {
		type = 34,
		seq = 34,
		value = 100,
		sign = "adef_min_fire",
		name = "火抗性下限",
		attr_name = "火抗性下限",
		pet = 40,
		pet_attach = 280,
	},
	[35] = {
		type = 35,
		seq = 35,
		value = 100,
		sign = "adef_min_dark",
		name = "玄抗性下限",
		attr_name = "玄抗性下限",
		pet = 40,
		pet_attach = 280,
	},
	[36] = {
		type = 36,
		seq = 36,
		value = 100,
		sign = "adef_min_poison",
		name = "毒抗性下限",
		attr_name = "毒抗性下限",
		pet = 40,
		pet_attach = 280,
	},
	[37] = {
		type = 37,
		seq = 37,
		value = 10,
		sign = "ahurt_add_ice",
		name = "冰傷害加成",
		attr_name = "冰傷害加成",
		pet = 4,
		pet_attach = 28,
	},
	[38] = {
		type = 38,
		seq = 38,
		value = 10,
		sign = "ahurt_add_fire",
		name = "火傷害加成",
		attr_name = "火傷害加成",
		pet = 4,
		pet_attach = 28,
	},
	[39] = {
		type = 39,
		seq = 39,
		value = 10,
		sign = "ahurt_add_dark",
		name = "玄傷害加成",
		attr_name = "玄傷害加成",
		pet = 4,
		pet_attach = 28,
	},
	[40] = {
		type = 40,
		seq = 40,
		value = 10,
		sign = "ahurt_add_poison",
		name = "毒傷害加成",
		attr_name = "毒傷害加成",
		pet = 4,
		pet_attach = 28,
	},
	[41] = {
		type = 41,
		seq = 41,
		value = 0,
		sign = "ahurt_add",
		name = "屬性傷害加成",
		attr_name = "屬性傷害加成",
		pet = 0,
		pet_attach = 0,
	},
	[42] = {
		type = 42,
		seq = 42,
		value = 0,
		sign = "ahurt_red",
		name = "屬性傷害減免",
		attr_name = "屬性傷害減免",
		pet = 0,
		pet_attach = 0,
	},
	[43] = {
		type = 43,
		seq = 43,
		value = 1.1000000000000001,
		sign = "penetrate_att",
		name = "穿刺攻擊",
		attr_name = "穿刺攻擊",
		pet = 0,
		pet_attach = 0,
	},
	[44] = {
		type = 44,
		seq = 44,
		value = 1.1000000000000001,
		sign = "penetrate_def",
		name = "穿刺防禦",
		attr_name = "穿刺防禦",
		pet = 0,
		pet_attach = 0,
	},
	[45] = {
		type = 45,
		seq = 45,
		value = 4.8,
		sign = "penetrate_crit",
		name = "穿刺會心",
		attr_name = "穿刺會心",
		pet = 0,
		pet_attach = 0,
	},
	[46] = {
		type = 46,
		seq = 46,
		value = 4.8,
		sign = "penetrate_crit_def",
		name = "穿刺會心防禦",
		attr_name = "穿刺會防",
		pet = 0,
		pet_attach = 0,
	},
	[47] = {
		type = 47,
		seq = 47,
		value = 0,
		sign = "penetrate_speed",
		name = "穿刺速度",
		attr_name = "穿刺速度",
		pet = 0,
		pet_attach = 0,
	},
	[48] = {
		type = 48,
		seq = 48,
		value = 0,
		sign = "penetrate_hurt_add",
		name = "穿刺傷害加成",
		attr_name = "穿刺傷害加成",
		pet = 0,
		pet_attach = 0,
	},
	[49] = {
		type = 49,
		seq = 49,
		value = 0,
		sign = "penetrate_hurt_red",
		name = "穿刺傷害減免",
		attr_name = "穿刺傷害減免",
		pet = 0,
		pet_attach = 0,
	},
	[50] = {
		type = 50,
		seq = 50,
		value = 10,
		sign = "ahurt_red_ice",
		name = "冰傷害減免",
		attr_name = "冰傷害減免",
		pet = 4,
		pet_attach = 28,
	},
	[51] = {
		type = 51,
		seq = 51,
		value = 10,
		sign = "ahurt_red_fire",
		name = "火傷害減免",
		attr_name = "火傷害減免",
		pet = 4,
		pet_attach = 28,
	},
	[52] = {
		type = 52,
		seq = 52,
		value = 10,
		sign = "ahurt_red_dark",
		name = "玄傷害減免",
		attr_name = "玄傷害減免",
		pet = 4,
		pet_attach = 28,
	},
	[53] = {
		type = 53,
		seq = 53,
		value = 10,
		sign = "ahurt_red_poison",
		name = "毒傷害減免",
		attr_name = "毒傷害減免",
		pet = 4,
		pet_attach = 28,
	},
	[54] = {
		type = 54,
		seq = 54,
		value = 0,
		sign = "ahurt_perc_ice",
		name = "冰傷害萬分比",
		attr_name = "冰傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[55] = {
		type = 55,
		seq = 55,
		value = 0,
		sign = "ahurt_perc_fire",
		name = "火傷害萬分比",
		attr_name = "火傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[56] = {
		type = 56,
		seq = 56,
		value = 0,
		sign = "ahurt_perc_dark",
		name = "玄傷害萬分比",
		attr_name = "玄傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[57] = {
		type = 57,
		seq = 57,
		value = 0,
		sign = "ahurt_perc_poison",
		name = "毒傷害萬分比",
		attr_name = "毒傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[58] = {
		type = 58,
		seq = 58,
		value = 0,
		sign = "aaffect_perc_ice",
		name = "受冰傷害萬分比",
		attr_name = "受冰傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[59] = {
		type = 59,
		seq = 59,
		value = 0,
		sign = "aaffect_perc_fire",
		name = "受火傷害萬分比",
		attr_name = "受火傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[60] = {
		type = 60,
		seq = 60,
		value = 0,
		sign = "aaffect_perc_dark",
		name = "受玄傷害萬分比",
		attr_name = "受玄傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[61] = {
		type = 61,
		seq = 61,
		value = 0,
		sign = "aaffect_perc_poison",
		name = "受毒傷害萬分比",
		attr_name = "受毒傷害萬分比",
		pet = 0,
		pet_attach = 0,
	},
	[62] = {
		type = 62,
		seq = 62,
		value = 0,
		sign = "active_cure_fact",
		name = "治療率",
		attr_name = "治療率",
		pet = 0,
		pet_attach = 0,
	},
	[63] = {
		type = 63,
		seq = 63,
		value = 0,
		sign = "passive_cure_fact",
		name = "被治療率",
		attr_name = "被治療率",
		pet = 0,
		pet_attach = 0,
	},
	[64] = {
		type = 64,
		seq = 64,
		value = 0,
		sign = "active_harm_fact",
		name = "傷害率",
		attr_name = "傷害率",
		pet = 0,
		pet_attach = 0,
	},
	[65] = {
		type = 65,
		seq = 65,
		value = 0,
		sign = "passive_harm_fact",
		name = "減傷率",
		attr_name = "減傷率",
		pet = 0,
		pet_attach = 0,
	},
}