config.strengthen_grade = {
    [1] = {
        id = 1,
        type = 1,
        name = "急需提升",
        color = "#DB4734",
    },
    [2] = {
        id = 2,
        type = 1,
        name = "急需提升",
        color = "#DB4734",
    },
    [3] = {
        id = 3,
        type = 1,
        name = "急需提升",
        color = "#DB4734",
    },
    [4] = {
        id = 4,
        type = 1,
        name = "急需提升",
        color = "#DB4734",
    },
    [5] = {
        id = 5,
        type = 1,
        name = "急需提升",
        color = "#DB4734",
    },
    [6] = {
        id = 6,
        type = 1,
        name = "出類拔萃",
        color = "#C54EF4",
    },
    [7] = {
        id = 7,
        type = 1,
        name = "勉勉強強",
        color = "#5FC934",
    },
    [8] = {
        id = 8,
        type = 1,
        name = "成績平平",
        color = "#3171F5",
    },
    [9] = {
        id = 9,
        type = 1,
        name = "出類拔萃",
        color = "#C54EF4",
    },
    [10] = {
        id = 10,
        type = 1,
        name = "出神入化",
        color = "#D5701D",
    },
    [101] = {
        id = 101,
        type = 2,
        name = "推薦提升",
        color = "#DB4734",
    },
    [102] = {
        id = 102,
        type = 2,
        name = "推薦提升",
        color = "#DB4734",
    },
    [103] = {
        id = 103,
        type = 2,
        name = "推薦提升",
        color = "#DB4734",
    },
    [104] = {
        id = 104,
        type = 2,
        name = "推薦提升",
        color = "#DB4734",
    },
    [105] = {
        id = 105,
        type = 2,
        name = "推薦提升",
        color = "#DB4734",
    },
    [106] = {
        id = 106,
        type = 2,
        name = "出類拔萃",
        color = "#C54EF4",
    },
    [107] = {
        id = 107,
        type = 2,
        name = "勉勉強強",
        color = "#5FC934",
    },
    [108] = {
        id = 108,
        type = 2,
        name = "成績平平",
        color = "#3171F5",
    },
    [109] = {
        id = 109,
        type = 2,
        name = "出類拔萃",
        color = "#C54EF4",
    },
    [110] = {
        id = 110,
        type = 2,
        name = "出神入化",
        color = "#D5701D",
    },
}
