config.achieve_task = {
    [1101] = {
        [1] = {
            name = "附近聊天",
            type = 11,
            star = 1,
            show_star = 1,
            reward = 305001,
            desc = "在附近聊天中使用文本向大家問好",
            condition = {54,1,{3}},
        },
        [2] = {
            name = "幫會聊天",
            type = 11,
            star = 1,
            show_star = 2,
            reward = 305002,
            desc = "在幫會聊天中使用文本向大家問好",
            condition = {54,1,{2}},
        },
        [3] = {
            name = "隊伍聊天",
            type = 11,
            star = 1,
            show_star = 3,
            reward = 305003,
            desc = "在隊伍聊天中使用文本向大家問好",
            condition = {54,1,{3}},
        },
        [4] = {
            name = "世界聊天",
            type = 11,
            star = 1,
            show_star = 4,
            reward = 305004,
            desc = "在世界聊天中使用文本向大家問好",
            condition = {54,1,{1}},
        },
        [5] = {
            name = "幫會聊天",
            type = 11,
            star = 1,
            show_star = 5,
            reward = 305005,
            desc = "在幫會聊天中使用語音向大家問好",
            condition = {57,1,{2}},
        },
    },
    [1104] = {
        [1] = {
            name = "江湖藏寶",
            type = 11,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "使用普通藏寶圖挖寶10次",
            condition = {28,10,{1}},
        },
        [2] = {
            name = "江湖藏寶",
            type = 11,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "使用普通藏寶圖挖寶50次",
            condition = {28,50,{1}},
        },
        [3] = {
            name = "江湖藏寶",
            type = 11,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "使用普通藏寶圖挖寶100次",
            condition = {28,100,{1}},
        },
        [4] = {
            name = "江湖藏寶",
            type = 11,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "使用普通藏寶圖挖寶200次",
            condition = {28,200,{1}},
        },
        [5] = {
            name = "江湖藏寶",
            type = 11,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "使用普通藏寶圖挖寶500次",
            condition = {28,500,{1}},
        },
    },
    [1105] = {
        [1] = {
            name = "稀世寶圖",
            type = 11,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "使用稀世藏寶圖挖寶1次",
            condition = {28,1,{2}},
        },
        [2] = {
            name = "稀世寶圖",
            type = 11,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "使用稀世藏寶圖挖寶10次",
            condition = {28,10,{2}},
        },
        [3] = {
            name = "稀世寶圖",
            type = 11,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "使用稀世藏寶圖挖寶30次",
            condition = {28,30,{2}},
        },
        [4] = {
            name = "稀世寶圖",
            type = 11,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "使用稀世藏寶圖挖寶60次",
            condition = {28,60,{2}},
        },
        [5] = {
            name = "稀世寶圖",
            type = 11,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "使用稀世藏寶圖挖寶100次",
            condition = {28,100,{2}},
        },
    },
    [1201] = {
        [1] = {
            name = "結拜兄弟",
            type = 12,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "與結拜兄弟累積獲得1000點金蘭值",
            condition = {60,1000,{}},
        },
        [2] = {
            name = "結拜兄弟",
            type = 12,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "與結拜兄弟累積獲得5000點金蘭值",
            condition = {60,5000,{}},
        },
        [3] = {
            name = "結拜兄弟",
            type = 12,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "與結拜兄弟累積獲得10000點金蘭值",
            condition = {60,10000,{}},
        },
        [4] = {
            name = "結拜兄弟",
            type = 12,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "與結拜兄弟累積獲得20000點金蘭值",
            condition = {60,20000,{}},
        },
        [5] = {
            name = "結拜兄弟",
            type = 12,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "與結拜兄弟累積獲得50000點金蘭值",
            condition = {60,50000,{}},
        },
    },
    [1301] = {
        [1] = {
            name = "英雄譜",
            type = 13,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "在英雄譜上結交4個英雄",
            condition = {24,4,{}},
        },
        [2] = {
            name = "英雄譜",
            type = 13,
            star = 1,
            show_star = 2,
            reward = 305007,
            desc = "在英雄譜上結交8個英雄",
            condition = {24,8,{}},
        },
        [3] = {
            name = "英雄譜",
            type = 13,
            star = 1,
            show_star = 3,
            reward = 305008,
            desc = "在英雄譜上結交18個英雄",
            condition = {24,18,{}},
        },
        [4] = {
            name = "英雄譜",
            type = 13,
            star = 1,
            show_star = 4,
            reward = 305011,
            desc = "在英雄譜上結交24個英雄",
            condition = {24,24,{}},
        },
        [5] = {
            name = "英雄譜",
            type = 13,
            star = 1,
            show_star = 5,
            reward = 305212,
            desc = "在英雄譜上結交32個英雄，達成可獲得稱號：天下誰人不識君",
            condition = {24,32,{}},
        },
    },
    [2101] = {
        [1] = {
            name = "幫會練功",
            type = 21,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "進行幫會練功1次",
            condition = {32,1,{}},
        },
        [2] = {
            name = "幫會練功",
            type = 21,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "進行幫會練功10次",
            condition = {32,10,{}},
        },
        [3] = {
            name = "幫會練功",
            type = 21,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "進行幫會練功20次",
            condition = {32,20,{}},
        },
        [4] = {
            name = "幫會練功",
            type = 21,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "進行幫會練功60次",
            condition = {32,60,{}},
        },
        [5] = {
            name = "幫會練功",
            type = 21,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "進行幫會練功100次",
            condition = {32,100,{}},
        },
    },
    [2102] = {
        [1] = {
            name = "幫會行酒令",
            type = 21,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "參加幫會行酒令1次",
            condition = {61,1,{}},
        },
        [2] = {
            name = "幫會行酒令",
            type = 21,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "參加幫會行酒令5次",
            condition = {61,5,{}},
        },
        [3] = {
            name = "幫會行酒令",
            type = 21,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "參加幫會行酒令20次",
            condition = {61,20,{}},
        },
        [4] = {
            name = "幫會行酒令",
            type = 21,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "參加幫會行酒令60次",
            condition = {61,60,{}},
        },
        [5] = {
            name = "幫會行酒令",
            type = 21,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "參加幫會行酒令120次",
            condition = {61,120,{}},
        },
    },
    [2103] = {
        [1] = {
            name = "幫會煉金",
            type = 21,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "完成幫會煉金3次",
            condition = {48,3,{}},
        },
        [2] = {
            name = "幫會煉金",
            type = 21,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "完成幫會煉金15次",
            condition = {48,15,{}},
        },
        [3] = {
            name = "幫會煉金",
            type = 21,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "完成幫會煉金75次",
            condition = {48,75,{}},
        },
        [4] = {
            name = "幫會煉金",
            type = 21,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "完成幫會煉金150次",
            condition = {48,150,{}},
        },
        [5] = {
            name = "幫會煉金",
            type = 21,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "完成幫會煉金250次",
            condition = {48,250,{}},
        },
    },
    [2104] = {
        [1] = {
            name = "幫會守衛",
            type = 21,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "參與幫會守衛戰，並堅持防守至10波怪物",
            condition = {62,10,{}},
        },
        [2] = {
            name = "幫會守衛",
            type = 21,
            star = 1,
            show_star = 2,
            reward = 305007,
            desc = "參與幫會守衛戰，並堅持防守至16波怪物",
            condition = {62,16,{}},
        },
        [3] = {
            name = "幫會守衛",
            type = 21,
            star = 1,
            show_star = 3,
            reward = 305008,
            desc = "參與幫會守衛戰，並堅持防守至24波怪物",
            condition = {62,24,{}},
        },
        [4] = {
            name = "幫會守衛",
            type = 21,
            star = 1,
            show_star = 4,
            reward = 305009,
            desc = "參與幫會守衛戰，並堅持防守至30波怪物",
            condition = {62,30,{}},
        },
        [5] = {
            name = "幫會守衛",
            type = 21,
            star = 1,
            show_star = 5,
            reward = 305010,
            desc = "參與幫會守衛戰，並堅持防守至36波怪物",
            condition = {62,36,{}},
        },
    },
    [2105] = {
        [1] = {
            name = "幫會發紅包",
            type = 21,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "在幫會中發5個紅包",
            condition = {63,5,{}},
        },
        [2] = {
            name = "幫會發紅包",
            type = 21,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "在幫會中發10個紅包",
            condition = {63,10,{}},
        },
        [3] = {
            name = "幫會發紅包",
            type = 21,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "在幫會中發50個紅包",
            condition = {63,50,{}},
        },
        [4] = {
            name = "幫會發紅包",
            type = 21,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "在幫會中發150個紅包",
            condition = {63,150,{}},
        },
        [5] = {
            name = "幫會發紅包",
            type = 21,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "在幫會中發300個紅包",
            condition = {63,300,{}},
        },
    },
    [2106] = {
        [1] = {
            name = "幫會搶紅包",
            type = 21,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "成功搶到幫會紅包10次",
            condition = {64,10,{}},
        },
        [2] = {
            name = "幫會搶紅包",
            type = 21,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "成功搶到幫會紅包20次",
            condition = {64,20,{}},
        },
        [3] = {
            name = "幫會搶紅包",
            type = 21,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "成功搶到幫會紅包30次",
            condition = {64,30,{}},
        },
        [4] = {
            name = "幫會搶紅包",
            type = 21,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "成功搶到幫會紅包40次",
            condition = {64,40,{}},
        },
        [5] = {
            name = "幫會搶紅包",
            type = 21,
            star = 1,
            show_star = 5,
            reward = 305106,
            desc = "成功搶到幫會紅包50次",
            condition = {64,50,{}},
        },
    },
    [3101] = {
        [1] = {
            name = "打造裝備",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "成功打造3件裝備",
            condition = {65,3,{0}},
        },
        [2] = {
            name = "打造裝備",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "成功打造15件裝備",
            condition = {65,15,{0}},
        },
        [3] = {
            name = "打造裝備",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "成功打造100件裝備",
            condition = {65,100,{0}},
        },
        [4] = {
            name = "打造裝備",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "成功打造200件裝備",
            condition = {65,200,{0}},
        },
        [5] = {
            name = "打造裝備",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "成功打造300件裝備",
            condition = {65,300,{0}},
        },
    },
    [3102] = {
        [1] = {
            name = "打造入門",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "打造1件5星以上裝備",
            condition = {65,1,{5}},
        },
        [2] = {
            name = "打造入門",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305213,
            desc = "打造10件6星以上裝備，達成可獲得稱號：打造學徒",
            condition = {65,10,{6}},
        },
        [3] = {
            name = "打造入門",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305214,
            desc = "打造20件7星以上裝備，達成可獲得稱號：打造匠人",
            condition = {65,20,{7}},
        },
        [4] = {
            name = "打造入門",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305215,
            desc = "打造30件8星以上裝備，達成可獲得稱號：打造名家",
            condition = {65,30,{8}},
        },
        [5] = {
            name = "打造入門",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305216,
            desc = "打造30件9星以上裝備，達成可獲得稱號：打造大師",
            condition = {65,30,{9}},
        },
    },
    [3103] = {
        [1] = {
            name = "裝備強化",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "累積強化裝備10次",
            condition = {4,10,{}},
        },
        [2] = {
            name = "裝備強化",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305007,
            desc = "累積強化裝備100次",
            condition = {4,100,{}},
        },
        [3] = {
            name = "裝備強化",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305008,
            desc = "累積強化裝備320次",
            condition = {4,320,{}},
        },
        [4] = {
            name = "裝備強化",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305107,
            desc = "累積強化裝備500次",
            condition = {4,500,{}},
        },
        [5] = {
            name = "裝備強化",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305108,
            desc = "累積強化裝備800次",
            condition = {4,800,{}},
        },
    },
    [3104] = {
        [1] = {
            name = "鑲嵌寶石",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "全身鑲嵌寶石1級",
            condition = {83,8,{1}},
        },
        [2] = {
            name = "鑲嵌寶石",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305217,
            desc = "全身鑲嵌寶石3級，達成可獲得稱號：閃閃發光",
            condition = {83,8,{3}},
        },
        [3] = {
            name = "鑲嵌寶石",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305218,
            desc = "全身鑲嵌寶石5級，達成可獲得稱號：璀璨星光",
            condition = {83,8,{5}},
        },
        [4] = {
            name = "鑲嵌寶石",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305219,
            desc = "全身鑲嵌寶石6級，達成可獲得稱號：異流星光",
            condition = {83,8,{6}},
        },
        [5] = {
            name = "鑲嵌寶石",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305220,
            desc = "全身鑲嵌寶石7級，達成可獲得稱號：七轉璿光",
            condition = {83,8,{7}},
        },
    },
    [3105] = {
        [1] = {
            name = "神器神鑄",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "將神器神鑄1個槽位",
            condition = {66,1,{}},
        },
        [2] = {
            name = "神器神鑄",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305006,
            desc = "將神器神鑄2個槽位",
            condition = {66,2,{}},
        },
        [3] = {
            name = "神器神鑄",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305007,
            desc = "將神器神鑄3個槽位",
            condition = {66,3,{}},
        },
        [4] = {
            name = "神器神鑄",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "將神器神鑄4個槽位",
            condition = {66,4,{}},
        },
        [5] = {
            name = "神器神鑄",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "將神器神鑄5個槽位",
            condition = {66,5,{}},
        },
    },
    [3106] = {
        [1] = {
            name = "神器突破",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "將神器品階突破1級",
            condition = {34,1,{}},
        },
        [2] = {
            name = "神器突破",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305006,
            desc = "將神器品階突破2級",
            condition = {34,2,{}},
        },
        [3] = {
            name = "神器突破",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305007,
            desc = "將神器品階突破3級",
            condition = {34,3,{}},
        },
        [4] = {
            name = "神器突破",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "將神器品階突破4級",
            condition = {34,4,{}},
        },
        [5] = {
            name = "神器突破",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "將神器品階突破5級",
            condition = {34,5,{}},
        },
    },
    [3107] = {
        [1] = {
            name = "暗器修煉",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "將暗器修煉至10級",
            condition = {67,10,{}},
        },
        [2] = {
            name = "暗器修煉",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "將暗器修煉至30級",
            condition = {67,30,{}},
        },
        [3] = {
            name = "暗器修煉",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "將暗器修煉至50級",
            condition = {67,50,{}},
        },
        [4] = {
            name = "暗器修煉",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "將暗器修煉至70級",
            condition = {67,70,{}},
        },
        [5] = {
            name = "暗器修煉",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305106,
            desc = "將暗器修煉至90級",
            condition = {67,90,{}},
        },
    },
    [3108] = {
        [1] = {
            name = "暗器品質",
            type = 31,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "將暗器品質提升至150",
            condition = {68,150,{}},
        },
        [2] = {
            name = "暗器品質",
            type = 31,
            star = 1,
            show_star = 2,
            reward = 305007,
            desc = "將暗器品質提升至500",
            condition = {68,500,{}},
        },
        [3] = {
            name = "暗器品質",
            type = 31,
            star = 1,
            show_star = 3,
            reward = 305008,
            desc = "將暗器品質提升至1000",
            condition = {68,1000,{}},
        },
        [4] = {
            name = "暗器品質",
            type = 31,
            star = 1,
            show_star = 4,
            reward = 305010,
            desc = "將暗器品質提升至1500",
            condition = {68,1500,{}},
        },
        [5] = {
            name = "暗器品質",
            type = 31,
            star = 1,
            show_star = 5,
            reward = 305012,
            desc = "將暗器品質提升至2000",
            condition = {68,2000,{}},
        },
    },
    [3201] = {
        [1] = {
            name = "捕捉珍獸",
            type = 32,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "捕捉珍獸2只",
            condition = {79,2,{}},
        },
        [2] = {
            name = "捕捉珍獸",
            type = 32,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "捕捉珍獸50只",
            condition = {79,50,{}},
        },
        [3] = {
            name = "捕捉珍獸",
            type = 32,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "捕捉珍獸100只",
            condition = {79,100,{}},
        },
        [4] = {
            name = "捕捉珍獸",
            type = 32,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "捕捉珍獸200只",
            condition = {79,200,{}},
        },
        [5] = {
            name = "捕捉珍獸",
            type = 32,
            star = 1,
            show_star = 5,
            reward = 305009,
            desc = "捕捉珍獸500只",
            condition = {79,500,{}},
        },
    },
    [3202] = {
        [1] = {
            name = "捕獸入門",
            type = 32,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "捕捉25級攜帶珍獸10只",
            condition = {69,10,{25}},
        },
        [2] = {
            name = "捕獸能手",
            type = 32,
            star = 1,
            show_star = 2,
            reward = 305221,
            desc = "捕捉25級攜帶珍獸30只，達成可獲得稱號：捕獸能手",
            condition = {69,30,{25}},
        },
        [3] = {
            name = "捕獸達人",
            type = 32,
            star = 1,
            show_star = 3,
            reward = 305222,
            desc = "捕捉45級攜帶珍獸50只，達成可獲得稱號：捕獸達人",
            condition = {69,50,{45}},
        },
        [4] = {
            name = "捕獸名家",
            type = 32,
            star = 1,
            show_star = 4,
            reward = 305223,
            desc = "捕捉65級攜帶珍獸80只，達成可獲得稱號：捕獸名家",
            condition = {69,80,{65}},
        },
        [5] = {
            name = "捕獸大師",
            type = 32,
            star = 1,
            show_star = 5,
            reward = 305224,
            desc = "捕捉65級攜帶珍獸200只，達成可獲得稱號：捕獸大師",
            condition = {69,200,{65}},
        },
    },
    [3203] = {
        [1] = {
            name = "繁殖入門",
            type = 32,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "成功繁殖珍獸10只",
            condition = {21,10,{1}},
        },
        [2] = {
            name = "繁殖能手",
            type = 32,
            star = 1,
            show_star = 2,
            reward = 305225,
            desc = "成功繁殖20只6星以上珍獸，達成可獲得稱號：繁殖能手",
            condition = {21,20,{6}},
        },
        [3] = {
            name = "繁殖達人",
            type = 32,
            star = 1,
            show_star = 3,
            reward = 305226,
            desc = "成功繁殖30只7星以上珍獸，達成可獲得稱號：繁殖達人",
            condition = {21,30,{7}},
        },
        [4] = {
            name = "繁殖名家",
            type = 32,
            star = 1,
            show_star = 4,
            reward = 305227,
            desc = "成功繁殖30只8星以上珍獸，達成可獲得稱號：繁殖名家",
            condition = {21,40,{8}},
        },
        [5] = {
            name = "繁殖大師",
            type = 32,
            star = 1,
            show_star = 5,
            reward = 305228,
            desc = "成功繁殖30只9星以上珍獸，達成可獲得稱號：繁殖大師",
            condition = {21,50,{9}},
        },
    },
    [3204] = {
        [1] = {
            name = "珍獸提悟",
            type = 32,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "累積為珍獸成功提悟10次",
            condition = {70,10,{}},
        },
        [2] = {
            name = "珍獸提悟",
            type = 32,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "累積為珍獸成功提悟30次",
            condition = {70,30,{}},
        },
        [3] = {
            name = "珍獸提悟",
            type = 32,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "累積為珍獸成功提悟100次",
            condition = {70,100,{}},
        },
        [4] = {
            name = "珍獸提悟",
            type = 32,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "累積為珍獸成功提悟200次",
            condition = {70,200,{}},
        },
        [5] = {
            name = "珍獸提悟",
            type = 32,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "累積為珍獸成功提悟300次",
            condition = {70,300,{}},
        },
    },
    [4101] = {
        [1] = {
            name = "挑戰老三環",
            type = 41,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "組隊完成老三環副本1次",
            condition = {17,1,{700}},
        },
        [2] = {
            name = "挑戰老三環",
            type = 41,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "組隊完成老三環副本10次",
            condition = {17,10,{700}},
        },
        [3] = {
            name = "挑戰老三環",
            type = 41,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "組隊完成老三環副本30次",
            condition = {17,30,{700}},
        },
        [4] = {
            name = "挑戰老三環",
            type = 41,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "組隊完成老三環副本100次",
            condition = {17,100,{700}},
        },
        [5] = {
            name = "挑戰老三環",
            type = 41,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "組隊完成老三環副本300次",
            condition = {17,300,{700}},
        },
    },
    [4102] = {
        [1] = {
            name = "挑戰燕子塢",
            type = 41,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "組隊完成燕子塢副本1次",
            condition = {17,1,{800}},
        },
        [2] = {
            name = "挑戰燕子塢",
            type = 41,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "組隊完成燕子塢副本10次",
            condition = {17,10,{800}},
        },
        [3] = {
            name = "挑戰燕子塢",
            type = 41,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "組隊完成燕子塢副本30次",
            condition = {17,30,{800}},
        },
        [4] = {
            name = "挑戰燕子塢",
            type = 41,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "組隊完成燕子塢副本100次",
            condition = {17,100,{800}},
        },
        [5] = {
            name = "挑戰燕子塢",
            type = 41,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "組隊完成燕子塢副本300次",
            condition = {17,300,{800}},
        },
    },
    [4103] = {
        [1] = {
            name = "挑戰四絕莊",
            type = 41,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "組隊完成四絕莊副本1次",
            condition = {17,1,{900}},
        },
        [2] = {
            name = "挑戰四絕莊",
            type = 41,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "組隊完成四絕莊副本10次",
            condition = {17,10,{900}},
        },
        [3] = {
            name = "挑戰四絕莊",
            type = 41,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "組隊完成四絕莊副本30次",
            condition = {17,30,{900}},
        },
        [4] = {
            name = "挑戰四絕莊",
            type = 41,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "組隊完成四絕莊副本100次",
            condition = {17,100,{900}},
        },
        [5] = {
            name = "挑戰四絕莊",
            type = 41,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "組隊完成四絕莊副本300次",
            condition = {17,300,{900}},
        },
    },
    [4104] = {
        [1] = {
            name = "挑戰縹緲峰",
            type = 41,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "組隊完成縹緲峰副本1次",
            condition = {17,1,{1000}},
        },
        [2] = {
            name = "挑戰縹緲峰",
            type = 41,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "組隊完成縹緲峰副本10次",
            condition = {17,10,{1000}},
        },
        [3] = {
            name = "挑戰縹緲峰",
            type = 41,
            star = 1,
            show_star = 3,
            reward = 305103,
            desc = "組隊完成縹緲峰副本30次",
            condition = {17,30,{1000}},
        },
        [4] = {
            name = "挑戰縹緲峰",
            type = 41,
            star = 1,
            show_star = 4,
            reward = 305104,
            desc = "組隊完成縹緲峰副本100次",
            condition = {17,100,{1000}},
        },
        [5] = {
            name = "挑戰縹緲峰",
            type = 41,
            star = 1,
            show_star = 5,
            reward = 305105,
            desc = "組隊完成縹緲峰副本300次",
            condition = {17,300,{1000}},
        },
    },
    [4301] = {
        [1] = {
            name = "常勝將軍",
            type = 43,
            star = 1,
            show_star = 1,
            reward = 305006,
            desc = "門派競技累計獲勝10場",
            condition = {71,10,{}},
        },
        [2] = {
            name = "常勝將軍",
            type = 43,
            star = 1,
            show_star = 2,
            reward = 305008,
            desc = "門派競技累計獲勝20場",
            condition = {71,20,{}},
        },
        [3] = {
            name = "常勝將軍",
            type = 43,
            star = 1,
            show_star = 3,
            reward = 305011,
            desc = "門派競技累計獲勝40場",
            condition = {71,40,{}},
        },
        [4] = {
            name = "常勝將軍",
            type = 43,
            star = 1,
            show_star = 4,
            reward = 305014,
            desc = "門派競技累計獲勝70場",
            condition = {71,70,{}},
        },
        [5] = {
            name = "常勝將軍",
            type = 43,
            star = 1,
            show_star = 5,
            reward = 305016,
            desc = "門派競技累計獲勝100場",
            condition = {71,100,{}},
        },
    },
    [4302] = {
        [1] = {
            name = "超神殺戮",
            type = 43,
            star = 1,
            show_star = 1,
            reward = 305010,
            desc = "門派競技連勝2場",
            condition = {72,2,{}},
        },
        [2] = {
            name = "超神殺戮",
            type = 43,
            star = 1,
            show_star = 2,
            reward = 305013,
            desc = "門派競技連勝4場",
            condition = {72,4,{}},
        },
        [3] = {
            name = "超神殺戮",
            type = 43,
            star = 1,
            show_star = 3,
            reward = 305015,
            desc = "門派競技連勝6場",
            condition = {72,6,{}},
        },
        [4] = {
            name = "超神殺戮",
            type = 43,
            star = 1,
            show_star = 4,
            reward = 305016,
            desc = "門派競技連勝7場",
            condition = {72,7,{}},
        },
        [5] = {
            name = "超神殺戮",
            type = 43,
            star = 1,
            show_star = 5,
            reward = 305017,
            desc = "門派競技連勝8場",
            condition = {72,8,{}},
        },
    },
    [4303] = {
        [1] = {
            name = "門派精英",
            type = 43,
            star = 1,
            show_star = 1,
            reward = 305013,
            desc = "門派競技進入前30名累計1次",
            condition = {73,1,{30}},
        },
        [2] = {
            name = "門派精英",
            type = 43,
            star = 1,
            show_star = 2,
            reward = 305016,
            desc = "門派競技進入前30名累計3次",
            condition = {73,3,{30}},
        },
        [3] = {
            name = "門派精英",
            type = 43,
            star = 1,
            show_star = 3,
            reward = 305017,
            desc = "門派競技進入前30名累計6次",
            condition = {73,6,{30}},
        },
        [4] = {
            name = "門派精英",
            type = 43,
            star = 1,
            show_star = 4,
            reward = 305018,
            desc = "門派競技進入前30名累計12次",
            condition = {73,12,{30}},
        },
        [5] = {
            name = "門派精英",
            type = 43,
            star = 1,
            show_star = 5,
            reward = 305019,
            desc = "門派競技進入前30名累計20次",
            condition = {73,20,{30}},
        },
    },
    [4304] = {
        [1] = {
            name = "內戰王者",
            type = 43,
            star = 1,
            show_star = 1,
            reward = 305016,
            desc = "累計獲得門派競技冠軍1次",
            condition = {73,1,{1}},
        },
        [2] = {
            name = "內戰王者",
            type = 43,
            star = 1,
            show_star = 2,
            reward = 305018,
            desc = "累計獲得門派競技冠軍3次",
            condition = {73,3,{1}},
        },
        [3] = {
            name = "內戰王者",
            type = 43,
            star = 1,
            show_star = 3,
            reward = 305019,
            desc = "累計獲得門派競技冠軍6次",
            condition = {73,6,{1}},
        },
        [4] = {
            name = "內戰王者",
            type = 43,
            star = 1,
            show_star = 4,
            reward = 305020,
            desc = "累計獲得門派競技冠軍12次",
            condition = {73,12,{1}},
        },
        [5] = {
            name = "內戰王者",
            type = 43,
            star = 1,
            show_star = 5,
            reward = 305021,
            desc = "累計獲得門派競技冠軍20次",
            condition = {73,20,{1}},
        },
    },
    [5101] = {
        [1] = {
            name = "奪寶馬賊",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "完成馬賊任務5輪",
            condition = {81,5,{}},
        },
        [2] = {
            name = "奪寶馬賊",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "完成馬賊任務35輪",
            condition = {81,35,{}},
        },
        [3] = {
            name = "奪寶馬賊",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "完成馬賊任務100輪",
            condition = {81,100,{}},
        },
        [4] = {
            name = "奪寶馬賊",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "完成馬賊任務300輪",
            condition = {81,300,{}},
        },
        [5] = {
            name = "奪寶馬賊",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "完成馬賊任務500輪",
            condition = {81,500,{}},
        },
    },
    [5102] = {
        [1] = {
            name = "殺馬隊長",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "帶隊完成馬賊任務1輪",
            condition = {74,1,{}},
        },
        [2] = {
            name = "殺馬隊長",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "帶隊完成馬賊任務5輪",
            condition = {74,5,{}},
        },
        [3] = {
            name = "殺馬隊長",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "帶隊完成馬賊任務20輪",
            condition = {74,20,{}},
        },
        [4] = {
            name = "殺馬隊長",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "帶隊完成馬賊任務50輪",
            condition = {74,50,{}},
        },
        [5] = {
            name = "殺馬隊長",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "帶隊完成馬賊任務100輪",
            condition = {74,100,{}},
        },
    },
    [5104] = {
        [1] = {
            name = "科舉考試",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "完成1次科舉考試，每次答對全部10題",
            condition = {82,1,{}},
        },
        [2] = {
            name = "科舉考試",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "完成3次科舉考試，每次答對全部10題",
            condition = {82,3,{}},
        },
        [3] = {
            name = "科舉考試",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "完成10次科舉考試，每次答對全部10題",
            condition = {82,10,{}},
        },
        [4] = {
            name = "科舉考試",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "完成30次科舉考試，每次答對全部10題",
            condition = {82,30,{}},
        },
        [5] = {
            name = "科舉考試",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "完成50次科舉考試，每次答對全部10題",
            condition = {82,50,{}},
        },
    },
    [5105] = {
        [1] = {
            name = "珍瓏棋局",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "完成2次珍瓏棋局活動",
            condition = {17,2,{1200}},
        },
        [2] = {
            name = "珍瓏棋局",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "完成20次珍瓏棋局活動",
            condition = {17,20,{1200}},
        },
        [3] = {
            name = "珍瓏棋局",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "完成100次珍瓏棋局活動",
            condition = {17,100,{1200}},
        },
        [4] = {
            name = "珍瓏棋局",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "完成200次珍瓏棋局活動",
            condition = {17,200,{1200}},
        },
        [5] = {
            name = "珍瓏棋局",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "完成300次珍瓏棋局活動",
            condition = {17,300,{1200}},
        },
    },
    [5106] = {
        [1] = {
            name = "黃金棋子",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "殺死1個黃金棋子",
            condition = {77,1,{}},
        },
        [2] = {
            name = "黃金棋子",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "殺死10個黃金棋子",
            condition = {77,10,{}},
        },
        [3] = {
            name = "黃金棋子",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "殺死30個黃金棋子",
            condition = {77,30,{}},
        },
        [4] = {
            name = "黃金棋子",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "殺死80個黃金棋子",
            condition = {77,80,{}},
        },
        [5] = {
            name = "黃金棋子",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "殺死150個黃金棋子",
            condition = {77,150,{}},
        },
    },
    [5107] = {
        [1] = {
            name = "宋遼大戰",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "參加宋遼大戰1次",
            condition = {33,1,{}},
        },
        [2] = {
            name = "宋遼大戰",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "參加宋遼大戰4次",
            condition = {33,4,{}},
        },
        [3] = {
            name = "宋遼大戰",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "參加宋遼大戰50次",
            condition = {33,50,{}},
        },
        [4] = {
            name = "宋遼大戰",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "參加宋遼大戰120次",
            condition = {33,120,{}},
        },
        [5] = {
            name = "宋遼大戰",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "參加宋遼大戰240次",
            condition = {33,240,{}},
        },
    },
    [5108] = {
        [1] = {
            name = "宋遼獲勝",
            type = 51,
            star = 1,
            show_star = 1,
            reward = 305101,
            desc = "獲勝宋遼大戰1次",
            condition = {78,1,{}},
        },
        [2] = {
            name = "宋遼獲勝",
            type = 51,
            star = 1,
            show_star = 2,
            reward = 305102,
            desc = "獲勝宋遼大戰3次",
            condition = {78,3,{}},
        },
        [3] = {
            name = "宋遼獲勝",
            type = 51,
            star = 1,
            show_star = 3,
            reward = 305006,
            desc = "獲勝宋遼大戰15次",
            condition = {78,15,{}},
        },
        [4] = {
            name = "宋遼獲勝",
            type = 51,
            star = 1,
            show_star = 4,
            reward = 305007,
            desc = "獲勝宋遼大戰30次",
            condition = {78,30,{}},
        },
        [5] = {
            name = "宋遼獲勝",
            type = 51,
            star = 1,
            show_star = 5,
            reward = 305008,
            desc = "獲勝宋遼大戰60次",
            condition = {78,60,{}},
        },
    },
}
