config.marry_skill = {
    [40000001] = {
        {
            level = 1,
            love = 3000,
            desc = "冷卻時間：600",
            cd = 600,
        },
        {
            level = 2,
            love = 10000,
            desc = "冷卻時間：580",
            cd = 580,
        },
        {
            level = 3,
            love = 50000,
            desc = "冷卻時間：560",
            cd = 560,
        },
        {
            level = 4,
            love = 100000,
            desc = "冷卻時間：540",
            cd = 540,
        },
        {
            level = 5,
            love = 200000,
            desc = "冷卻時間：520",
            cd = 520,
        },
        {
            level = 6,
            love = 300000,
            desc = "冷卻時間：500",
            cd = 500,
        },
        {
            level = 7,
            love = 400000,
            desc = "冷卻時間：480",
            cd = 480,
        },
        {
            level = 8,
            love = 500000,
            desc = "冷卻時間：460",
            cd = 460,
        },
        {
            level = 9,
            love = 600000,
            desc = "冷卻時間：440",
            cd = 440,
        },
        {
            level = 10,
            love = 700000,
            desc = "冷卻時間：420",
            cd = 420,
        },
    },
    [40000002] = {
        {
            level = 1,
            love = 3000,
            desc = "血氣回復：10",
            cd = 0,
        },
        {
            level = 2,
            love = 10000,
            desc = "血氣回復：15",
            cd = 0,
        },
        {
            level = 3,
            love = 50000,
            desc = "血氣回復：20",
            cd = 0,
        },
        {
            level = 4,
            love = 100000,
            desc = "血氣回復：25",
            cd = 0,
        },
        {
            level = 5,
            love = 200000,
            desc = "血氣回復：30",
            cd = 0,
        },
        {
            level = 6,
            love = 300000,
            desc = "血氣回復：35",
            cd = 0,
        },
        {
            level = 7,
            love = 400000,
            desc = "血氣回復：40",
            cd = 0,
        },
        {
            level = 8,
            love = 500000,
            desc = "血氣回復：45",
            cd = 0,
        },
        {
            level = 9,
            love = 600000,
            desc = "血氣回復：50",
            cd = 0,
        },
        {
            level = 10,
            love = 700000,
            desc = "血氣回復：55",
            cd = 0,
        },
    },
    [40000003] = {
        {
            level = 1,
            love = 3000,
            desc = "血上限提高：1240",
            cd = 0,
        },
        {
            level = 2,
            love = 10000,
            desc = "血上限提高：1680",
            cd = 0,
        },
        {
            level = 3,
            love = 50000,
            desc = "血上限提高：2120",
            cd = 0,
        },
        {
            level = 4,
            love = 100000,
            desc = "血上限提高：2560",
            cd = 0,
        },
        {
            level = 5,
            love = 200000,
            desc = "血上限提高：3000",
            cd = 0,
        },
        {
            level = 6,
            love = 300000,
            desc = "血上限提高：3440",
            cd = 0,
        },
        {
            level = 7,
            love = 400000,
            desc = "血上限提高：3880",
            cd = 0,
        },
        {
            level = 8,
            love = 500000,
            desc = "血上限提高：4320",
            cd = 0,
        },
        {
            level = 9,
            love = 600000,
            desc = "血上限提高：4760",
            cd = 0,
        },
        {
            level = 10,
            love = 700000,
            desc = "血上限提高：5200",
            cd = 0,
        },
    },
    [40000004] = {
        {
            level = 1,
            love = 3000,
            desc = "冷卻時間：600",
            cd = 600,
        },
        {
            level = 2,
            love = 10000,
            desc = "冷卻時間：580",
            cd = 580,
        },
        {
            level = 3,
            love = 50000,
            desc = "冷卻時間：560",
            cd = 560,
        },
        {
            level = 4,
            love = 100000,
            desc = "冷卻時間：540",
            cd = 540,
        },
        {
            level = 5,
            love = 200000,
            desc = "冷卻時間：520",
            cd = 520,
        },
        {
            level = 6,
            love = 300000,
            desc = "冷卻時間：500",
            cd = 500,
        },
        {
            level = 7,
            love = 400000,
            desc = "冷卻時間：480",
            cd = 480,
        },
        {
            level = 8,
            love = 500000,
            desc = "冷卻時間：460",
            cd = 460,
        },
        {
            level = 9,
            love = 600000,
            desc = "冷卻時間：440",
            cd = 440,
        },
        {
            level = 10,
            love = 700000,
            desc = "冷卻時間：420",
            cd = 420,
        },
    },
}