config.battle_career_fact = {
    [0] = {
	    career = 0,
	    ice_factor = 1,
	    fire_factor = 1,		
		dark_factor = 1,
		poison_factor = 1,
		cure_fact = 1,
		attr_cure_fact = 1,		
		inner_fact = 0.7,
		outer_fact = 0.7,		
	},
    [1] = {
	    career = 1,
	    ice_factor = 1,
	    fire_factor = 1,		
		dark_factor = 1,
		poison_factor = 1.5,
		cure_fact = 1,
		attr_cure_fact = 1,		
		inner_fact = 1,
		outer_fact = 0.2,		
	},
    [2] = {
	    career = 2,
	    ice_factor = 1,
	    fire_factor = 1.5,		
		dark_factor = 1,
		poison_factor = 1,
		cure_fact = 1,
		attr_cure_fact = 1,		
		inner_fact = 0.2,
		outer_fact = 1,		
	},
    [3] = {
	    career = 3,
	    ice_factor = 1,
	    fire_factor = 1,		
		dark_factor = 1.5,
		poison_factor = 1,
		cure_fact = 1,
		attr_cure_fact = 1,		
		inner_fact = 1,
		outer_fact = 0.2,		
	},
    [4] = {
	    career = 4,
	    ice_factor = 1.5,
	    fire_factor = 1,		
		dark_factor = 1,
		poison_factor = 1,
		cure_fact = 1,
		attr_cure_fact = 1,		
		inner_fact = 0.2,
		outer_fact = 1,		
	},
}

