config.artifact_avatar = {
    [1] = {
        [1100] = {
            id = 1100,
            name = "默認幻化",
            lv = 0,
            item_id = 16410101,
            model = 1001,
            attr = {},
            desc = "默認幻化",
            visible = 1,
        },
    },
    [2] = {
        [1200] = {
            id = 1200,
            name = "默認幻化",
            lv = 0,
            item_id = 16410201,
            model = 2001,
            attr = {},
            desc = "默認幻化",
            visible = 1,
        },
    },
    [3] = {
        [1300] = {
            id = 1300,
            name = "默認幻化",
            lv = 0,
            item_id = 16410301,
            model = 3001,
            attr = {},
            desc = "默認幻化",
            visible = 1,
        },
    },
    [4] = {
        [1400] = {
            id = 1400,
            name = "默認幻化",
            lv = 0,
            item_id = 16410401,
            model = 4001,
            attr = {},
            desc = "默認幻化",
            visible = 1,
        },
    },
    [0] = {
        [1500] = {
            id = 1500,
            name = "泣血鉤",
            lv = 0,
            item_id = 16420207,
            model = 32010,
            attr = {},
            desc = "刀出見血",
            visible = 1,
        },
        [1501] = {
            id = 1501,
            name = "繁花似錦",
            lv = 0,
            item_id = 16410007,
            model = 21008,
            attr = {},
            desc = "白玫瑰代表著純潔天真",
            visible = 1,
        },
        [1502] = {
            id = 1502,
            name = "清凉夏日",
            lv = 0,
            item_id = 16410008,
            model = 21002,
            attr = {},
            desc = "來吃雪糕吧",
            visible = 1,
        },
        [1503] = {
            id = 1503,
            name = "逃之夭夭",
            lv = 0,
            item_id = 16410009,
            model = 4002,
            attr = {{32,10},{22,176}},
            desc = "逃之夭夭",
            visible = 0,
        },
        [1504] = {
            id = 1504,
            name = "星空棒棒糖",
            lv = 0,
            item_id = 16410010,
            model = 4003,
            attr = {{32,10},{22,176}},
            desc = "星空棒棒糖",
            visible = 0,
        },
    },
}