config.career_battle_win = {
    [1] = {     
        [1] =  {
            times = 1,                
            grade = 1,                
            get_score = 90,
            defend_get_score = 5,
        },
        [2] =  {
            times = 2,                
            grade = 1,                
            get_score = 101,
            defend_get_score = 10,
        },
        [3] =  {
            times = 3,                
            grade = 1,                
            get_score = 112,
            defend_get_score = 15,
        },
        [4] =  {
            times = 4,                
            grade = 1,                
            get_score = 124,
            defend_get_score = 20,
        },
        [5] =  {
            times = 5,                
            grade = 1,                
            get_score = 136,
            defend_get_score = 25,
        },
        [6] =  {
            times = 6,                
            grade = 1,                
            get_score = 148,
            defend_get_score = 30,
        },
        [7] =  {
            times = 7,                
            grade = 1,                
            get_score = 160,
            defend_get_score = 35,
        },
        [8] =  {
            times = 8,                
            grade = 1,                
            get_score = 172,
            defend_get_score = 40,
        },
        [9] =  {
            times = 9,                
            grade = 1,                
            get_score = 184,
            defend_get_score = 45,
        },
        [10] =  {
            times = 10,                
            grade = 1,                
            get_score = 196,
            defend_get_score = 50,
        },
    },
    [2] = {     
        [1] =  {
            times = 1,                
            grade = 2,                
            get_score = 90,
            defend_get_score = 5,
        },
        [2] =  {
            times = 2,                
            grade = 2,                
            get_score = 101,
            defend_get_score = 10,
        },
        [3] =  {
            times = 3,                
            grade = 2,                
            get_score = 112,
            defend_get_score = 15,
        },
        [4] =  {
            times = 4,                
            grade = 2,                
            get_score = 124,
            defend_get_score = 20,
        },
        [5] =  {
            times = 5,                
            grade = 2,                
            get_score = 136,
            defend_get_score = 25,
        },
        [6] =  {
            times = 6,                
            grade = 2,                
            get_score = 148,
            defend_get_score = 30,
        },
        [7] =  {
            times = 7,                
            grade = 2,                
            get_score = 160,
            defend_get_score = 35,
        },
        [8] =  {
            times = 8,                
            grade = 2,                
            get_score = 172,
            defend_get_score = 40,
        },
        [9] =  {
            times = 9,                
            grade = 2,                
            get_score = 184,
            defend_get_score = 45,
        },
        [10] =  {
            times = 10,                
            grade = 2,                
            get_score = 196,
            defend_get_score = 50,
        },
    },
    [3] = {     
        [1] =  {
            times = 1,                
            grade = 3,                
            get_score = 90,
            defend_get_score = 5,
        },
        [2] =  {
            times = 2,                
            grade = 3,                
            get_score = 101,
            defend_get_score = 10,
        },
        [3] =  {
            times = 3,                
            grade = 3,                
            get_score = 112,
            defend_get_score = 15,
        },
        [4] =  {
            times = 4,                
            grade = 3,                
            get_score = 124,
            defend_get_score = 20,
        },
        [5] =  {
            times = 5,                
            grade = 3,                
            get_score = 136,
            defend_get_score = 25,
        },
        [6] =  {
            times = 6,                
            grade = 3,                
            get_score = 148,
            defend_get_score = 30,
        },
        [7] =  {
            times = 7,                
            grade = 3,                
            get_score = 160,
            defend_get_score = 35,
        },
        [8] =  {
            times = 8,                
            grade = 3,                
            get_score = 172,
            defend_get_score = 40,
        },
        [9] =  {
            times = 9,                
            grade = 3,                
            get_score = 184,
            defend_get_score = 45,
        },
        [10] =  {
            times = 10,                
            grade = 3,                
            get_score = 196,
            defend_get_score = 50,
        },
    },
    [4] = {     
        [1] =  {
            times = 1,                
            grade = 4,                
            get_score = 90,
            defend_get_score = 5,
        },
        [2] =  {
            times = 2,                
            grade = 4,                
            get_score = 101,
            defend_get_score = 10,
        },
        [3] =  {
            times = 3,                
            grade = 4,                
            get_score = 112,
            defend_get_score = 15,
        },
        [4] =  {
            times = 4,                
            grade = 4,                
            get_score = 124,
            defend_get_score = 20,
        },
        [5] =  {
            times = 5,                
            grade = 4,                
            get_score = 136,
            defend_get_score = 25,
        },
        [6] =  {
            times = 6,                
            grade = 4,                
            get_score = 148,
            defend_get_score = 30,
        },
        [7] =  {
            times = 7,                
            grade = 4,                
            get_score = 160,
            defend_get_score = 35,
        },
        [8] =  {
            times = 8,                
            grade = 4,                
            get_score = 172,
            defend_get_score = 40,
        },
        [9] =  {
            times = 9,                
            grade = 4,                
            get_score = 184,
            defend_get_score = 45,
        },
        [10] =  {
            times = 10,                
            grade = 4,                
            get_score = 196,
            defend_get_score = 50,
        },
    },
}