
local ModuleMgr = Class()

function ModuleMgr:_init()
	self.module_list = {}
	self.module_map = {}
end

function ModuleMgr:_delete()
	self:StopAllModule()
end

function ModuleMgr:LoadAllModule()
	require("game/platform/platform_ctrl")
    require("game/effect/effect_mgr")
	require("game/gamemsg/game_msg_ctrl")
    require("game/login/login_ctrl")
	require("game/fight/fight_ctrl")
	require("game/scene/scene")
	require("game/guide/guide_ctrl")
	require("game/main/main_ui_ctrl")
	require("game/bag/bag_ctrl")
	require("game/open_func/open_func_ctrl")
    require("game/gm/gm_ctrl")
	require("game/role/role_ctrl")
	require("game/red_point/red_point_ctrl")
	require("game/foundry/foundry_ctrl")
	require("game/world_map/world_map_ctrl")
	require("game/chat/chat_ctrl")
	require("game/god_equip/god_equip_ctrl")
	require("game/pet/pet_ctrl")
	require("game/shop/shop_ctrl")
	require("game/carbon/carbon_ctrl")
	require("game/mail/mail_ctrl")
	require("game/friend/friend_ctrl")
	require("game/daily_task/daily_task_ctrl")
	require("game/arena/arena_ctrl")
	require("game/monitor/monitor_ctrl")
	require("game/fashion/fashion_ctrl")
	require("game/pass_boss/pass_boss_ctrl")
	require("game/task/task_ctrl")
	require("game/skill/skill_ctrl")
	require("game/guild/guild_ctrl")
	require("game/marry/marry_ctrl")
	require("game/vip/vip_ctrl")
	require("game/rank/rank_ctrl")
	require("game/activity/activity_mgr_ctrl")
	require("game/surface_suit/surface_suit_ctrl")
	require("game/hero/hero_ctrl")
	require("game/reward_hall/reward_hall_ctrl")
	require("game/songliao_war/songliao_war_ctrl")
	require("game/lake_bandits/lake_bandits_ctrl")
	require("game/auction/auction_ctrl")
	require("game/world_boss/world_boss_ctrl")
	require("game/career_battle/career_battle_ctrl")
	require("game/overlord/overlord_ctrl")
	require("game/sys_setting/sys_setting_ctrl")
	require("game/make_team/make_team_ctrl")
	require("game/guild_arena/guild_arena_ctrl")
	require("game/field_battle/field_battle_ctrl")
	require("game/lake_exp/lake_exp_ctrl")
	require("game/exterior/exterior_ctrl")
	require("game/gather/gather_ctrl")
	require("game/guild_task/guild_task_ctrl")
	require("game/market/market_ctrl")
	require("game/recharge/recharge_ctrl")
	require("game/strengthen/strengthen_ctrl")
	require("game/mini_game/mini_game_ctrl")
	require("game/sworn/sworn_ctrl")
	require("game/mentor/mentor_ctrl")
	require("game/wulin_reward/wulin_reward_ctrl")
	require("game/society/society_ctrl")
	require("game/view_others/view_others_ctrl")
	require("game/imperial_examine/imperial_examine_ctrl")
	require("game/lucky_money/lucky_money_ctrl")
	require("game/jump/jump_ctrl")
	require("game/feedback/feedback_ctrl")
	require("game/achieve/achieve_ctrl")
	require("game/weapon_soul/weapon_soul_ctrl")
	require("game/dragon_design/dragon_design_ctrl")
	require("game/vow/vow_ctrl")
	require("game/msg_notice/msg_notice_ctrl")
	require("game/post_effect/post_effect_ctrl")
	require("game/firework/firework_ctrl")
	require("game/marry/marry_process_ctrl")
end

function ModuleMgr:StartAllModule()
	--  基础功能模块
	self:AddModule("platform_ctrl", game.PlatformCtrl.New())
	self:AddModule("effect", game.EffectMgr.New())
	self:AddModule("game_msg", game.GameMsgCtrl.New())
	self:AddModule("main_ui_ctrl", game.MainUICtrl.New())
	self:AddModule("open_func_ctrl", game.OpenFuncCtrl.New())
	self:AddModule("bag", game.BagCtrl.New())
	self:AddModule("gm", game.GmCtrl.New())
	self:AddModule("role", game.RoleCtrl.New())
	self:AddModule("red_point_ctrl", game.RedPointCtrl.New())
	self:AddModule("foundry_ctrl", game.FoundryCtrl.New())
	self:AddModule("world_map_ctrl", game.WorldMapCtrl.New())
	self:AddModule("chat_ctrl", game.ChatCtrl.New())
	self:AddModule("god_equip_ctrl", game.GodEquipCtrl.New())
	self:AddModule("pet_ctrl", game.PetCtrl.New())
	self:AddModule("shop_ctrl", game.ShopCtrl.New())
	self:AddModule("mail_ctrl", game.MailCtrl.New())
	self:AddModule("daily_task_ctrl", game.DailyTaskCtrl.New())
	self:AddModule("monitor_ctrl", game.MonitorCtrl.New())
	self:AddModule("fashion_ctrl", game.FashionCtrl.New())
	self:AddModule("pass_boss_ctrl", game.PassBossCtrl.New())
	self:AddModule("task_ctrl", game.TaskCtrl.New())
	self:AddModule("skill_ctrl", game.SkillCtrl.New())
	self:AddModule("guild_ctrl", game.GuildCtrl.New())
	self:AddModule("guide_ctrl", game.GuideCtrl.New())
	self:AddModule("marry_ctrl", game.MarryCtrl.New())
	self:AddModule("vip_ctrl", game.VipCtrl.New())
	self:AddModule("hero_ctrl", game.HeroCtrl.New())
	self:AddModule("lake_bandits_ctrl", game.LakeBanditsCtrl.New())
	self:AddModule("career_battle_ctrl", game.CareerBattleCtrl.New())
	self:AddModule("lake_exp_ctrl", game.LakeExpCtrl.New())
	self:AddModule("overlord_ctrl", game.OverlordCtrl.New())
	self:AddModule("exterior_ctrl", game.ExteriorCtrl.New())
	self:AddModule("guild_task_ctrl", game.GuildTaskCtrl.New())
	self:AddModule("market_ctrl", game.MarketCtrl.New())
	self:AddModule("recharge_ctrl", game.RechargeCtrl.New())
	self:AddModule("strengthen_ctrl", game.StrengthenCtrl.New())
	self:AddModule("mini_game_ctrl", game.MiniGameCtrl.New())
	self:AddModule("sworn_ctrl", game.SwornCtrl.New())
	self:AddModule("mentor_ctrl", game.MentorCtrl.New())
	self:AddModule("view_others_ctrl", game.ViewOthersCtrl.New())
	self:AddModule("imperial_examine_ctrl", game.ImperialExamineCtrl.New())
	self:AddModule("lucky_money_ctrl", game.LuckyMoneyCtrl.New())
	self:AddModule("feedback_ctrl", game.FeedbackCtrl.New())
	self:AddModule("achieve_ctrl", game.AchieveCtrl.New())

    -- 游戏系统模块
    self:AddModule("login", game.LoginCtrl.New())
    self:AddModule("fight", game.FightCtrl.New())
    self:AddModule("carbon_ctrl", game.CarbonCtrl.New())
    self:AddModule("friend_ctrl", game.FriendCtrl.New())
    self:AddModule("arena_ctrl", game.ArenaCtrl.New())
    self:AddModule("rank_ctrl", game.RankCtrl.New())
    self:AddModule("activity_mgr_ctrl", game.ActivityMgrCtrl.New())
    self:AddModule("surface_suit_ctrl", game.SurfaceSuitCtrl.New())
    self:AddModule("reward_hall_ctrl", game.RewardHallCtrl.New())
    self:AddModule("songliao_war_ctrl", game.SongliaoWarCtrl.New())
    self:AddModule("auction_ctrl", game.AuctionCtrl.New())
    self:AddModule("world_boss_ctrl", game.WorldBossCtrl.New())
    self:AddModule("sys_setting_ctrl", game.SysSettingCtrl.New())
    self:AddModule("make_team_ctrl", game.MakeTeamCtrl.New())
    self:AddModule("guild_arena_ctrl", game.GuildArenaCtrl.New())
    self:AddModule("field_battle_ctrl", game.FieldBattleCtrl.New())
    self:AddModule("gather_ctrl", game.GatherCtrl.New())
    self:AddModule("wulin_reward_ctrl", game.WulinRewardCtrl.New())
    self:AddModule("society_ctrl", game.SocietyCtrl.New())
    self:AddModule("jump_ctrl", game.JumpCtrl.New())
    self:AddModule("weapon_soul_ctrl", game.WeaponSoulCtrl.New())
    self:AddModule("dragon_design_ctrl", game.DragonDesignCtrl.New())
    self:AddModule("vow_ctrl", game.VowCtrl.New())
    self:AddModule("msg_notice_ctrl", game.MsgNoticeCtrl.New())
    self:AddModule("post_effect_ctrl", game.PostEffectCtrl.New())
    self:AddModule("firework_ctrl", game.FireworkCtrl.New())
    self:AddModule("marry_process_ctrl", game.MarryProcessCtrl.New())

	-- 依赖性较强的功能模块
    self:AddModule("scene", game.Scene.New())
end

function ModuleMgr:StopAllModule()
	for i=#self.module_list, 1, -1 do
		self.module_list[i]:DeleteMe()
	end
	self.module_list = {}
	self.module_map = {}
end

function ModuleMgr:AddModule(name, model)
	if self.module_map[name] then
		error("Module Has Exist " .. name)
	end
	self.module_map[name] = model
	table.insert(self.module_list, model)
end

function ModuleMgr:GetModule(name)
	return self.module_map[name]
end

game.ModuleMgr = ModuleMgr.New()
