
game = {}

require("game/game_config")
require("game/game_help")
require("game/config_help/init")
require("game/events_config")
require("game/common/render/render_unit")
require("game/common/gamenet/gamenet")
require("game/common/gamenet/gamenet_init")
require("game/common/mvc/base_ctrl")
require("game/common/mvc/base_view")
require("game/common/mvc/base_data")
require("game/common/mvc/event_handler")
require("game/common/mvc/ui_template")
require("game/common/mvc/ui_list")
require("game/common/mvc/view_mgr")
require("game/common/module/modules_mgr")
require("game/common/gameloop/gameloop")
require("game/common/sdk_mgr/sdk_mgr")
require("game/common/voice_mgr/voice_mgr")
require("game/common/service_mgr/service_mgr")
require("game/common/anim_mgr/anim_mgr")
require("game/common/cache_mgr/cache_mgr")
require("game/common/utils/utils")
require("game/game_pool")
require("game/ai/ai_mgr")
